var annotated_dup =
[
    [ "cJSON", "structcJSON.html", "structcJSON" ],
    [ "cJSON_Hooks", "structcJSON__Hooks.html", "structcJSON__Hooks" ],
    [ "error", "structerror.html", "structerror" ],
    [ "internal_hooks", "structinternal__hooks.html", "structinternal__hooks" ],
    [ "mb_conn", "structmb__conn.html", "structmb__conn" ],
    [ "mb_init_args", "structmb__init__args.html", "structmb__init__args" ],
    [ "mbpg_ctx", "structmbpg__ctx.html", "structmbpg__ctx" ],
    [ "modbus_ctx", "structmodbus__ctx.html", "structmodbus__ctx" ],
    [ "parse_buffer", "structparse__buffer.html", "structparse__buffer" ],
    [ "pg_col_metadata", "structpg__col__metadata.html", "structpg__col__metadata" ],
    [ "pg_table_info", "structpg__table__info.html", "structpg__table__info" ],
    [ "postgres_ctx", "structpostgres__ctx.html", "structpostgres__ctx" ],
    [ "pq_col_all_metadata", "structpq__col__all__metadata.html", "structpq__col__all__metadata" ],
    [ "printbuffer", "structprintbuffer.html", "structprintbuffer" ],
    [ "sdb__log_module__", "structsdb____log__module____.html", "structsdb____log__module____" ],
    [ "sdb__thread_arenas__", "structsdb____thread__arenas____.html", "structsdb____thread__arenas____" ],
    [ "sdb_arena", "structsdb__arena.html", "structsdb__arena" ],
    [ "sdb_file_data", "structsdb__file__data.html", "structsdb__file__data" ],
    [ "sdb_mmap", "structsdb__mmap.html", "structsdb__mmap" ],
    [ "sdb_scratch_arena", "structsdb__scratch__arena.html", "structsdb__scratch__arena" ],
    [ "sdb_slice", "structsdb__slice.html", "structsdb__slice" ],
    [ "sdb_string_header", "structsdb__string__header.html", "structsdb__string__header" ],
    [ "sdb_thread_control", "structsdb__thread__control.html", "structsdb__thread__control" ],
    [ "sdb_token", "structsdb__token.html", "structsdb__token" ],
    [ "sensor_data_pipe", "structsensor__data__pipe.html", "structsensor__data__pipe" ],
    [ "signal_handler_context", "structsignal__handler__context.html", "structsignal__handler__context" ],
    [ "tg_group", "structtg__group.html", "structtg__group" ],
    [ "tg_manager", "structtg__manager.html", "structtg__manager" ]
];