Sensor Data Handler System: src/Libs/cJSON/cJSON.h File Reference
cJSON.h File Reference
#include <stddef.h>
Classes
struct cJSON
struct cJSON_Hooks
Macros
#define cJSON_Array (1 << 5)
#define cJSON_ArrayForEach(element, array) for(element = (array != NULL) ? (array)->child : NULL; element != NULL; element = element->next)
#define CJSON_CDECL
#define CJSON_CIRCULAR_LIMIT 10000
#define cJSON_False (1 << 0)
#define cJSON_Invalid (0)
#define cJSON_IsReference 256
#define CJSON_NESTING_LIMIT 1000
#define cJSON_NULL (1 << 2)
#define cJSON_Number (1 << 3)
#define cJSON_Object (1 << 6)
#define CJSON_PUBLIC(type) type
#define cJSON_Raw (1 << 7) /* raw json */
#define cJSON_SetBoolValue(object, boolValue)
#define cJSON_SetIntValue(object, number) ((object) ? (object)->valueint = (object)->valuedouble = (number) : (number))
#define cJSON_SetNumberValue(object, number) ((object != NULL) ? cJSON_SetNumberHelper(object, (double)number) : (number))
#define CJSON_STDCALL
#define cJSON_String (1 << 4)
#define cJSON_StringIsConst 512
#define cJSON_True (1 << 1)
#define CJSON_VERSION_MAJOR 1
#define CJSON_VERSION_MINOR 7
#define CJSON_VERSION_PATCH 18
Typedefs
typedef struct cJSON cJSON
typedef int cJSON_bool
typedef struct cJSON_Hooks cJSON_Hooks
Functions
cJSON_AddBoolToObject (cJSON *const object, const char *const name, const cJSON_bool boolean)
cJSON_AddItemReferenceToObject (cJSON *object, const char *string, cJSON *item)
cJSON_AddItemToObjectCS (cJSON *object, const char *string, cJSON *item)
cJSON_AddNumberToObject (cJSON *const object, const char *const name, const double number)
cJSON_AddRawToObject (cJSON *const object, const char *const name, const char *const raw)
cJSON_AddStringToObject (cJSON *const object, const char *const name, const char *const string)
cJSON_Compare (const cJSON *const a, const cJSON *const b, const cJSON_bool case_sensitive)
cJSON_DetachItemFromObjectCaseSensitive (cJSON *object, const char *string)
cJSON_GetObjectItemCaseSensitive (const cJSON *const object, const char *const string)
cJSON_InsertItemInArray (cJSON *array, int which, cJSON *newitem)
cJSON_ParseWithLengthOpts (const char *value, size_t buffer_length, const char **return_parse_end, cJSON_bool require_null_terminated)
cJSON_ParseWithOpts (const char *value, const char **return_parse_end, cJSON_bool require_null_terminated)
cJSON_PrintPreallocated (cJSON *item, char *buffer, const int length, const cJSON_bool format)
CJSON_PUBLIC (char *) cJSON_Print(const cJSON *item)
CJSON_PUBLIC (cJSON *) cJSON_Parse(const char *value)
CJSON_PUBLIC (const char *) cJSON_Version(void)
CJSON_PUBLIC (double) cJSON_GetNumberValue(const cJSON *const item)
CJSON_PUBLIC (int) cJSON_GetArraySize(const cJSON *array)
CJSON_PUBLIC (void *) cJSON_malloc(size_t size)
CJSON_PUBLIC (void) cJSON_InitHooks(cJSON_Hooks *hooks)
cJSON_ReplaceItemInObject (cJSON *object, const char *string, cJSON *newitem)
cJSON_ReplaceItemInObjectCaseSensitive (cJSON *object, const char *string, cJSON *newitem)
cJSON_ReplaceItemViaPointer (cJSON *const parent, cJSON *const item, cJSON *replacement)
Variables
size_t buffer_length
int count
int cJSON_bool fmt
int index
cJSON * item
const char *const name
int cJSON * newitem
double number
int prebuffer
cJSON_bool recurse
const char *const string
const char * valuestring
int which
Macro Definition Documentation
cJSON_Array
#define cJSON_Array (1 << 5)
Definition at line 100 of file cJSON.h.
cJSON_ArrayForEach
#define cJSON_ArrayForEach (element, array) for(element = (array != NULL) ? (array)->child : NULL; element != NULL; element = element->next)
Definition at line 341 of file cJSON.h.
CJSON_CDECL
#define CJSON_CDECL
Definition at line 75 of file cJSON.h.
CJSON_CIRCULAR_LIMIT
#define CJSON_CIRCULAR_LIMIT 10000
Definition at line 152 of file cJSON.h.
cJSON_False
#define cJSON_False (1 << 0)
Definition at line 95 of file cJSON.h.
cJSON_Invalid
#define cJSON_Invalid (0)
Definition at line 94 of file cJSON.h.
cJSON_IsReference
#define cJSON_IsReference 256
Definition at line 104 of file cJSON.h.
CJSON_NESTING_LIMIT
#define CJSON_NESTING_LIMIT 1000
Definition at line 146 of file cJSON.h.
cJSON_NULL
#define cJSON_NULL (1 << 2)
Definition at line 97 of file cJSON.h.
cJSON_Number
#define cJSON_Number (1 << 3)
Definition at line 98 of file cJSON.h.
cJSON_Object
#define cJSON_Object (1 << 6)
Definition at line 101 of file cJSON.h.
CJSON_PUBLIC
#define CJSON_PUBLIC (type) type
Definition at line 82 of file cJSON.h.
cJSON_Raw
#define cJSON_Raw (1 << 7) /* raw json */
Definition at line 102 of file cJSON.h.
cJSON_SetBoolValue
#define cJSON_SetBoolValue (object, boolValue)
Value:
    ((object != NULL && ((object)->type & (cJSON_False | cJSON_True)))                             \
         ? (object)->type = ((object)->type & (~(cJSON_False | cJSON_True)))                       \
                          | ((boolValue) ? cJSON_True : cJSON_False)                               \
         : cJSON_Invalid)
Definition at line 334 of file cJSON.h.
cJSON_SetIntValue
#define cJSON_SetIntValue (object, number) ((object) ? (object)->valueint = (object)->valuedouble = (number) : (number))
Definition at line 322 of file cJSON.h.
cJSON_SetNumberValue
#define cJSON_SetNumberValue (object, number) ((object != NULL) ? cJSON_SetNumberHelper(object, (double)number) : (number))
Definition at line 326 of file cJSON.h.
CJSON_STDCALL
#define CJSON_STDCALL
Definition at line 76 of file cJSON.h.
cJSON_String
#define cJSON_String (1 << 4)
Definition at line 99 of file cJSON.h.
cJSON_StringIsConst
#define cJSON_StringIsConst 512
Definition at line 105 of file cJSON.h.
cJSON_True
#define cJSON_True (1 << 1)
Definition at line 96 of file cJSON.h.
CJSON_VERSION_MAJOR
#define CJSON_VERSION_MAJOR 1
Definition at line 87 of file cJSON.h.
CJSON_VERSION_MINOR
#define CJSON_VERSION_MINOR 7
Definition at line 88 of file cJSON.h.
CJSON_VERSION_PATCH
#define CJSON_VERSION_PATCH 18
Definition at line 89 of file cJSON.h.
Typedef Documentation
cJSON
typedef struct cJSON cJSON
cJSON_bool
typedef int cJSON_bool
Definition at line 141 of file cJSON.h.
cJSON_Hooks
typedef struct cJSON_Hooks cJSON_Hooks
Function Documentation
cJSON_AddBoolToObject()
cJSON_AddBoolToObject (cJSON *const object, const char *const name, const cJSON_bool boolean)
Definition at line 1970 of file cJSON.c.
References add_item_to_object(), global_hooks, and name.
cJSON_AddItemReferenceToObject()
cJSON_AddItemReferenceToObject (cJSON * object, const char * string, cJSON * item)
Definition at line 1926 of file cJSON.c.
References add_item_to_object(), create_reference(), global_hooks, and item.
cJSON_AddItemToObjectCS()
cJSON_AddItemToObjectCS (cJSON * object, const char * string, cJSON * item)
cJSON_AddNumberToObject()
cJSON_AddNumberToObject (cJSON *const object, const char *const name, const double number)
Definition at line 1982 of file cJSON.c.
References add_item_to_object(), global_hooks, name, and number.
cJSON_AddRawToObject()
cJSON_AddRawToObject (cJSON *const object, const char *const name, const char *const raw)
Definition at line 2006 of file cJSON.c.
References add_item_to_object(), global_hooks, and name.
cJSON_AddStringToObject()
cJSON_AddStringToObject (cJSON *const object, const char *const name, const char *const string)
Definition at line 1994 of file cJSON.c.
References add_item_to_object(), global_hooks, and name.
cJSON_Compare()
cJSON_Compare (const cJSON *const a, const cJSON *const b, const cJSON_bool case_sensitive)
Definition at line 2769 of file cJSON.c.
References cJSON::child, cJSON_Array, cJSON_ArrayForEach, cJSON_Compare(), cJSON_False, cJSON_NULL, cJSON_Number, cJSON_Object, cJSON_Raw, cJSON_String, cJSON_True, compare_double(), get_object_item(), cJSON::next, and cJSON::string.
Referenced by cJSON_Compare().
cJSON_DetachItemFromObjectCaseSensitive()
cJSON_DetachItemFromObjectCaseSensitive (cJSON * object, const char * string)
cJSON_GetObjectItemCaseSensitive()
cJSON_GetObjectItemCaseSensitive (const cJSON *const object, const char *const string)
Definition at line 1780 of file cJSON.c.
References get_object_item().
cJSON_InsertItemInArray()
cJSON_InsertItemInArray (cJSON * array, int which, cJSON * newitem)
cJSON_ParseWithLengthOpts()
cJSON_ParseWithLengthOpts (const char * value, size_t buffer_length, const char ** return_parse_end, cJSON_bool require_null_terminated)
Definition at line 1022 of file cJSON.c.
References buffer_at_offset, buffer_length, buffer_skip_whitespace(), cJSON_New_Item(), parse_buffer::content, global_error, global_hooks, parse_buffer::hooks, item, error::json, parse_buffer::length, parse_buffer::offset, parse_value(), error::position, and skip_utf8_bom().
Referenced by cJSON_ParseWithOpts().
cJSON_ParseWithOpts()
cJSON_ParseWithOpts (const char * value, const char ** return_parse_end, cJSON_bool require_null_terminated)
Definition at line 1004 of file cJSON.c.
References buffer_length, and cJSON_ParseWithLengthOpts().
Referenced by CJSON_PUBLIC().
cJSON_PrintPreallocated()
cJSON_PrintPreallocated (cJSON * item, char * buffer, const int length, const cJSON_bool format)
Definition at line 1210 of file cJSON.c.
References printbuffer::buffer, printbuffer::format, global_hooks, printbuffer::hooks, item, printbuffer::length, printbuffer::noalloc, printbuffer::offset, and print_value().
CJSON_PUBLIC() [1/7]
CJSON_PUBLIC (char *) const
CJSON_PUBLIC() [2/7]
CJSON_PUBLIC (cJSON *) const
CJSON_PUBLIC() [3/7]
CJSON_PUBLIC (const char *)
Definition at line 96 of file cJSON.c.
References global_error, error::json, and error::position.
CJSON_PUBLIC() [4/7]
CJSON_PUBLIC (double) const
CJSON_PUBLIC() [5/7]
CJSON_PUBLIC (int) const
CJSON_PUBLIC() [6/7]
CJSON_PUBLIC (void *)
Definition at line 2881 of file cJSON.c.
References internal_hooks::allocate(), and global_hooks.
CJSON_PUBLIC() [7/7]
CJSON_PUBLIC (void)
cJSON_ReplaceItemInObject()
cJSON_ReplaceItemInObject (cJSON * object, const char * string, cJSON * newitem)
Definition at line 2211 of file cJSON.c.
References newitem, and replace_item_in_object().
cJSON_ReplaceItemInObjectCaseSensitive()
cJSON_ReplaceItemInObjectCaseSensitive (cJSON * object, const char * string, cJSON * newitem)
Definition at line 2217 of file cJSON.c.
References newitem, and replace_item_in_object().
cJSON_ReplaceItemViaPointer()
cJSON_ReplaceItemViaPointer (cJSON *const parent, cJSON *const item, cJSON * replacement)
Definition at line 2138 of file cJSON.c.
References cJSON::child, item, cJSON::next, and cJSON::prev.
Referenced by replace_item_in_object().
Variable Documentation
buffer_length
size_t buffer_length
Definition at line 167 of file cJSON.h.
Referenced by cJSON_ParseWithLengthOpts(), and cJSON_ParseWithOpts().
count
int count
Definition at line 248 of file cJSON.h.
fmt
int cJSON_bool fmt
Definition at line 185 of file cJSON.h.
index
int index
Definition at line 198 of file cJSON.h.
Referenced by get_array_item().
item
cJSON *const item
Definition at line 254 of file cJSON.h.
Referenced by add_item_to_array(), add_item_to_object(), cJSON_AddItemReferenceToObject(), cJSON_Duplicate_rec(), cJSON_ParseWithLengthOpts(), cJSON_PrintPreallocated(), CJSON_PUBLIC(), CJSON_PUBLIC(), cJSON_ReplaceItemViaPointer(), create_reference(), parse_array(), parse_number(), parse_object(), parse_string(), parse_value(), print(), print_array(), print_number(), print_object(), print_string(), print_value(), and suffix_object().
name
const char *const name
Definition at line 307 of file cJSON.h.
Referenced by cJSON_AddBoolToObject(), cJSON_AddNumberToObject(), cJSON_AddRawToObject(), cJSON_AddStringToObject(), and get_object_item().
newitem
int cJSON* newitem
Definition at line 283 of file cJSON.h.
Referenced by cJSON_Duplicate_rec(), cJSON_ReplaceItemInObject(), and cJSON_ReplaceItemInObjectCaseSensitive().
number
double number
Definition at line 325 of file cJSON.h.
Referenced by cJSON_AddNumberToObject(), and parse_number().
prebuffer
int prebuffer
Definition at line 185 of file cJSON.h.
recurse
cJSON_bool recurse
Definition at line 290 of file cJSON.h.
Referenced by cJSON_Duplicate_rec().
string
const char * string
Definition at line 200 of file cJSON.h.
Referenced by add_item_to_object(), cast_away_const(), and replace_item_in_object().
valuestring
const char* valuestring
Definition at line 330 of file cJSON.h.
which
int which
Definition at line 269 of file cJSON.h.