Sensor Data Handler System: src/Libs/cJSON/cJSON.c File Reference
cJSON.c File Reference
#include <ctype.h>
#include <float.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cJSON.h"
Classes
struct error
struct internal_hooks
struct parse_buffer
struct printbuffer
Macros
#define buffer_at_offset(buffer) ((buffer)->content + (buffer)->offset)
#define can_access_at_index(buffer, index) ((buffer != NULL) && (((buffer)->offset + index) < (buffer)->length))
#define can_read(buffer, size) ((buffer != NULL) && (((buffer)->offset + size) <= (buffer)->length))
#define cannot_access_at_index(buffer, index) (!can_access_at_index(buffer, index))
#define cjson_min(a, b) (((a) < (b)) ? (a) : (b))
#define false ((cJSON_bool)0)
#define internal_free free
#define internal_malloc malloc
#define internal_realloc realloc
#define isinf(d) (isnan((d - d)) && !isnan(d))
#define isnan(d) (d != d)
#define NAN 0.0 / 0.0
#define static_strlen(string_literal) (sizeof(string_literal) - sizeof(""))
#define true ((cJSON_bool)1)
Typedefs
typedef struct internal_hooks internal_hooks
Functions
static cJSON_bool add_item_to_array (cJSON *array, cJSON *item)
static cJSON_bool add_item_to_object (cJSON *const object, const char *const string, cJSON *const item, const internal_hooks *const hooks, const cJSON_bool constant_key)
static parse_buffer * buffer_skip_whitespace (parse_buffer *const buffer)
static int case_insensitive_strcmp (const unsigned char *string1, const unsigned char *string2)
static void * cast_away_const (const void *string)
cJSON_AddBoolToObject (cJSON *const object, const char *const name, const cJSON_bool boolean)
cJSON_AddItemReferenceToObject (cJSON *object, const char *string, cJSON *item)
cJSON_AddNumberToObject (cJSON *const object, const char *const name, const double number)
cJSON_AddRawToObject (cJSON *const object, const char *const name, const char *const raw)
cJSON_AddStringToObject (cJSON *const object, const char *const name, const char *const string)
cJSON_Compare (const cJSON *const a, const cJSON *const b, const cJSON_bool case_sensitive)
cJSON * cJSON_Duplicate_rec (const cJSON *item, size_t depth, cJSON_bool recurse)
cJSON_GetObjectItemCaseSensitive (const cJSON *const object, const char *const string)
static cJSON * cJSON_New_Item (const internal_hooks *const hooks)
cJSON_ParseWithLengthOpts (const char *value, size_t buffer_length, const char **return_parse_end, cJSON_bool require_null_terminated)
cJSON_ParseWithOpts (const char *value, const char **return_parse_end, cJSON_bool require_null_terminated)
cJSON_PrintPreallocated (cJSON *item, char *buffer, const int length, const cJSON_bool format)
CJSON_PUBLIC (char *)
CJSON_PUBLIC (cJSON *)
CJSON_PUBLIC (const char *)
CJSON_PUBLIC (double)
CJSON_PUBLIC (int)
CJSON_PUBLIC (void *)
CJSON_PUBLIC (void)
cJSON_ReplaceItemInObject (cJSON *object, const char *string, cJSON *newitem)
cJSON_ReplaceItemInObjectCaseSensitive (cJSON *object, const char *string, cJSON *newitem)
cJSON_ReplaceItemViaPointer (cJSON *const parent, cJSON *const item, cJSON *replacement)
static unsigned char * cJSON_strdup (const unsigned char *string, const internal_hooks *const hooks)
static cJSON_bool compare_double (double a, double b)
static cJSON * create_reference (const cJSON *item, const internal_hooks *const hooks)
static unsigned char * ensure (printbuffer *const p, size_t needed)
static cJSON * get_array_item (const cJSON *array, size_t index)
static unsigned char get_decimal_point (void)
static cJSON * get_object_item (const cJSON *const object, const char *const name, const cJSON_bool case_sensitive)
static void minify_string (char **input, char **output)
static cJSON_bool parse_array (cJSON *const item, parse_buffer *const input_buffer)
static unsigned parse_hex4 (const unsigned char *const input)
static cJSON_bool parse_number (cJSON *const item, parse_buffer *const input_buffer)
static cJSON_bool parse_object (cJSON *const item, parse_buffer *const input_buffer)
static cJSON_bool parse_string (cJSON *const item, parse_buffer *const input_buffer)
static cJSON_bool parse_value (cJSON *const item, parse_buffer *const input_buffer)
static unsigned char * print (const cJSON *const item, cJSON_bool format, const internal_hooks *const hooks)
static cJSON_bool print_array (const cJSON *const item, printbuffer *const output_buffer)
static cJSON_bool print_number (const cJSON *const item, printbuffer *const output_buffer)
static cJSON_bool print_object (const cJSON *const item, printbuffer *const output_buffer)
static cJSON_bool print_string (const cJSON *const item, printbuffer *const p)
static cJSON_bool print_string_ptr (const unsigned char *const input, printbuffer *const output_buffer)
static cJSON_bool print_value (const cJSON *const item, printbuffer *const output_buffer)
static cJSON_bool replace_item_in_object (cJSON *object, const char *string, cJSON *replacement, cJSON_bool case_sensitive)
static void skip_multiline_comment (char **input)
static void skip_oneline_comment (char **input)
static parse_buffer * skip_utf8_bom (parse_buffer *const buffer)
static void suffix_object (cJSON *prev, cJSON *item)
static void update_offset (printbuffer *const buffer)
static unsigned char utf16_literal_to_utf8 (const unsigned char *const input_pointer, const unsigned char *const input_end, unsigned char **output_pointer)
Variables
static error global_error = { NULL, 0 }
static internal_hooks global_hooks = { internal_malloc, internal_free, internal_realloc }
Macro Definition Documentation
buffer_at_offset
#define buffer_at_offset (buffer) ((buffer)->content + (buffer)->offset)
Definition at line 297 of file cJSON.c.
can_access_at_index
#define can_access_at_index (buffer, index) ((buffer != NULL) && (((buffer)->offset + index) < (buffer)->length))
Definition at line 293 of file cJSON.c.
can_read
#define can_read (buffer, size) ((buffer != NULL) && (((buffer)->offset + size) <= (buffer)->length))
Definition at line 291 of file cJSON.c.
cannot_access_at_index
#define cannot_access_at_index (buffer, index) (!can_access_at_index(buffer, index))
Definition at line 295 of file cJSON.c.
cjson_min
#define cjson_min (a, b) (((a) < (b)) ? (a) : (b))
Definition at line 1105 of file cJSON.c.
false
#define false ((cJSON_bool)0)
Definition at line 70 of file cJSON.c.
internal_free
#define internal_free free
Definition at line 179 of file cJSON.c.
internal_malloc
#define internal_malloc malloc
Definition at line 178 of file cJSON.c.
internal_realloc
#define internal_realloc realloc
Definition at line 180 of file cJSON.c.
isinf
#define isinf (d) (isnan((d - d)) && !isnan(d))
Definition at line 75 of file cJSON.c.
isnan
#define isnan (d) (d != d)
Definition at line 78 of file cJSON.c.
NAN
#define NAN 0.0 / 0.0
Definition at line 85 of file cJSON.c.
static_strlen
#define static_strlen (string_literal) (sizeof(string_literal) - sizeof(""))
Definition at line 184 of file cJSON.c.
true
#define true ((cJSON_bool)1)
Definition at line 65 of file cJSON.c.
Typedef Documentation
internal_hooks
typedef struct internal_hooks internal_hooks
Function Documentation
add_item_to_array()
static cJSON_bool add_item_to_array (cJSON * array, cJSON * item) static
Definition at line 1820 of file cJSON.c.
References cJSON::child, item, cJSON::next, cJSON::prev, and suffix_object().
Referenced by add_item_to_object().
add_item_to_object()
static cJSON_bool add_item_to_object (cJSON *const object, const char *const string, cJSON *const item, const internal_hooks *const hooks, const cJSON_bool constant_key) static
Definition at line 1873 of file cJSON.c.
References add_item_to_array(), cast_away_const(), cJSON_Invalid, cJSON_strdup(), cJSON_StringIsConst, item, cJSON::string, string, and cJSON::type.
Referenced by cJSON_AddBoolToObject(), cJSON_AddItemReferenceToObject(), cJSON_AddNumberToObject(), cJSON_AddRawToObject(), and cJSON_AddStringToObject().
buffer_skip_whitespace()
static parse_buffer * buffer_skip_whitespace (parse_buffer *const buffer) static
Definition at line 966 of file cJSON.c.
References buffer_at_offset, can_access_at_index, cannot_access_at_index, parse_buffer::content, parse_buffer::length, and parse_buffer::offset.
Referenced by cJSON_ParseWithLengthOpts(), parse_array(), and parse_object().
case_insensitive_strcmp()
static int case_insensitive_strcmp (const unsigned char * string1, const unsigned char * string2) static
Definition at line 134 of file cJSON.c.
Referenced by get_object_item().
cast_away_const()
static void * cast_away_const (const void * string) static
Definition at line 1863 of file cJSON.c.
References string.
Referenced by add_item_to_object().
cJSON_AddBoolToObject()
cJSON_AddBoolToObject (cJSON *const object, const char *const name, const cJSON_bool boolean)
Definition at line 1970 of file cJSON.c.
References add_item_to_object(), global_hooks, and name.
cJSON_AddItemReferenceToObject()
cJSON_AddItemReferenceToObject (cJSON * object, const char * string, cJSON * item)
Definition at line 1926 of file cJSON.c.
References add_item_to_object(), create_reference(), global_hooks, and item.
cJSON_AddNumberToObject()
cJSON_AddNumberToObject (cJSON *const object, const char *const name, const double number)
Definition at line 1982 of file cJSON.c.
References add_item_to_object(), global_hooks, name, and number.
cJSON_AddRawToObject()
cJSON_AddRawToObject (cJSON *const object, const char *const name, const char *const raw)
Definition at line 2006 of file cJSON.c.
References add_item_to_object(), global_hooks, and name.
cJSON_AddStringToObject()
cJSON_AddStringToObject (cJSON *const object, const char *const name, const char *const string)
Definition at line 1994 of file cJSON.c.
References add_item_to_object(), global_hooks, and name.
cJSON_Compare()
cJSON_Compare (const cJSON *const a, const cJSON *const b, const cJSON_bool case_sensitive)
Definition at line 2769 of file cJSON.c.
References cJSON::child, cJSON_Array, cJSON_ArrayForEach, cJSON_Compare(), cJSON_False, cJSON_NULL, cJSON_Number, cJSON_Object, cJSON_Raw, cJSON_String, cJSON_True, compare_double(), get_object_item(), cJSON::next, and cJSON::string.
Referenced by cJSON_Compare().
cJSON_Duplicate_rec()
cJSON * cJSON_Duplicate_rec (const cJSON * item, size_t depth, cJSON_bool recurse)
Definition at line 2512 of file cJSON.c.
References cJSON::child, CJSON_CIRCULAR_LIMIT, cJSON_Duplicate_rec(), cJSON_New_Item(), cJSON_strdup(), cJSON_StringIsConst, global_hooks, item, newitem, cJSON::next, cJSON::prev, recurse, cJSON::string, cJSON::type, cJSON::valuedouble, cJSON::valueint, and cJSON::valuestring.
Referenced by cJSON_Duplicate_rec().
cJSON_GetObjectItemCaseSensitive()
cJSON_GetObjectItemCaseSensitive (const cJSON *const object, const char *const string)
Definition at line 1780 of file cJSON.c.
References get_object_item().
cJSON_New_Item()
static cJSON * cJSON_New_Item (const internal_hooks *const hooks) static
Definition at line 237 of file cJSON.c.
References internal_hooks::allocate().
Referenced by cJSON_Duplicate_rec(), cJSON_ParseWithLengthOpts(), create_reference(), parse_array(), and parse_object().
cJSON_ParseWithLengthOpts()
cJSON_ParseWithLengthOpts (const char * value, size_t buffer_length, const char ** return_parse_end, cJSON_bool require_null_terminated)
Definition at line 1022 of file cJSON.c.
References buffer_at_offset, buffer_length, buffer_skip_whitespace(), cJSON_New_Item(), parse_buffer::content, global_error, global_hooks, parse_buffer::hooks, item, error::json, parse_buffer::length, parse_buffer::offset, parse_value(), error::position, and skip_utf8_bom().
Referenced by cJSON_ParseWithOpts().
cJSON_ParseWithOpts()
cJSON_ParseWithOpts (const char * value, const char ** return_parse_end, cJSON_bool require_null_terminated)
Definition at line 1004 of file cJSON.c.
References buffer_length, and cJSON_ParseWithLengthOpts().
Referenced by CJSON_PUBLIC().
cJSON_PrintPreallocated()
cJSON_PrintPreallocated (cJSON * item, char * buffer, const int length, const cJSON_bool format)
Definition at line 1210 of file cJSON.c.
References printbuffer::buffer, printbuffer::format, global_hooks, printbuffer::hooks, item, printbuffer::length, printbuffer::noalloc, printbuffer::offset, and print_value().
CJSON_PUBLIC() [1/7]
CJSON_PUBLIC (char *)
Definition at line 101 of file cJSON.c.
References item, and cJSON::valuestring.
CJSON_PUBLIC() [2/7]
CJSON_PUBLIC (cJSON *)
Definition at line 1095 of file cJSON.c.
References cJSON_ParseWithOpts().
CJSON_PUBLIC() [3/7]
CJSON_PUBLIC (const char *)
Definition at line 96 of file cJSON.c.
References global_error, error::json, and error::position.
CJSON_PUBLIC() [4/7]
CJSON_PUBLIC (double)
Definition at line 110 of file cJSON.c.
References item, NAN, and cJSON::valuedouble.
CJSON_PUBLIC() [5/7]
CJSON_PUBLIC (int)
Definition at line 1695 of file cJSON.c.
References cJSON::child, and cJSON::next.
CJSON_PUBLIC() [6/7]
CJSON_PUBLIC (void *)
Definition at line 2881 of file cJSON.c.
References internal_hooks::allocate(), and global_hooks.
CJSON_PUBLIC() [7/7]
CJSON_PUBLIC (void)
Definition at line 208 of file cJSON.c.
References internal_hooks::allocate(), global_hooks, cJSON_Hooks::malloc_fn(), and internal_hooks::reallocate().
cJSON_ReplaceItemInObject()
cJSON_ReplaceItemInObject (cJSON * object, const char * string, cJSON * newitem)
Definition at line 2211 of file cJSON.c.
References newitem, and replace_item_in_object().
cJSON_ReplaceItemInObjectCaseSensitive()
cJSON_ReplaceItemInObjectCaseSensitive (cJSON * object, const char * string, cJSON * newitem)
Definition at line 2217 of file cJSON.c.
References newitem, and replace_item_in_object().
cJSON_ReplaceItemViaPointer()
cJSON_ReplaceItemViaPointer (cJSON *const parent, cJSON *const item, cJSON * replacement)
Definition at line 2138 of file cJSON.c.
References cJSON::child, item, cJSON::next, and cJSON::prev.
Referenced by replace_item_in_object().
cJSON_strdup()
static unsigned char * cJSON_strdup (const unsigned char * string, const internal_hooks *const hooks) static
Definition at line 189 of file cJSON.c.
References internal_hooks::allocate().
Referenced by add_item_to_object(), cJSON_Duplicate_rec(), and replace_item_in_object().
compare_double()
static cJSON_bool compare_double (double a, double b) static
Definition at line 522 of file cJSON.c.
Referenced by cJSON_Compare(), and print_number().
create_reference()
static cJSON * create_reference (const cJSON * item, const internal_hooks *const hooks) static
Definition at line 1800 of file cJSON.c.
References cJSON_IsReference, cJSON_New_Item(), item, cJSON::next, cJSON::prev, cJSON::string, and cJSON::type.
Referenced by cJSON_AddItemReferenceToObject().
ensure()
static unsigned char * ensure (printbuffer *const p, size_t needed) static
Definition at line 437 of file cJSON.c.
References internal_hooks::allocate(), printbuffer::buffer, printbuffer::hooks, printbuffer::length, printbuffer::noalloc, printbuffer::offset, and internal_hooks::reallocate().
Referenced by print_array(), print_number(), print_object(), print_string_ptr(), and print_value().
get_array_item()
static cJSON * get_array_item (const cJSON * array, size_t index) static
Definition at line 1717 of file cJSON.c.
References cJSON::child, index, and cJSON::next.
get_decimal_point()
static unsigned char get_decimal_point (void) static
Definition at line 271 of file cJSON.c.
Referenced by parse_number(), and print_number().
get_object_item()
static cJSON * get_object_item (const cJSON *const object, const char *const name, const cJSON_bool case_sensitive) static
Definition at line 1744 of file cJSON.c.
References case_insensitive_strcmp(), cJSON::child, name, cJSON::next, and cJSON::string.
Referenced by cJSON_Compare(), cJSON_GetObjectItemCaseSensitive(), and replace_item_in_object().
minify_string()
static void minify_string (char ** input, char ** output) static
Definition at line 2615 of file cJSON.c.
References static_strlen.
parse_array()
static cJSON_bool parse_array (cJSON *const item, parse_buffer *const input_buffer) static
Definition at line 1354 of file cJSON.c.
References buffer_at_offset, buffer_skip_whitespace(), can_access_at_index, cannot_access_at_index, cJSON::child, cJSON_Array, CJSON_NESTING_LIMIT, cJSON_New_Item(), parse_buffer::depth, parse_buffer::hooks, item, cJSON::next, parse_buffer::offset, parse_value(), cJSON::prev, and cJSON::type.
Referenced by parse_value().
parse_hex4()
static unsigned parse_hex4 (const unsigned char *const input) static
Definition at line 590 of file cJSON.c.
Referenced by utf16_literal_to_utf8().
parse_number()
static cJSON_bool parse_number (cJSON *const item, parse_buffer *const input_buffer) static
Definition at line 301 of file cJSON.c.
References buffer_at_offset, can_access_at_index, cJSON_Number, parse_buffer::content, get_decimal_point(), item, number, parse_buffer::offset, cJSON::type, cJSON::valuedouble, and cJSON::valueint.
Referenced by parse_value().
parse_object()
static cJSON_bool parse_object (cJSON *const item, parse_buffer *const input_buffer) static
Definition at line 1495 of file cJSON.c.
References buffer_at_offset, buffer_skip_whitespace(), can_access_at_index, cannot_access_at_index, cJSON::child, CJSON_NESTING_LIMIT, cJSON_New_Item(), cJSON_Object, parse_buffer::depth, parse_buffer::hooks, item, cJSON::next, parse_buffer::offset, parse_string(), parse_value(), cJSON::prev, cJSON::string, cJSON::type, and cJSON::valuestring.
Referenced by parse_value().
parse_string()
static cJSON_bool parse_string (cJSON *const item, parse_buffer *const input_buffer) static
Definition at line 721 of file cJSON.c.
References internal_hooks::allocate(), buffer_at_offset, cJSON_String, parse_buffer::content, parse_buffer::hooks, item, parse_buffer::length, parse_buffer::offset, cJSON::type, utf16_literal_to_utf8(), and cJSON::valuestring.
Referenced by parse_object(), and parse_value().
parse_value()
static cJSON_bool parse_value (cJSON *const item, parse_buffer *const input_buffer) static
Definition at line 1232 of file cJSON.c.
References buffer_at_offset, can_access_at_index, can_read, cJSON_False, cJSON_NULL, cJSON_True, parse_buffer::content, item, parse_buffer::offset, parse_array(), parse_number(), parse_object(), parse_string(), cJSON::type, and cJSON::valueint.
Referenced by cJSON_ParseWithLengthOpts(), parse_array(), and parse_object().
print()
static unsigned char * print (const cJSON *const item, cJSON_bool format, const internal_hooks *const hooks) static
Definition at line 1108 of file cJSON.c.
References internal_hooks::allocate(), printbuffer::buffer, cjson_min, printbuffer::format, printbuffer::hooks, item, printbuffer::length, printbuffer::offset, print_value(), internal_hooks::reallocate(), and update_offset().
Referenced by Timings::analyze_timing_data(), and Timings::main().
print_array()
static cJSON_bool print_array (const cJSON *const item, printbuffer *const output_buffer) static
Definition at line 1440 of file cJSON.c.
References cJSON::child, printbuffer::depth, ensure(), printbuffer::format, item, cJSON::next, printbuffer::offset, print_value(), and update_offset().
Referenced by print_value().
print_number()
static cJSON_bool print_number (const cJSON *const item, printbuffer *const output_buffer) static
Definition at line 530 of file cJSON.c.
References compare_double(), ensure(), get_decimal_point(), isinf, isnan, item, printbuffer::offset, cJSON::valuedouble, and cJSON::valueint.
Referenced by print_value().
print_object()
static cJSON_bool print_object (const cJSON *const item, printbuffer *const output_buffer) static
Definition at line 1598 of file cJSON.c.
References cJSON::child, printbuffer::depth, ensure(), printbuffer::format, item, cJSON::next, printbuffer::offset, print_string_ptr(), print_value(), cJSON::string, and update_offset().
Referenced by print_value().
print_string()
static cJSON_bool print_string (const cJSON *const item, printbuffer *const p) static
Definition at line 951 of file cJSON.c.
References item, print_string_ptr(), and cJSON::valuestring.
Referenced by print_value().
print_string_ptr()
static cJSON_bool print_string_ptr (const unsigned char *const input, printbuffer *const output_buffer) static
Definition at line 841 of file cJSON.c.
References ensure().
Referenced by print_object(), and print_string().
print_value()
static cJSON_bool print_value (const cJSON *const item, printbuffer *const output_buffer) static
Definition at line 1286 of file cJSON.c.
References cJSON_Array, cJSON_False, cJSON_NULL, cJSON_Number, cJSON_Object, cJSON_Raw, cJSON_String, cJSON_True, ensure(), item, print_array(), print_number(), print_object(), print_string(), cJSON::type, and cJSON::valuestring.
Referenced by cJSON_PrintPreallocated(), print(), print_array(), and print_object().
replace_item_in_object()
static cJSON_bool replace_item_in_object (cJSON * object, const char * string, cJSON * replacement, cJSON_bool case_sensitive) static
Definition at line 2188 of file cJSON.c.
References cJSON_ReplaceItemViaPointer(), cJSON_strdup(), cJSON_StringIsConst, get_object_item(), global_hooks, cJSON::string, string, and cJSON::type.
Referenced by cJSON_ReplaceItemInObject(), and cJSON_ReplaceItemInObjectCaseSensitive().
skip_multiline_comment()
static void skip_multiline_comment (char ** input) static
Definition at line 2602 of file cJSON.c.
References static_strlen.
skip_oneline_comment()
static void skip_oneline_comment (char ** input) static
Definition at line 2589 of file cJSON.c.
References static_strlen.
skip_utf8_bom()
static parse_buffer * skip_utf8_bom (parse_buffer *const buffer) static
Definition at line 989 of file cJSON.c.
References buffer_at_offset, can_access_at_index, parse_buffer::content, and parse_buffer::offset.
Referenced by cJSON_ParseWithLengthOpts().
suffix_object()
static void suffix_object (cJSON * prev, cJSON * item) static
Definition at line 1792 of file cJSON.c.
References item, cJSON::next, and cJSON::prev.
Referenced by add_item_to_array().
update_offset()
static void update_offset (printbuffer *const buffer) static
Definition at line 509 of file cJSON.c.
References printbuffer::buffer, and printbuffer::offset.
Referenced by print(), print_array(), and print_object().
utf16_literal_to_utf8()
static unsigned char utf16_literal_to_utf8 (const unsigned char *const input_pointer, const unsigned char *const input_end, unsigned char ** output_pointer) static
Definition at line 620 of file cJSON.c.
References parse_hex4().
Referenced by parse_string().
Variable Documentation
global_error
error global_error = { NULL, 0 } static
Definition at line 94 of file cJSON.c.
Referenced by cJSON_ParseWithLengthOpts(), and CJSON_PUBLIC().
global_hooks
internal_hooks global_hooks = { internal_malloc, internal_free, internal_realloc } static
Definition at line 186 of file cJSON.c.
Referenced by cJSON_AddBoolToObject(), cJSON_AddItemReferenceToObject(), cJSON_AddNumberToObject(), cJSON_AddRawToObject(), cJSON_AddStringToObject(), cJSON_Duplicate_rec(), cJSON_ParseWithLengthOpts(), cJSON_PrintPreallocated(), CJSON_PUBLIC(), CJSON_PUBLIC(), and replace_item_in_object().