Sensor Data Handler System: src/CommProtocols/Modbus.c File Reference
Modbus.c File Reference
Implementation of Modbus protocol handling.
#include <pthread.h>
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <src/Sdb.h>
#include <src/CommProtocols/Modbus.h>
#include <src/Common/SensorDataPipe.h>
#include <src/Common/Socket.h>
#include <src/Common/Thread.h>
Functions
const u8 * MbParseTcpFrame (const u8 *Frame, u16 *UnitId, u16 *DataLength)
Parses a Modbus TCP frame into its components.
modbus_ctx * MbPrepareCtx (sdb_arena *MbArena)
Prepares Modbus context from configuration file.
ssize_t MbReceiveTcpFrame (int Sockfd, u8 *Frame, size_t BufferSize)
Receives a complete Modbus TCP frame.
void MbThreadArenasInit (void)
Initializes thread arenas for Modbus operations.
SDB_LOG_REGISTER (Modbus)
SDB_THREAD_ARENAS_REGISTER (Modbus, 2)
Detailed Description
Implementation of Modbus protocol handling.
Resources: Modbus Application Protocol. Defines the Modbus spesifications. https://modbus.org/docs/Modbus_Application_Protocol_V1_1b.pdf
Definition in file Modbus.c.
Function Documentation
MbParseTcpFrame()
const u8 * MbParseTcpFrame (const u8 * Frame, u16 * UnitId, u16 * DataLength)
Parses a Modbus TCP frame into its components.
Parses a Modbus TCP frame.
Frame Structure:
| Field         | Size    | Description            |
|---------------|---------|------------------------|
| Transaction ID| 2 bytes | Request identifier     |
| Protocol ID   | 2 bytes | Protocol (0 = Modbus)  |
| Length        | 2 bytes | Number of following bytes|
| Unit ID       | 1 byte  | Slave identifier       |
| Function Code | 1 byte  | Action code           |
| DataLength    | 1 byte  | Length of data field  |
| Data          | n bytes | Payload data          |
The function checks for frame consistency by verifying that the Length field matches DataLength + 3 (accounting for UnitID, FunctionCode, and ByteCount).
Parameters
Frame Pointer to the raw Modbus TCP frame
UnitId Pointer to store the parsed Unit ID
DataLength Pointer to store the data length
Returns
Pointer to the start of data section, NULL if parsing fails or frame is invalid
See also
https://en.wikipedia.org/wiki/Modbus#Public_function_codes
https://modbus.org/docs/Modbus_Application_Protocol_V1_1b.pdf
Note
Bytes are arranged in big-endian order (most significant byte first)
Definition at line 109 of file Modbus.c.
References SdbLogWarning.
Referenced by MbRun().
MbPrepareCtx()
modbus_ctx * MbPrepareCtx (sdb_arena * MbArena)
Prepares Modbus context from configuration file.
Prepares Modbus context from configuration.
Reads IP address and port from configuration file and initializes connections. Creates and configures sockets for each connection.
Parameters
MbArena Memory arena for allocations
Returns
Initialized context or NULL on failure
Definition at line 137 of file Modbus.c.
References sdb_scratch_arena::Arena, modbus_ctx::ConnCount, modbus_ctx::Conns, sdb_file_data::Data, mb_conn::Ip, MODBUS_CONF_FS_PATH, mb_conn::Port, SdbLoadFileIntoMemory(), SdbLogDebug, SdbLogError, SdbPushArray, SdbPushStruct, SdbScratchGet, SdbScratchRelease, SdbStringMake(), SocketCreate(), and mb_conn::SockFd.
Referenced by MbRun().
MbReceiveTcpFrame()
ssize_t MbReceiveTcpFrame (int Sockfd, u8 * Frame, size_t BufferSize)
Receives a complete Modbus TCP frame.
Implements a two-stage reading process:
Reads the header to determine frame size
Reads the remaining data
Parameters
Sockfd Socket file descriptor
Frame Buffer to store received frame
BufferSize Size of provided buffer
Returns
Number of bytes read or negative on error
Definition at line 44 of file Modbus.c.
References MODBUS_TCP_HEADER_LEN, and SdbLogDebug.
MbThreadArenasInit()
void MbThreadArenasInit (void)
Initializes thread arenas for Modbus operations.
Definition at line 26 of file Modbus.c.
References SdbThreadArenasInit.
Referenced by MbPipeThroughputTest(), and MbRun().
SDB_LOG_REGISTER()
SDB_LOG_REGISTER (Modbus)
SDB_THREAD_ARENAS_REGISTER()
SDB_THREAD_ARENAS_REGISTER (Modbus , 2)