Sensor Data Handler System: src/CommProtocols/Modbus.h File Reference
Modbus.h File Reference
Modbus protocol implementation interface.
#include <src/Sdb.h>
#include <src/Common/SensorDataPipe.h>
#include <src/Common/Thread.h>
Classes
struct mb_conn
Represents a single Modbus TCP connection.
struct mb_init_args
Initialization arguments for Modbus connections.
struct modbus_ctx
Context structure for Modbus operations.
Macros
#define MB_SCRATCH_COUNT 2
Number of scratch arenas for Modbus operations.
#define MODBUS_CONF_FS_PATH "./configs/modbus-conf"
Path to Modbus configuration file.
#define MODBUS_PDU_MAX_SIZE (253)
Maximum size of Modbus Protocol Data Unit.
#define MODBUS_PORT (1312)
Default Modbus TCP port (testing port, standard is 502)
#define MODBUS_READ_HOLDING_REGISTERS (0x03)
Function code for reading holding registers.
#define MODBUS_TCP_FRAME_MAX_SIZE (260)
Maximum size of complete Modbus TCP frame.
#define MODBUS_TCP_HEADER_LEN (7)
Length of Modbus TCP header in bytes.
Functions
const u8 * MbParseTcpFrame (const u8 *Frame, u16 *UnitId, u16 *DataLength)
Parses a Modbus TCP frame.
modbus_ctx * MbPrepareCtx (sdb_arena *MbArena)
Prepares Modbus context from configuration.
void MbThreadArenasInit (void)
Initializes thread arenas for Modbus operations.
Detailed Description
Modbus protocol implementation interface.
Provides functionality for Modbus TCP communication including frame parsing, context management, and connection handling. This implementation follows the Modbus Application Protocol Specification V1.1b.
Definition in file Modbus.h.
Macro Definition Documentation
MB_SCRATCH_COUNT
#define MB_SCRATCH_COUNT 2
Number of scratch arenas for Modbus operations.
Definition at line 76 of file Modbus.h.
MODBUS_CONF_FS_PATH
#define MODBUS_CONF_FS_PATH "./configs/modbus-conf"
Path to Modbus configuration file.
Definition at line 38 of file Modbus.h.
MODBUS_PDU_MAX_SIZE
#define MODBUS_PDU_MAX_SIZE (253)
Maximum size of Modbus Protocol Data Unit.
Definition at line 29 of file Modbus.h.
MODBUS_PORT
#define MODBUS_PORT (1312)
Default Modbus TCP port (testing port, standard is 502)
Note
Using non-standard port as 502 is in reserved range
Definition at line 23 of file Modbus.h.
MODBUS_READ_HOLDING_REGISTERS
#define MODBUS_READ_HOLDING_REGISTERS (0x03)
Function code for reading holding registers.
Definition at line 35 of file Modbus.h.
MODBUS_TCP_FRAME_MAX_SIZE
#define MODBUS_TCP_FRAME_MAX_SIZE (260)
Maximum size of complete Modbus TCP frame.
Definition at line 32 of file Modbus.h.
MODBUS_TCP_HEADER_LEN
#define MODBUS_TCP_HEADER_LEN (7)
Length of Modbus TCP header in bytes.
Definition at line 26 of file Modbus.h.
Function Documentation
MbParseTcpFrame()
const u8 * MbParseTcpFrame (const u8 * Frame, u16 * UnitId, u16 * DataLength)
Parses a Modbus TCP frame.
Parameters
Frame Raw frame data
UnitId Pointer to store unit ID
DataLength Pointer to store data length
Returns
Pointer to start of data section, NULL if parsing fails
Parses a Modbus TCP frame.
Frame Structure:
| Field         | Size    | Description            |
|---------------|---------|------------------------|
| Transaction ID| 2 bytes | Request identifier     |
| Protocol ID   | 2 bytes | Protocol (0 = Modbus)  |
| Length        | 2 bytes | Number of following bytes|
| Unit ID       | 1 byte  | Slave identifier       |
| Function Code | 1 byte  | Action code           |
| DataLength    | 1 byte  | Length of data field  |
| Data          | n bytes | Payload data          |
The function checks for frame consistency by verifying that the Length field matches DataLength + 3 (accounting for UnitID, FunctionCode, and ByteCount).
Parameters
Frame Pointer to the raw Modbus TCP frame
UnitId Pointer to store the parsed Unit ID
DataLength Pointer to store the data length
Returns
Pointer to the start of data section, NULL if parsing fails or frame is invalid
See also
https://en.wikipedia.org/wiki/Modbus#Public_function_codes
https://modbus.org/docs/Modbus_Application_Protocol_V1_1b.pdf
Note
Bytes are arranged in big-endian order (most significant byte first)
Definition at line 109 of file Modbus.c.
References SdbLogWarning.
Referenced by MbRun().
MbPrepareCtx()
modbus_ctx * MbPrepareCtx (sdb_arena * MbArena)
Prepares Modbus context from configuration.
Parameters
MbArena Memory arena for allocations
Returns
Initialized modbus context, NULL on failure
Prepares Modbus context from configuration.
Reads IP address and port from configuration file and initializes connections. Creates and configures sockets for each connection.
Parameters
MbArena Memory arena for allocations
Returns
Initialized context or NULL on failure
Definition at line 137 of file Modbus.c.
References sdb_scratch_arena::Arena, modbus_ctx::ConnCount, modbus_ctx::Conns, sdb_file_data::Data, mb_conn::Ip, MODBUS_CONF_FS_PATH, mb_conn::Port, SdbLoadFileIntoMemory(), SdbLogDebug, SdbLogError, SdbPushArray, SdbPushStruct, SdbScratchGet, SdbScratchRelease, SdbStringMake(), SocketCreate(), and mb_conn::SockFd.
Referenced by MbRun().
MbThreadArenasInit()
void MbThreadArenasInit (void)
Initializes thread arenas for Modbus operations.
Definition at line 26 of file Modbus.c.
References SdbThreadArenasInit.
Referenced by MbPipeThroughputTest(), and MbRun().