Sensor Data Handler System: src/DataHandlers/ModbusWithPostgres/Postgres.h File Reference
Postgres.h File Reference
#include <src/Sdb.h>
Functions
sdb_errno PgRun (void *Arg)
Main PostgreSQL thread function.
Function Documentation
PgRun()
sdb_errno PgRun (void * Arg)
Main PostgreSQL thread function.
Manages the PostgreSQL database operations:
Initializes database connection
Processes sensor data from pipe
Handles data insertion with timing metrics
Manages graceful shutdown
Parameters
Arg Pointer to mbpg_ctx structure
Returns
sdb_errno 0 on success, error code on failure:
-ETIMEDOUT: Connection timeout
-EIO: I/O error
-errno: System error codes
Main PostgreSQL thread function.
Implementation details:
Initializes thread-local resources and arenas
Sets up database connection and event handling
Processes data in a loop until shutdown:
Waits for data using epoll
Reads data from pipe
Inserts data into database
Tracks performance metrics
Handles cleanup on shutdown
Performance monitoring:
Tracks insertion timing
Monitors total items processed
Records operation latency
Error handling:
Connection failures
Timeouts
I/O errors
Data insertion failures
Parameters
Arg Pointer to mbpg_ctx structure
Returns
sdb_errno Success/error status
Note
Currently supports single table operations
Warning
May timeout after 5 consecutive failures
Definition at line 55 of file Postgres.c.
References mbpg_ctx::Barrier, sdb_arena::Cur, postgres_ctx::DbConn, sensor_data_pipe::ItemMaxCount, sdb_arena::Mem, sensor_data_pipe::PacketSize, PG_SCRATCH_COUNT, PgInitThreadArenas(), PgInsertData(), mbpg_ctx::PgMemSize, PgPrepareCtx(), mbpg_ctx::PgScratchSize, sensor_data_pipe::ReadEventFd, SDB_TIME_MS, SdbArenaBootstrap(), SdbArenaInit(), SdbAssert, SdbBarrierWait(), SdbLogDebug, SdbLogError, SdbLogInfo, SdbLogWarning, SdbShouldShutdown(), SdbThreadArenasAdd, SdbThreadArenasInitExtern, SdbTimeMonotonic(), SdbTimePrintSpecDiffWT(), mbpg_ctx::SdPipe, SdPipeGetReadBuffer(), and postgres_ctx::TablesInfo.
Referenced by PgThread().