Sensor Data Handler System: src/DatabaseSystems/DatabaseInitializer.c File Reference
DatabaseInitializer.c File Reference
Implementation of database configuration initialization.
#include <libpq-fe.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <src/Sdb.h>
#include <src/Libs/cJSON/cJSON.h>
Functions
cJSON * DbInitGetConfFromFile (const char *Filename, sdb_arena *A)
Loads and parses a database configuration file.
SDB_LOG_REGISTER (DatabaseInitializer)
Detailed Description
Implementation of database configuration initialization.
Definition in file DatabaseInitializer.c.
Function Documentation
DbInitGetConfFromFile()
cJSON * DbInitGetConfFromFile (const char * Filename, sdb_arena * A)
Loads and parses a database configuration file.
Implementation details:
Creates a scratch arena if an arena is provided
Loads file content into memory
Parses JSON content
Cleans up temporary resources
Parameters
Filename Configuration file path
A Optional memory arena
Returns
cJSON structure containing parsed configuration
Definition at line 33 of file DatabaseInitializer.c.
References sdb_scratch_arena::Arena, sdb_file_data::Data, SdbLoadFileIntoMemory(), SdbLogError, SdbScratchBegin(), and SdbScratchRelease.
Referenced by PgPrepareCtx().
SDB_LOG_REGISTER()
SDB_LOG_REGISTER (DatabaseInitializer)