Sensor Data Handler System: src/DataHandlers/DataHandlers.h File Reference
DataHandlers.h File Reference
Data Handler Management for Thread Group Creation.
#include <src/Sdb.h>
#include <src/Common/ThreadGroup.h>
#include <src/Libs/cJSON/cJSON.h>
Functions
tg_group * DhsCreateTg (cJSON *Conf, u64 GroupId, sdb_arena *A)
Creates a thread group based on the configuration.
void DhsGetMemAndScratchSize (cJSON *Conf, u64 *MemSize, u64 *ScratchSize)
Extracts memory and scratch size from configuration.
Detailed Description
Data Handler Management for Thread Group Creation.
This header provides interfaces for creating and configuring data handler thread groups based on JSON configuration. It supports dynamic selection and initialization of different data handling mechanisms.
Definition in file DataHandlers.h.
Function Documentation
DhsCreateTg()
tg_group * DhsCreateTg (cJSON * Conf, u64 GroupId, sdb_arena * A)
Creates a thread group based on the configuration.
This function creates a thread group for a specific data handler based on the provided configuration. Currently supports Modbus with Postgres handler.
Parameters
Conf Pointer to the JSON configuration object
GroupId Unique identifier for the thread group
A Memory arena for allocation
Returns
tg_group* Pointer to the created thread group, or NULL if creation fails
Creates a thread group based on the configuration.
Determines the appropriate handler based on the configuration and creates a corresponding thread group. Currently supports Modbus with Postgres handler.
Parameters
Conf JSON configuration object
GroupId Unique identifier for the thread group
A Memory arena for allocation
Returns
tg_group* Pointer to the created thread group, or NULL if creation fails
Note
Logs information or error messages during thread group creation
Definition at line 101 of file DataHandlers.c.
References GetHandlerIdFromName(), Mb_With_Postgres, MbPgCreateTg(), SdbLogError, and SdbLogInfo.
Referenced by SetUpFromConf().
DhsGetMemAndScratchSize()
void DhsGetMemAndScratchSize (cJSON * Conf, u64 * MemSize, u64 * ScratchSize)
Extracts memory and scratch size from configuration.
Retrieves memory and scratch sizes from the JSON configuration. Asserts if the configuration is malformed or missing required fields.
Parameters
Conf Pointer to the JSON configuration object
MemSize Pointer to store the memory size
ScratchSize Pointer to store the scratch size
Extracts memory and scratch size from configuration.
Retrieves memory and scratch sizes from the provided JSON configuration. Performs validation and converts string representations to numeric sizes.
Parameters
Conf JSON configuration object
MemSize Pointer to store the extracted memory size
ScratchSize Pointer to store the extracted scratch size
Note
Asserts if configuration is invalid or missing required fields
Definition at line 71 of file DataHandlers.c.
References SdbAssert, and SdbMemSizeFromString().
Referenced by MbPgCreateTg().