Sensor Data Handler System: src/DatabaseSystems/Postgres.h File Reference
Postgres.h File Reference
PostgreSQL interface for sensor data storage.
#include <libpq-fe.h>
#include <src/Sdb.h>
#include <src/Common/SensorDataPipe.h>
#include <src/Common/Thread.h>
#include <src/Libs/cJSON/cJSON.h>
Classes
struct pg_col_metadata
PostgreSQL column metadata.
struct pg_table_info
Table information for PostgreSQL operations.
struct postgres_ctx
PostgreSQL context for database operations.
struct pq_col_all_metadata
Macros
#define PG_BOOL_NAME "boolean";
#define PG_DATE_NAME "date";
#define PG_FLOAT8_NAME "double precision";
#define PG_INT4_NAME "integer";
#define PG_INT8_NAME "bigint";
#define PG_NUMERIC_NAME "numeric";
#define PG_SCRATCH_COUNT 2
#define PG_TEXT_NAME "text";
#define PG_TIME_NAME "time without time zone";
#define PG_TIMESTAMPTZ_NAME "timestamp with time zone";
#define PG_VARCHAR_NAME "character varying";
#define POSTGRES_CONF_FS_PATH "./configs/postgres-conf"
Path to PostgreSQL configuration file.
#define PQ_ALL_TABLE_METADATA_QUERY_FMT
#define PQ_ALL_TABLE_METADATA_QUERY_FMT_LEN 609
#define PQ_TABLE_METADATA_QUERY_FMT
PostgreSQL Epoch Constants
#define NSECS_PER_USEC INT64_C(1000)
#define POSTGRES_EPOCH_JDATE 2451545
#define UNIX_EPOCH_JDATE 2440588
#define USECS_PER_DAY INT64_C(86400000000)
#define USECS_PER_MSEC INT64_C(1000)
#define USECS_PER_SECOND INT64_C(1000000)
Typedefs
typedef float pg_float4
typedef double pg_float8
typedef i16 pg_int2
typedef i32 pg_int4
typedef i64 pg_int8
typedef u32 pg_oid
typedef i64 pg_timestamp
Enumerations
enum {
PG_BOOL = 16 ,
PG_INT2 = 21 ,
PG_INT4 = 23 ,
PG_INT8 = 20 ,
PG_FLOAT4 = 700 ,
PG_FLOAT8 = 701 ,
PG_NUMERIC = 1700 ,
PG_CHAR = 18 ,
PG_NAME = 19 ,
PG_TEXT = 25 ,
PG_BPCHAR = 1042 ,
PG_VARCHAR = 1043 ,
PG_DATE = 1082 ,
PG_TIME = 1083 ,
PG_TIMETZ = 1266 ,
PG_TIMESTAMP = 1114 ,
PG_TIMESTAMPTZ = 1184 ,
PG_INTERVAL = 1186 ,
PG_BYTEA = 17 ,
PG_INET = 869 ,
PG_CIDR = 650 ,
PG_MACADDR = 829 ,
PG_MACADDR8 = 774 ,
PG_BIT = 1560 ,
PG_VARBIT = 1562 ,
PG_POINT = 600 ,
PG_LINE = 628 ,
PG_LSEG = 601 ,
PG_BOX = 603 ,
PG_PATH = 602 ,
PG_POLYGON = 604 ,
PG_CIRCLE = 718 ,
PG_JSON = 114 ,
PG_JSONB = 3802 ,
PG_BOOL_ARRAY = 1000 ,
PG_INT2_ARRAY = 1005 ,
PG_INT4_ARRAY = 1007 ,
PG_INT8_ARRAY = 1016 ,
PG_FLOAT4_ARRAY = 1021 ,
PG_FLOAT8_ARRAY = 1022 ,
PG_CHAR_ARRAY = 1002 ,
PG_TEXT_ARRAY = 1009 ,
PG_VARCHAR_ARRAY = 1015 ,
PG_BPCHAR_ARRAY = 1014 ,
PG_BYTEA_ARRAY = 1001 ,
PG_TIMESTAMP_ARRAY = 1115 ,
PG_TIMESTAMPTZ_ARRAY = 1185 ,
PG_DATE_ARRAY = 1182 ,
PG_TIME_ARRAY = 1183 ,
PG_TIMETZ_ARRAY = 1270 ,
PG_INTERVAL_ARRAY = 1187 ,
PG_NUMERIC_ARRAY = 1231 ,
PG_UUID = 2950 ,
PG_XML = 142 ,
PG_MONEY = 790 ,
PG_INT4RANGE = 3904 ,
PG_INT8RANGE = 3926 ,
PG_NUMRANGE = 3906 ,
PG_TSRANGE = 3908 ,
PG_TSTZRANGE = 3910 ,
PG_DATERANGE = 3912 ,
PG_OID = 26 ,
PG_REGPROC = 24 ,
PG_REGCLASS = 2205 ,
PG_REGTYPE = 2206 ,
PG_VOID = 2278 ,
PG_UNKNOWN = 705
}
PostgreSQL data types.
Functions
void DiagnoseConnectionAndTable (PGconn *DbConn, const char *TableName)
pg_col_metadata * GetTableMetadata (PGconn *DbConn, sdb_string TableName, i16 *ColCount, i16 *ColCountNoAutoIncrements, size_t *RowSize, sdb_arena *A)
void PgInitThreadArenas (void)
Initializes thread arenas for PostgreSQL operations.
sdb_errno PgInsertData (PGconn *Conn, pg_table_info *Ti, const char *Data, u64 ItemCount)
Inserts data into PostgreSQL table using COPY protocol.
postgres_ctx * PgPrepareCtx (sdb_arena *PgArena, sensor_data_pipe *Pipe)
Prepares PostgreSQL context from configuration.
void PrintPGresult (const PGresult *Result)
pg_timestamp TimespecToPgTimestamp (struct timespec Ts)
pg_timestamp TimevalToPgTimestamp (struct timeval Tv)
pg_timestamp UnixToPgTimestamp (time_t UnixTime)
Converts Unix timestamp to PostgreSQL timestamp.
Detailed Description
PostgreSQL interface for sensor data storage.
Provides functionality for storing sensor data in PostgreSQL databases, including data type mappings, timestamp conversions, and bulk data operations.
Definition in file Postgres.h.
Macro Definition Documentation
NSECS_PER_USEC
#define NSECS_PER_USEC INT64_C(1000)
Definition at line 32 of file Postgres.h.
PG_BOOL_NAME
#define PG_BOOL_NAME "boolean";
Definition at line 151 of file Postgres.h.
PG_DATE_NAME
#define PG_DATE_NAME "date";
Definition at line 157 of file Postgres.h.
PG_FLOAT8_NAME
#define PG_FLOAT8_NAME "double precision";
Definition at line 155 of file Postgres.h.
PG_INT4_NAME
#define PG_INT4_NAME "integer";
Definition at line 153 of file Postgres.h.
PG_INT8_NAME
#define PG_INT8_NAME "bigint";
Definition at line 152 of file Postgres.h.
PG_NUMERIC_NAME
#define PG_NUMERIC_NAME "numeric";
Definition at line 160 of file Postgres.h.
PG_SCRATCH_COUNT
#define PG_SCRATCH_COUNT 2
Definition at line 260 of file Postgres.h.
PG_TEXT_NAME
#define PG_TEXT_NAME "text";
Definition at line 154 of file Postgres.h.
PG_TIME_NAME
#define PG_TIME_NAME "time without time zone";
Definition at line 159 of file Postgres.h.
PG_TIMESTAMPTZ_NAME
#define PG_TIMESTAMPTZ_NAME "timestamp with time zone";
Definition at line 158 of file Postgres.h.
PG_VARCHAR_NAME
#define PG_VARCHAR_NAME "character varying";
Definition at line 156 of file Postgres.h.
POSTGRES_CONF_FS_PATH
#define POSTGRES_CONF_FS_PATH "./configs/postgres-conf"
Path to PostgreSQL configuration file.
Definition at line 21 of file Postgres.h.
POSTGRES_EPOCH_JDATE
#define POSTGRES_EPOCH_JDATE 2451545
Julian date for 2000-01-01 (PostgreSQL epoch)
Definition at line 27 of file Postgres.h.
PQ_ALL_TABLE_METADATA_QUERY_FMT
#define PQ_ALL_TABLE_METADATA_QUERY_FMT
Value:
    "SELECT c.oid AS table_oid, c.relname AS table_name, a.attnum AS column_number, a.attname AS " \
    "column_name, t.oid AS type_oid, t.typname AS type_name, t.typlen AS type_length, t.typbyval " \
    "AS type_by_value, t.typalign AS type_alignment, t.typstorage AS type_storage, a.atttypmod "   \
    "AS type_modifier, a.attnotnull AS not_null, pg_catalog.format_type(a.atttypid, a.atttypmod) " \
    "AS full_data_type FROM pg_catalog.pg_class c JOIN pg_catalog.pg_attribute a ON a.attrelid = " \
    "c.oid JOIN pg_catalog.pg_type t ON a.atttypid = t.oid WHERE c.relname = "                     \
    "'%s' AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum"
Definition at line 163 of file Postgres.h.
PQ_ALL_TABLE_METADATA_QUERY_FMT_LEN
#define PQ_ALL_TABLE_METADATA_QUERY_FMT_LEN 609
Definition at line 162 of file Postgres.h.
PQ_TABLE_METADATA_QUERY_FMT
#define PQ_TABLE_METADATA_QUERY_FMT
Value:
    "SELECT "                                                                                      \
    "a.attname AS column_name, "                                                                   \
    "t.oid AS type_oid, "                                                                          \
    "t.typlen AS type_length, "                                                                    \
    "a.atttypmod AS type_modifier, "                                                               \
    "EXISTS ( "                                                                                    \
    "SELECT 1 "                                                                                    \
    "FROM pg_constraint pc "                                                                       \
    "WHERE pc.conrelid = c.oid "                                                                   \
    "AND pc.contype = 'p' "                                                                        \
    "AND a.attnum = ANY(pc.conkey) "                                                               \
    ") AS is_primary_key, "                                                                        \
    "EXISTS ( "                                                                                    \
    "SELECT 1 "                                                                                    \
    "FROM pg_attrdef ad "                                                                          \
    "WHERE ad.adrelid = c.oid "                                                                    \
    "AND ad.adnum = a.attnum "                                                                     \
    "AND pg_get_expr(ad.adbin, ad.adrelid) LIKE 'nextval%%' "                                      \
    ") AS is_auto_increment "                                                                      \
    "FROM pg_catalog.pg_class c "                                                                  \
    "JOIN pg_catalog.pg_attribute a ON a.attrelid = c.oid "                                        \
    "JOIN pg_catalog.pg_type t ON a.atttypid = t.oid "                                             \
    "WHERE c.relname = '%s' "                                                                      \
    "AND a.attnum > 0 "                                                                            \
    "AND NOT a.attisdropped "                                                                      \
    "ORDER BY a.attnum"
Definition at line 189 of file Postgres.h.
UNIX_EPOCH_JDATE
#define UNIX_EPOCH_JDATE 2440588
Julian date for 1970-01-01 (Unix epoch)
Definition at line 28 of file Postgres.h.
USECS_PER_DAY
#define USECS_PER_DAY INT64_C(86400000000)
Definition at line 29 of file Postgres.h.
USECS_PER_MSEC
#define USECS_PER_MSEC INT64_C(1000)
Definition at line 31 of file Postgres.h.
USECS_PER_SECOND
#define USECS_PER_SECOND INT64_C(1000000)
Definition at line 30 of file Postgres.h.
Typedef Documentation
pg_float4
typedef float pg_float4
Definition at line 147 of file Postgres.h.
pg_float8
typedef double pg_float8
Definition at line 148 of file Postgres.h.
pg_int2
typedef i16 pg_int2
Definition at line 144 of file Postgres.h.
pg_int4
typedef i32 pg_int4
Definition at line 145 of file Postgres.h.
pg_int8
typedef i64 pg_int8
Definition at line 146 of file Postgres.h.
pg_oid
typedef u32 pg_oid
Definition at line 143 of file Postgres.h.
pg_timestamp
typedef i64 pg_timestamp
Definition at line 149 of file Postgres.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
PostgreSQL data types.
Enumerator
PG_BOOL
Boolean Boolean type Numbers
PG_INT2
smallint, int2
PG_INT4
integer, int4
PG_INT8
bigint, int8
PG_FLOAT4
real, float4
PG_FLOAT8
double precision, float8
PG_NUMERIC
numeric, decimal Character types
PG_CHAR
single char
PG_NAME
internal type for object names
PG_TEXT
variable-length text
PG_BPCHAR
blank-padded char(n)
PG_VARCHAR
variable-length character string Date/Time
PG_DATE
date
PG_TIME
time without timezone
PG_TIMETZ
time with timezone
PG_TIMESTAMP
timestamp without timezone
PG_TIMESTAMPTZ
timestamp with timezone
PG_INTERVAL
time interval Binary data
PG_BYTEA
variable-length binary string Network address types
PG_INET
IPv4 or IPv6 address
PG_CIDR
IPv4 or IPv6 network
PG_MACADDR
MAC address
PG_MACADDR8
MAC address (EUI-64 format) Bit strings
PG_BIT
fixed-length bit string
PG_VARBIT
variable-length bit string Geometric types
PG_POINT
geometric point (x,y)
PG_LINE
geometric line
PG_LSEG
geometric line segment
PG_BOX
geometric box
PG_PATH
geometric path
PG_POLYGON
geometric polygon
PG_CIRCLE
geometric circle JSON types
PG_JSON
text JSON
PG_JSONB
binary JSON Arrays
PG_BOOL_ARRAY
PG_INT2_ARRAY
PG_INT4_ARRAY
PG_INT8_ARRAY
PG_FLOAT4_ARRAY
PG_FLOAT8_ARRAY
PG_CHAR_ARRAY
PG_TEXT_ARRAY
PG_VARCHAR_ARRAY
PG_BPCHAR_ARRAY
PG_BYTEA_ARRAY
PG_TIMESTAMP_ARRAY
PG_TIMESTAMPTZ_ARRAY
PG_DATE_ARRAY
PG_TIME_ARRAY
PG_TIMETZ_ARRAY
PG_INTERVAL_ARRAY
PG_NUMERIC_ARRAY
UUID
PG_UUID
universally unique identifier XML
PG_XML
XML data Money
PG_MONEY
currency amount Range types
PG_INT4RANGE
PG_INT8RANGE
PG_NUMRANGE
PG_TSRANGE
PG_TSTZRANGE
PG_DATERANGE
Object identifier types
PG_OID
object identifier
PG_REGPROC
registered procedure
PG_REGCLASS
registered class
PG_REGTYPE
registered type Pseudo-types
PG_VOID
PG_UNKNOWN
Definition at line 39 of file Postgres.h.
Function Documentation
DiagnoseConnectionAndTable()
void DiagnoseConnectionAndTable (PGconn * DbConn, const char * TableName)
Definition at line 70 of file Postgres.c.
References SdbLogError, and SdbLogInfo.
GetTableMetadata()
pg_col_metadata * GetTableMetadata (PGconn * DbConn, sdb_string TableName, i16 * ColCount, i16 * ColCountNoAutoIncrements, size_t * RowSize, sdb_arena * A)
Definition at line 142 of file Postgres.c.
References sdb_scratch_arena::Arena, pg_col_metadata::ColumnName, pg_col_metadata::IsAutoIncrement, pg_col_metadata::IsPrimaryKey, pg_col_metadata::Offset, PQ_TABLE_METADATA_QUERY_FMT, SdbLogError, SdbPushArray, SdbScratchGet, SdbScratchRelease, SdbStringAppendFmt(), SdbStringMake(), pg_col_metadata::TypeLength, pg_col_metadata::TypeModifier, and pg_col_metadata::TypeOid.
Referenced by PgPrepareCtx().
PgInitThreadArenas()
void PgInitThreadArenas (void)
Initializes thread arenas for PostgreSQL operations.
Definition at line 36 of file Postgres.c.
References SdbThreadArenasInit.
Referenced by PgRun().
PgInsertData()
sdb_errno PgInsertData (PGconn * Conn, pg_table_info * Ti, const char * Data, u64 ItemCount)
Inserts data into PostgreSQL table using COPY protocol.
Implements bulk data insertion using PostgreSQL's binary COPY protocol:
Begins transaction
Initiates COPY operation
Converts data to network byte order
Sends data in binary format
Commits or rolls back transaction
Parameters
Conn Database connection
Ti Table information
Data Raw data to insert
ItemCount Number of items to insert
Returns
0 on success, error code on failure
Definition at line 421 of file Postgres.c.
References pg_table_info::ColCount, pg_table_info::ColCountNoAutoIncrements, pg_table_info::ColMetadata, pg_table_info::CopyCommand, pg_col_metadata::IsAutoIncrement, pg_col_metadata::Offset, PG_FLOAT4, PG_FLOAT8, PG_INT2, PG_INT4, PG_INT8, PG_TIMESTAMP, pg_table_info::RowSize, SDBE_PG_ERR, SdbLogDebug, SdbLogError, SdbLogWarning, SdbMemcpy(), SdbPushArrayZero, SdbScratchGet, SdbScratchRelease, pg_table_info::TableName, pg_col_metadata::TypeLength, pg_col_metadata::TypeOid, Write2(), Write4(), Write8(), and WriteTimestamp().
Referenced by PgRun().
PgPrepareCtx()
postgres_ctx * PgPrepareCtx (sdb_arena * PgArena, sensor_data_pipe * Pipe)
Prepares PostgreSQL context from configuration.
Parameters
PgArena Memory arena for allocations
Pipe Sensor data pipe
Returns
Initialized context or NULL on failure
Definition at line 204 of file Postgres.c.
References sdb_scratch_arena::Arena, sensor_data_pipe::BufferMaxFill, sensor_data_pipe::Buffers, sdb_arena::Cap, cJSON_ArrayForEach, pg_table_info::ColCount, pg_table_info::ColCountNoAutoIncrements, pg_table_info::ColMetadata, pg_col_metadata::ColumnName, pg_table_info::CopyCommand, sdb_file_data::Data, postgres_ctx::DbConn, DbInitGetConfFromFile(), GetTableMetadata(), pg_col_metadata::IsAutoIncrement, sensor_data_pipe::ItemMaxCount, sensor_data_pipe::PacketSize, POSTGRES_CONF_FS_PATH, pg_table_info::RowSize, SDBE_JSON_ERR, SDBE_PG_ERR, SdbLoadFileIntoMemory(), SdbLogError, SdbLogInfo, SdbPrintfDebug, SdbPushArray, SdbPushStruct, SdbScratchGet, SdbScratchRelease, SdbStringAppend(), SdbStringAppendC(), SdbStringBackspace(), SdbStringMake(), cJSON::string, pg_table_info::TableName, postgres_ctx::TablesInfo, and cJSON::valuestring.
Referenced by PgRun().
PrintPGresult()
void PrintPGresult (const PGresult * Result)
Definition at line 106 of file Postgres.c.
References SdbLogError, and SdbPrintfDebug.
TimespecToPgTimestamp()
pg_timestamp TimespecToPgTimestamp (struct timespec Ts)
Definition at line 63 of file Postgres.c.
References NSECS_PER_USEC, POSTGRES_EPOCH_JDATE, UNIX_EPOCH_JDATE, USECS_PER_DAY, and USECS_PER_SECOND.
TimevalToPgTimestamp()
pg_timestamp TimevalToPgTimestamp (struct timeval Tv)
Definition at line 56 of file Postgres.c.
References POSTGRES_EPOCH_JDATE, UNIX_EPOCH_JDATE, USECS_PER_DAY, and USECS_PER_SECOND.
UnixToPgTimestamp()
pg_timestamp UnixToPgTimestamp (time_t UnixTime) inline
Converts Unix timestamp to PostgreSQL timestamp.
Implementation detail: Converts by adjusting for epoch difference and scaling to microseconds
Definition at line 48 of file Postgres.c.
References POSTGRES_EPOCH_JDATE, UNIX_EPOCH_JDATE, USECS_PER_DAY, and USECS_PER_SECOND.
Referenced by WriteTimestamp().