Sensor Data Handler System: src/DataHandlers/DataHandlers.c File Reference
DataHandlers.c File Reference
Implementation of Data Handler Thread Group Management.
#include <src/Sdb.h>
#include <src/Common/ThreadGroup.h>
#include <src/Libs/cJSON/cJSON.h>
#include <src/DataHandlers/ModbusWithPostgres/ModbusWithPostgres.h>
Enumerations
enum handler_id { Mb_With_Postgres = 0 }
Functions
tg_group * DhsCreateTg (cJSON *Conf, u64 GroupId, sdb_arena *A)
Creates a thread group based on configuration.
void DhsGetMemAndScratchSize (cJSON *Conf, u64 *MemSize, u64 *ScratchSize)
Extracts memory and scratch sizes from JSON configuration.
static enum handler_id GetHandlerIdFromName (const char *Name)
Converts handler name to its corresponding ID.
SDB_LOG_REGISTER (DataHandlers)
Variables
static const char * AvailableHandlers [] = { "modbus_with_postgres" }
Array of available handler names.
Detailed Description
Implementation of Data Handler Thread Group Management.
Provides the core implementation for creating and managing thread groups based on configuration. Handles dynamic handler selection and initialization process.
Definition in file DataHandlers.c.
Enumeration Type Documentation
handler_id
enum handler_id
Enumerator
Mb_With_Postgres
Definition at line 20 of file DataHandlers.c.
Function Documentation
DhsCreateTg()
tg_group * DhsCreateTg (cJSON * Conf, u64 GroupId, sdb_arena * A)
Creates a thread group based on configuration.
Creates a thread group based on the configuration.
Determines the appropriate handler based on the configuration and creates a corresponding thread group. Currently supports Modbus with Postgres handler.
Parameters
Conf JSON configuration object
GroupId Unique identifier for the thread group
A Memory arena for allocation
Returns
tg_group* Pointer to the created thread group, or NULL if creation fails
Note
Logs information or error messages during thread group creation
Definition at line 101 of file DataHandlers.c.
References GetHandlerIdFromName(), Mb_With_Postgres, MbPgCreateTg(), SdbLogError, and SdbLogInfo.
Referenced by SetUpFromConf().
DhsGetMemAndScratchSize()
void DhsGetMemAndScratchSize (cJSON * Conf, u64 * MemSize, u64 * ScratchSize)
Extracts memory and scratch sizes from JSON configuration.
Extracts memory and scratch size from configuration.
Retrieves memory and scratch sizes from the provided JSON configuration. Performs validation and converts string representations to numeric sizes.
Parameters
Conf JSON configuration object
MemSize Pointer to store the extracted memory size
ScratchSize Pointer to store the extracted scratch size
Note
Asserts if configuration is invalid or missing required fields
Definition at line 71 of file DataHandlers.c.
References SdbAssert, and SdbMemSizeFromString().
Referenced by MbPgCreateTg().
GetHandlerIdFromName()
static enum handler_id GetHandlerIdFromName (const char * Name) static
Converts handler name to its corresponding ID.
Searches through AvailableHandlers to find the matching handler ID for a given name.
Parameters
Name Name of the handler to look up
Returns
enum handler_id Numeric ID of the handler, or -1 if not found
Definition at line 44 of file DataHandlers.c.
References AvailableHandlers, and SdbArrayLen.
Referenced by DhsCreateTg().
SDB_LOG_REGISTER()
SDB_LOG_REGISTER (DataHandlers)
Variable Documentation
AvailableHandlers
const char* AvailableHandlers[] = { "modbus_with_postgres" } static
Array of available handler names.
Contains string representations of supported data handlers. Must be kept in sync with handler_id enumeration.
Definition at line 31 of file DataHandlers.c.
Referenced by GetHandlerIdFromName().