Sensor Data Handler System: src/DataHandlers/ModbusWithPostgres/Modbus.h File Reference
Modbus.h File Reference
#include <src/Sdb.h>
Functions
sdb_errno MbPipeThroughputTest (void *Arg)
Runs a throughput test on the Modbus data pipe.
sdb_errno MbRun (void *Arg)
Main Modbus thread loop.
Function Documentation
MbPipeThroughputTest()
sdb_errno MbPipeThroughputTest (void * Arg)
Runs a throughput test on the Modbus data pipe.
Tests the throughput capacity of the Modbus data pipe by loading and processing test data. Waits at a barrier for synchronization with other threads before starting the test.
Parameters
Arg Pointer to mbpg_ctx structure
Returns
sdb_errno 0 on success, error code on failure
Runs a throughput test on the Modbus data pipe.
Loads test data and processes it through the data pipe while measuring throughput. Thread-safe implementation using atomic operations for buffer management.
Implementation details:
Initializes arenas
Waits at synchronization barrier
Loads test data from file
Pushes data to pipe buffers
Parameters
Arg Pointer to mbpg_ctx structure
Returns
sdb_errno Success/error status
Definition at line 36 of file Modbus.c.
References mbpg_ctx::Barrier, sensor_data_pipe::BufferMaxFill, sensor_data_pipe::Buffers, sdb_file_data::Data, MB_SCRATCH_COUNT, MbThreadArenasInit(), mbpg_ctx::ModbusMemSize, mbpg_ctx::ModbusScratchSize, SdbArenaBootstrap(), SdbArenaInit(), SdbArenaPush(), SdbBarrierWait(), SdbLoadFileIntoMemory(), SdbLogDebug, SdbLogInfo, SdbMemcpy(), SdbThreadArenasAdd, SdbThreadArenasInitExtern, mbpg_ctx::SdPipe, SdPipeFlush(), SdPipeGetWriteBuffer(), sdb_file_data::Size, and sensor_data_pipe::WriteBufIdx.
Referenced by MbPgPipeThroughputTest().
MbRun()
sdb_errno MbRun (void * Arg)
Main Modbus thread loop.
Implements the main Modbus thread functionality:
Initializes Modbus context and connections
Manages connection lifecycle
Handles data reception and parsing
Implements reconnection logic
pushes data to the sensor data pipe
Manages graceful shutdown
Parameters
Arg Pointer to mbpg_ctx structure
Returns
sdb_errno 0 on success, error code on failure
Main Modbus thread loop.
Manages the lifecycle of Modbus connections and data processing:
Handles connection establishment and recovery
Processes incoming Modbus frames
Manages graceful shutdown
Connection handling:
Automatically reconnects on failure
Implements backoff on repeated failures
Validates frame integrity
Data processing:
Parses Modbus TCP frames
Validates data length and format
Manages buffer rotation
Handles pipeline flushing
Parameters
Arg Pointer to mbpg_ctx structure
Returns
sdb_errno Success/error status
< Only wait at barrier first time
< Create new context and connection for each attempt
< First receive just the header
< Clean up current connection before retry
< Wait 1 second before retry
Definition at line 103 of file Modbus.c.
References mbpg_ctx::Barrier, sensor_data_pipe::BufferMaxFill, sensor_data_pipe::Buffers, modbus_ctx::ConnCount, modbus_ctx::Conns, MB_SCRATCH_COUNT, MbParseTcpFrame(), MbPrepareCtx(), MbThreadArenasInit(), MODBUS_TCP_FRAME_MAX_SIZE, MODBUS_TCP_HEADER_LEN, mbpg_ctx::ModbusMemSize, mbpg_ctx::ModbusScratchSize, sensor_data_pipe::PacketSize, SDB_TIME_MS, SdbArenaBootstrap(), SdbArenaGetPos(), SdbArenaInit(), SdbArenaPush(), SdbAssert, SdbBarrierWait(), SdbLogError, SdbLogInfo, SdbMemcpy(), SdbShouldShutdown(), SdbThreadArenasAdd, SdbThreadArenasInitExtern, mbpg_ctx::SdPipe, SdPipeFlush(), SdPipeGetWriteBuffer(), SocketRecvWithTimeout(), mb_conn::SockFd, and sensor_data_pipe::WriteBufIdx.
Referenced by MbThread().