Sensor Data Handler System: src/DatabaseSystems/DatabaseInitializer.h File Reference
DatabaseInitializer.h File Reference
Database configuration initialization interface.
#include <src/Sdb.h>
#include <src/Libs/cJSON/cJSON.h>
Functions
SDB_BEGIN_EXTERN_C cJSON * DbInitGetConfFromFile (const char *Filename, sdb_arena *A)
Loads and parses a database configuration file.
Detailed Description
Database configuration initialization interface.
Provides functionality for loading and parsing database configuration files in JSON format. Supports both arena-based and traditional memory management.
Definition in file DatabaseInitializer.h.
Function Documentation
DbInitGetConfFromFile()
SDB_BEGIN_EXTERN_C cJSON* DbInitGetConfFromFile (const char * Filename, sdb_arena * A)
Loads and parses a database configuration file.
Reads a JSON configuration file into memory and parses it into a cJSON structure. Supports both arena-based and traditional memory allocation depending on whether an arena is provided.
Parameters
Filename Path to the configuration file
A Memory arena for allocations (can be NULL for heap allocation)
Returns
Parsed cJSON structure, NULL on failure
Note
If arena is NULL, caller is responsible for freeing the returned cJSON structure
If arena is provided, memory will be managed through the arena
Implementation details:
Creates a scratch arena if an arena is provided
Loads file content into memory
Parses JSON content
Cleans up temporary resources
Parameters
Filename Configuration file path
A Optional memory arena
Returns
cJSON structure containing parsed configuration
Definition at line 33 of file DatabaseInitializer.c.
References sdb_scratch_arena::Arena, sdb_file_data::Data, SdbLoadFileIntoMemory(), SdbLogError, SdbScratchBegin(), and SdbScratchRelease.
Referenced by PgPrepareCtx().