Sensor Data Handler System: src/DatabaseSystems/Postgres.c File Reference
Postgres.c File Reference
Implementation of PostgreSQL database operations.
#include <arpa/inet.h>
#include <libpq-fe.h>
#include <stdlib.h>
#include <string.h>
#include <sys/epoll.h>
#include <sys/eventfd.h>
#include <src/Sdb.h>
#include <src/DatabaseSystems/Postgres.h>
#include <src/Common/SensorDataPipe.h>
#include <src/Common/Thread.h>
#include <src/DatabaseSystems/DatabaseInitializer.h>
#include <src/Libs/cJSON/cJSON.h>
#include <src/DevUtils/TestConstants.h>
Functions
void DiagnoseConnectionAndTable (PGconn *DbConn, const char *TableName)
pg_col_metadata * GetTableMetadata (PGconn *DbConn, sdb_string TableName, i16 *ColCount, i16 *ColCountNoAutoIncrements, size_t *RowSize, sdb_arena *A)
void PgInitThreadArenas (void)
Initializes thread arenas for PostgreSQL operations.
sdb_errno PgInsertData (PGconn *Conn, pg_table_info *Ti, const char *Data, u64 ItemCount)
Inserts data into PostgreSQL table using COPY protocol.
postgres_ctx * PgPrepareCtx (sdb_arena *PgArena, sensor_data_pipe *Pipe)
Prepares PostgreSQL context from configuration.
void PrintPGresult (const PGresult *Result)
SDB_LOG_REGISTER (Postgres)
SDB_THREAD_ARENAS_REGISTER (Postgres, 2)
pg_timestamp TimespecToPgTimestamp (struct timespec Ts)
pg_timestamp TimevalToPgTimestamp (struct timeval Tv)
pg_timestamp UnixToPgTimestamp (time_t UnixTime)
Converts Unix timestamp to PostgreSQL timestamp.
static size_t Write2 (char *To, const char *From)
Writes a 2-byte value in network byte order.
static size_t Write4 (char *To, const char *From)
static size_t Write8 (char *To, const char *From)
static size_t WriteTimestamp (char *To, const char *From)
Detailed Description
Implementation of PostgreSQL database operations.
Definition in file Postgres.c.
Function Documentation
DiagnoseConnectionAndTable()
void DiagnoseConnectionAndTable (PGconn * DbConn, const char * TableName)
Definition at line 70 of file Postgres.c.
References SdbLogError, and SdbLogInfo.
GetTableMetadata()
pg_col_metadata * GetTableMetadata (PGconn * DbConn, sdb_string TableName, i16 * ColCount, i16 * ColCountNoAutoIncrements, size_t * RowSize, sdb_arena * A)
Definition at line 142 of file Postgres.c.
References sdb_scratch_arena::Arena, pg_col_metadata::ColumnName, pg_col_metadata::IsAutoIncrement, pg_col_metadata::IsPrimaryKey, pg_col_metadata::Offset, PQ_TABLE_METADATA_QUERY_FMT, SdbLogError, SdbPushArray, SdbScratchGet, SdbScratchRelease, SdbStringAppendFmt(), SdbStringMake(), pg_col_metadata::TypeLength, pg_col_metadata::TypeModifier, and pg_col_metadata::TypeOid.
Referenced by PgPrepareCtx().
PgInitThreadArenas()
void PgInitThreadArenas (void)
Initializes thread arenas for PostgreSQL operations.
Definition at line 36 of file Postgres.c.
References SdbThreadArenasInit.
Referenced by PgRun().
PgInsertData()
sdb_errno PgInsertData (PGconn * Conn, pg_table_info * Ti, const char * Data, u64 ItemCount)
Inserts data into PostgreSQL table using COPY protocol.
Implements bulk data insertion using PostgreSQL's binary COPY protocol:
Begins transaction
Initiates COPY operation
Converts data to network byte order
Sends data in binary format
Commits or rolls back transaction
Parameters
Conn Database connection
Ti Table information
Data Raw data to insert
ItemCount Number of items to insert
Returns
0 on success, error code on failure
Definition at line 421 of file Postgres.c.
References pg_table_info::ColCount, pg_table_info::ColCountNoAutoIncrements, pg_table_info::ColMetadata, pg_table_info::CopyCommand, pg_col_metadata::IsAutoIncrement, pg_col_metadata::Offset, PG_FLOAT4, PG_FLOAT8, PG_INT2, PG_INT4, PG_INT8, PG_TIMESTAMP, pg_table_info::RowSize, SDBE_PG_ERR, SdbLogDebug, SdbLogError, SdbLogWarning, SdbMemcpy(), SdbPushArrayZero, SdbScratchGet, SdbScratchRelease, pg_table_info::TableName, pg_col_metadata::TypeLength, pg_col_metadata::TypeOid, Write2(), Write4(), Write8(), and WriteTimestamp().
Referenced by PgRun().
PgPrepareCtx()
postgres_ctx * PgPrepareCtx (sdb_arena * PgArena, sensor_data_pipe * Pipe)
Prepares PostgreSQL context from configuration.
Parameters
PgArena Memory arena for allocations
Pipe Sensor data pipe
Returns
Initialized context or NULL on failure
Definition at line 204 of file Postgres.c.
References sdb_scratch_arena::Arena, sensor_data_pipe::BufferMaxFill, sensor_data_pipe::Buffers, sdb_arena::Cap, cJSON_ArrayForEach, pg_table_info::ColCount, pg_table_info::ColCountNoAutoIncrements, pg_table_info::ColMetadata, pg_col_metadata::ColumnName, pg_table_info::CopyCommand, sdb_file_data::Data, postgres_ctx::DbConn, DbInitGetConfFromFile(), GetTableMetadata(), pg_col_metadata::IsAutoIncrement, sensor_data_pipe::ItemMaxCount, sensor_data_pipe::PacketSize, POSTGRES_CONF_FS_PATH, pg_table_info::RowSize, SDBE_JSON_ERR, SDBE_PG_ERR, SdbLoadFileIntoMemory(), SdbLogError, SdbLogInfo, SdbPrintfDebug, SdbPushArray, SdbPushStruct, SdbScratchGet, SdbScratchRelease, SdbStringAppend(), SdbStringAppendC(), SdbStringBackspace(), SdbStringMake(), cJSON::string, pg_table_info::TableName, postgres_ctx::TablesInfo, and cJSON::valuestring.
Referenced by PgRun().
PrintPGresult()
void PrintPGresult (const PGresult * Result)
Definition at line 106 of file Postgres.c.
References SdbLogError, and SdbPrintfDebug.
SDB_LOG_REGISTER()
SDB_LOG_REGISTER (Postgres)
SDB_THREAD_ARENAS_REGISTER()
SDB_THREAD_ARENAS_REGISTER (Postgres , 2)
TimespecToPgTimestamp()
pg_timestamp TimespecToPgTimestamp (struct timespec Ts)
Definition at line 63 of file Postgres.c.
References NSECS_PER_USEC, POSTGRES_EPOCH_JDATE, UNIX_EPOCH_JDATE, USECS_PER_DAY, and USECS_PER_SECOND.
TimevalToPgTimestamp()
pg_timestamp TimevalToPgTimestamp (struct timeval Tv)
Definition at line 56 of file Postgres.c.
References POSTGRES_EPOCH_JDATE, UNIX_EPOCH_JDATE, USECS_PER_DAY, and USECS_PER_SECOND.
UnixToPgTimestamp()
pg_timestamp UnixToPgTimestamp (time_t UnixTime) inline
Converts Unix timestamp to PostgreSQL timestamp.
Implementation detail: Converts by adjusting for epoch difference and scaling to microseconds
Definition at line 48 of file Postgres.c.
References POSTGRES_EPOCH_JDATE, UNIX_EPOCH_JDATE, USECS_PER_DAY, and USECS_PER_SECOND.
Referenced by WriteTimestamp().
Write2()
static size_t Write2 (char * To, const char * From) inline static
Writes a 2-byte value in network byte order.
Parameters
To Destination buffer
From Source buffer
Returns
Number of bytes written
Definition at line 363 of file Postgres.c.
References SdbMemcpy().
Referenced by PgInsertData().
Write4()
static size_t Write4 (char * To, const char * From) inline static
Definition at line 373 of file Postgres.c.
References SdbMemcpy().
Referenced by PgInsertData().
Write8()
static size_t Write8 (char * To, const char * From) inline static
Definition at line 383 of file Postgres.c.
References SdbMemcpy().
Referenced by PgInsertData().
WriteTimestamp()
static size_t WriteTimestamp (char * To, const char * From) inline static
Definition at line 393 of file Postgres.c.
References SdbMemcpy(), and UnixToPgTimestamp().
Referenced by PgInsertData().