version: "3.8"

services:
  db:
    image: postgres:14 # Explicitly using PostgreSQL 14 to match your existing database
    environment:
      POSTGRES_PASSWORD: passord
      POSTGRES_DB: fordypningsprosjekt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs
      - ./build:/app/build

volumes:
  postgres_data:
