Sensor Data Handler System: src/Main.c File Reference
Main.c File Reference
Main implementation file for the Sensor Data Handler System.
#include <signal.h>
#include <stdlib.h>
#include <string.h>
#include <src/Sdb.h>
#include <src/Common/Thread.h>
#include <src/Common/ThreadGroup.h>
#include <src/DataHandlers/DataHandlers.h>
#include <src/Libs/cJSON/cJSON.h>
#include <src/Signals.h>
Macros
#define SDB_H_IMPLEMENTATION
Functions
int main (int ArgCount, char **ArgV)
Main entry point for the Sensor Data Handler System.
SDB_LOG_REGISTER (Main)
sdb_errno SetUpFromConf (sdb_string ConfFilename, tg_manager **Manager)
Sets up the thread group manager from a configuration file.
Detailed Description
Main implementation file for the Sensor Data Handler System.
Author
Magnus Gjerstad, Ingar Asheim, Ole Fredrik Høivang Heggum
Date
2024
This file implements the main entry point and configuration setup for the Kongsberg Maritime's sensor data handling system. The system is designed to collect and store sensor data with flexible and modular configuration capabilities.
This system can be configured to handle multiple data handlers, each with their own thread group. The system is designed to be easily extensible and configurable through JSON configuration files.
Changes to the code can be made to extend the system's capabilities, such as adding protocols. This system has buildt up a framework for adding new configurations later.
Definition in file Main.c.
Macro Definition Documentation
SDB_H_IMPLEMENTATION
#define SDB_H_IMPLEMENTATION
Definition at line 23 of file Main.c.
Function Documentation
main()
int main (int ArgCount, char ** ArgV)
Main entry point for the Sensor Data Handler System.
This function initializes and runs the sensor data handling system. It performs the following main tasks:
Sets up the system configuration from a JSON file
Initializes signal handlers
Starts all thread groups
Waits for completion and performs cleanup
Parameters
ArgCount Number of command line arguments
ArgV Array of command line argument strings
Returns
EXIT_SUCCESS on successful execution, EXIT_FAILURE if initialization fails
Definition at line 148 of file Main.c.
References SdbLogError, SdbLogInfo, SdbSetupSignalHandlers(), SetUpFromConf(), TgDestroyManager(), TgManagerStartAll(), and TgManagerWaitForAll().
SDB_LOG_REGISTER()
SDB_LOG_REGISTER (Main)
SetUpFromConf()
sdb_errno SetUpFromConf (sdb_string ConfFilename, tg_manager ** Manager)
Sets up the thread group manager from a configuration file.
This function reads and parses a JSON configuration file to set up data handlers and their corresponding thread groups. It creates a thread group manager that oversees all configured data handlers.
Parameters
[in] ConfFilename Path to the JSON configuration file
[out] Manager Pointer to the thread group manager pointer that will be initialized
Returns
sdb_errno Returns 0 on success, or one of the following error codes:
-ENOMEM: Memory allocation failed
-SDBE_JSON_ERR: JSON parsing error
-EINVAL: No data handlers found in configuration
-1: General failure in thread group creation or manager initialization
Note
The caller is responsible for destroying the manager using TgDestroyManager() when it's no longer needed
Definition at line 57 of file Main.c.
References cJSON_ArrayForEach, sdb_file_data::Data, DhsCreateTg(), SDBE_JSON_ERR, SdbLoadFileIntoMemory(), SdbLogError, TgCreateManager(), and TgDestroyManager().
Referenced by main().