Sensor Data Handler System: src/DevUtils/ModbusTestServer.c File Reference
ModbusTestServer.c File Reference
Implementation of Modbus Test Server.
#include <arpa/inet.h>
#include <string.h>
#include <sys/socket.h>
#include <time.h>
#include <unistd.h>
#include <src/Sdb.h>
#include <netinet/tcp.h>
#include <src/CommProtocols/Modbus.h>
#include <src/Common/Socket.h>
#include <src/Common/Thread.h>
#include <src/Common/Time.h>
#include <src/DatabaseSystems/Postgres.h>
#include <src/DevUtils/TestConstants.h>
#include <src/Signals.h>
Macros
#define BACKLOG 5
#define PACKET_FREQ 1e5
Functions
static void GenerateModbusTcpFrame (u8 *Buffer, u16 TransactionId, u16 ProtocolId, u16 Length, u8 UnitId, u16 FunctionCode, u8 *Data, u16 DataLength)
Constructs a Modbus TCP frame.
static void GenerateShaftPowerData (shaft_power_data *Data)
Generates deterministic shaft power data.
static void GenerateShaftPowerDataRandom (shaft_power_data *Data)
Generates random shaft power data.
void RunModbusTestServer (sdb_barrier *Barrier)
Main Modbus Test Server routine.
SDB_LOG_REGISTER (ModbusTestServer)
static sdb_errno SendModbusData (int NewFd)
Sends Modbus data over a socket.
Detailed Description
Implementation of Modbus Test Server.
Provides an implementation of a Modbus TCP test server that generates and transmits simulated shaft power data.
Main Responsibilities:
Create and manage TCP server socket
Generate random shaft power measurement data
Handle client connections
Implement controlled data transmission
Key Components:
Non-blocking socket operations
Random data generation
Rate-limited data transmission
Definition in file ModbusTestServer.c.
Macro Definition Documentation
BACKLOG
#define BACKLOG 5
Definition at line 42 of file ModbusTestServer.c.
PACKET_FREQ
#define PACKET_FREQ 1e5
Definition at line 43 of file ModbusTestServer.c.
Function Documentation
GenerateModbusTcpFrame()
static void GenerateModbusTcpFrame (u8 * Buffer, u16 TransactionId, u16 ProtocolId, u16 Length, u8 UnitId, u16 FunctionCode, u8 * Data, u16 DataLength) static
Constructs a Modbus TCP frame.
Builds a complete Modbus TCP frame with specified parameters, including transaction ID, protocol ID, length, unit ID, function code, and payload data.
Parameters
Buffer Output buffer to store the constructed frame
TransactionId Modbus transaction identifier
ProtocolId Modbus protocol identifier
Length Total length of the frame payload
UnitId Modbus unit identifier
FunctionCode Modbus function code
Data Payload data to be included in the frame
DataLength Length of the payload data
Definition at line 118 of file ModbusTestServer.c.
References SdbMemcpy().
GenerateShaftPowerData()
static void GenerateShaftPowerData (shaft_power_data * Data) inline static
Generates deterministic shaft power data.
Creates a shaft power data structure with incrementing values. Useful for consistent, predictable data generation.
Parameters
Data Pointer to shaft_power_data structure to be filled
Definition at line 55 of file ModbusTestServer.c.
GenerateShaftPowerDataRandom()
static void GenerateShaftPowerDataRandom (shaft_power_data * Data) static
Generates random shaft power data.
Creates a shaft power data structure with randomized values. Simulates realistic variations in power measurements.
Generates:
Randomized RPM with sinusoidal variation
Randomized Torque
Calculated Power
Randomized Peak-to-Peak PFS
Parameters
Data Pointer to shaft_power_data structure to be filled
Definition at line 87 of file ModbusTestServer.c.
Referenced by SendModbusData().
RunModbusTestServer()
void RunModbusTestServer (sdb_barrier * Barrier)
Main Modbus Test Server routine.
Runs the Modbus Test Server.
Implements the complete Modbus test server workflow:
Create and configure server socket
Handle incoming client connections
Send simulated shaft power data
Support non-blocking operations
Graceful shutdown handling
Parameters
Barrier Synchronization barrier to coordinate server startup
Definition at line 215 of file ModbusTestServer.c.
References BACKLOG, MODBUS_PORT, SdbBarrierWait(), SdbLogError, SdbLogInfo, SdbMemset(), SdbShouldShutdown(), and SendModbusData().
Referenced by MbPgTestServer().
SDB_LOG_REGISTER()
SDB_LOG_REGISTER (ModbusTestServer)
SendModbusData()
static sdb_errno SendModbusData (int NewFd) inline static
Sends Modbus data over a socket.
Generates a random shaft power data packet, constructs a Modbus TCP frame, and sends it over the provided socket.
Features:
Random data generation
Modbus TCP frame construction
Periodic logging of sent packets
Parameters
NewFd Socket file descriptor to send data
Returns
sdb_errno Status of send operation
Definition at line 149 of file ModbusTestServer.c.
References GenerateShaftPowerDataRandom(), MODBUS_TCP_FRAME_MAX_SIZE, MODBUS_TCP_HEADER_LEN, SdbLogDebug, SdbLogError, SdbLogInfo, SdbMemcpy(), and shaft_power_data.
Referenced by RunModbusTestServer().