Sensor Data Handler System: src/DataHandlers/ModbusWithPostgres/ModbusWithPostgres.h File Reference
ModbusWithPostgres.h File Reference
Integration of Modbus and PostgreSQL data handling.
#include <src/Sdb.h>
#include <src/Common/SensorDataPipe.h>
#include <src/Common/ThreadGroup.h>
#include <src/Libs/cJSON/cJSON.h>
Classes
struct mbpg_ctx
Context for Modbus-PostgreSQL integration.
Functions
sdb_errno MbPgCleanup (void *Arg)
Cleanup function for Modbus-PostgreSQL context.
tg_group * MbPgCreateTg (cJSON *Conf, u64 GroupId, sdb_arena *A)
Creates thread group for Modbus-PostgreSQL integration.
void * MbPgPipeThroughputTest (void *Arg)
Data pipe throughput test thread.
void * MbPgTestServer (void *Arg)
Modbus test server thread.
void * MbThread (void *Arg)
Modbus thread function.
void * PgThread (void *Arg)
PostgreSQL thread function.
Detailed Description
Integration of Modbus and PostgreSQL data handling.
Provides functionality for coordinating Modbus data collection with PostgreSQL storage, including thread management and data pipe handling.
Definition in file ModbusWithPostgres.h.
Function Documentation
MbPgCleanup()
sdb_errno MbPgCleanup (void * Arg)
Cleanup function for Modbus-PostgreSQL context.
Parameters
Arg Pointer to mbpg_ctx structure
Returns
sdb_errno 0 on success, error code on failure
Definition at line 149 of file ModbusWithPostgres.c.
References mbpg_ctx::Barrier, SdbBarrierDeinit(), SDBE_PTR_WAS_NULL, SdbLogWarning, SdpDestroy(), and mbpg_ctx::SdPipe.
Referenced by MbPgCreateTg().
MbPgCreateTg()
tg_group * MbPgCreateTg (cJSON * Conf, u64 GroupId, sdb_arena * A)
Creates thread group for Modbus-PostgreSQL integration.
Parameters
Conf JSON configuration
GroupId Thread group identifier
A Memory arena for allocations
Returns
Initialized thread group or NULL on failure
Creates thread group for Modbus-PostgreSQL integration.
Creates and initializes a thread group based on JSON configuration:
Parses Modbus and PostgreSQL configurations
Allocates and initializes context
Sets up data pipe
Configures thread tasks based on mode (test/normal)
Parameters
Conf JSON configuration
GroupId Thread group identifier
A Memory arena for allocations
Returns
Initialized thread group or NULL on failure
Definition at line 196 of file ModbusWithPostgres.c.
References mbpg_ctx::Barrier, DhsGetMemAndScratchSize(), GSignalContext, MbPgCleanup(), MbPgTestTasks, MbPgThroughputTestTasks, mbpg_ctx::ModbusMemSize, mbpg_ctx::ModbusScratchSize, mbpg_ctx::PgMemSize, mbpg_ctx::PgScratchSize, signal_handler_context::Pipe, SdbBarrierInit(), SdbLogError, SdbMemSizeFromString(), SdpCreate(), mbpg_ctx::SdPipe, and TgCreateGroup().
Referenced by DhsCreateTg().
MbPgPipeThroughputTest()
void * MbPgPipeThroughputTest (void * Arg)
Data pipe throughput test thread.
Parameters
Arg Pointer to mbpg_ctx structure
Returns
Thread return value (always NULL)
Data pipe throughput test thread.
Tests the throughput capacity of the Modbus data pipe by loading and processing test data. Waits at a barrier for synchronization with other threads before starting the test.
Parameters
Arg Pointer to mbpg_ctx structure
Returns
sdb_errno 0 on success, error code on failure
Definition at line 107 of file ModbusWithPostgres.c.
References MbPipeThroughputTest(), SdbLogError, SdbLogInfo, SdbShouldShutdown(), and SdbStrErr().
MbPgTestServer()
void * MbPgTestServer (void * Arg)
Modbus test server thread.
Parameters
Arg Pointer to mbpg_ctx structure
Returns
Thread return value (always NULL)
Sets thread name and runs the Modbus test server. Handles errors and performs graceful shutdown.
Parameters
Arg Pointer to mbpg_ctx context.
Returns
NULL
Definition at line 84 of file ModbusWithPostgres.c.
References mbpg_ctx::Barrier, RunModbusTestServer(), and SdbLogInfo.
MbThread()
void * MbThread (void * Arg)
Modbus thread function.
Parameters
Arg Pointer to mbpg_ctx structure
Returns
Thread return value (always NULL)
Modbus thread function.
Sets thread name and runs Modbus operations. Handles errors and performs graceful shutdown.
Parameters
Arg Pointer to mbpg_ctx structure
Returns
NULL
Definition at line 60 of file ModbusWithPostgres.c.
References MbRun(), SdbLogError, SdbLogInfo, and SdbStrErr().
PgThread()
void * PgThread (void * Arg)
PostgreSQL thread function.
Parameters
Arg Pointer to mbpg_ctx structure
Returns
Thread return value (always NULL)
PostgreSQL thread function.
Sets thread name and runs PostgreSQL operations. Handles errors and performs graceful shutdown.
Parameters
Arg Pointer to mbpg_ctx structure
Returns
NULL
Definition at line 35 of file ModbusWithPostgres.c.
References PgRun(), SdbLogError, SdbLogInfo, and SdbStrErr().