Sensor Data Handler System: src/Sdb.h File Reference
Sdb.h File Reference
#include <assert.h>
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <float.h>
#include <math.h>
#include <pthread.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
#include <stdbool.h>
Classes
struct sdb__log_module__
struct sdb__thread_arenas__
struct sdb_arena
struct sdb_file_data
struct sdb_mmap
struct sdb_scratch_arena
struct sdb_slice
struct sdb_string_header
struct sdb_token
Macros
#define SDB__CONCAT2__(x, y) x##y
#define SDB__CONCAT3__(x, y, z) x##y##z
#define SDB__LOG__(log_level, fmt, ...)
#define SDB__LOG_LEVEL_CHECK__(level) (SDB_LOG_LEVEL >= SDB_LOG_LEVEL_##level)
#define SDB__STRINGIFY__(x) #x
#define SDB_BEGIN_EXTERN_C
#define SDB_CONCAT2(x, y) SDB__CONCAT2__(x, y)
#define SDB_CONCAT3(x, y, z) SDB__CONCAT3__(x, y, z)
#define SDB_END_EXTERN_C
#define SDB_EXPAND(x) x
#define sdb_global static
#define sdb_internal static
#define SDB_LOG_BUF_SIZE 2048
#define SDB_LOG_DECLARE(name)
#define SDB_LOG_LEVEL 3
#define SDB_LOG_LEVEL_DBG (4U)
#define SDB_LOG_LEVEL_ERR (1U)
#define SDB_LOG_LEVEL_INF (3U)
#define SDB_LOG_LEVEL_NONE (0U)
#define SDB_LOG_LEVEL_WRN (2U)
#define SDB_LOG_REGISTER(module_name)
#define SDB_LOGGING_NOT_USED static sdb__log_module__ *Sdb__LogInstance__ __attribute__((used)) = NULL
#define sdb_persist static
#define SDB_POOL_ALLOCATOR_DEFINE(type_name, func_name)
#define SDB_STRING_HEADER(str) ((sdb_string_header *)(str) - 1)
#define SDB_STRINGIFY(x) SDB__STRINGIFY__(x)
#define SDB_THREAD_ARENAS_EXTERN(thread_name)
#define SDB_THREAD_ARENAS_REGISTER(thread_name, count)
#define SdbArrayDeleteAndShift(mem, i, count, esize) SdbArrayShift(mem, (i + 1), i, count, esize)
#define SdbArrayLen(Array) (sizeof(Array) / sizeof(Array[0]))
#define SdbAssert(...)
#define SdbGibiByte(Number) (SdbMebiByte(Number) * 1024ULL)
#define SdbGigaByte(Number) (SdbMegaByte(Number) * 1000ULL)
#define SdbKibiByte(Number) (Number * 1024ULL)
#define SdbKiloByte(Number) (Number * 1000ULL)
#define SdbLogDebug(...) SDB__LOG__(DBG, ##__VA_ARGS__)
#define SdbLogError(...) SDB__LOG__(ERR, ##__VA_ARGS__)
#define SdbLogInfo(...) SDB__LOG__(INF, ##__VA_ARGS__)
#define SdbLogWarning(...) SDB__LOG__(WRN, ##__VA_ARGS__)
#define SdbMax(a, b) ((a > b) ? a : b)
#define SdbMebiByte(Number) (SdbKibiByte(Number) * 1024ULL)
#define SdbMegaByte(Number) (SdbKiloByte(Number) * 1000ULL)
#define SdbMemMap(map, maddr, msize, mprot, mflags, mfd, moffset, filename, oflags, omode)
#define SdbMemZeroStruct(struct) SdbMemZero(struct, sizeof(*struct))
#define SdbMemZeroStructSecure(struct) SdbMemZeroSecure(struct, sizeof(*struct))
#define SdbMin(a, b) ((a < b) ? a : b)
#define SdbPrintfDebug(...)
#define SdbPushArray(arena, type, count) (type *)SdbArenaPush(arena, sizeof(type) * (count))
#define SdbPushArrayZero(arena, type, count) (type *)SdbArenaPushZero(arena, sizeof(type) * (count))
#define SdbPushStruct(arena, type) SdbPushArray(arena, type, 1)
#define SdbPushStructZero(arena, type) SdbPushArrayZero(arena, type, 1)
#define SdbScratchGet(conflicts, conflict_count) Sdb__ScratchGet__(conflicts, conflict_count, Sdb__ThreadArenasInstance__)
#define SdbScratchRelease(scratch) Sdb__ScratchRelease__(scratch)
#define SdbTebiByte(Number) (SdbGibiByte(Number) * 1024ULL)
#define SdbTeraByte(Number) (SdbGigaByte(Number) * 1000ULL)
#define SdbThreadArenasAdd(arena) Sdb__ThreadArenasAdd__(arena, Sdb__ThreadArenasInstance__)
#define SdbThreadArenasInit(thread_name)
#define SdbThreadArenasInitExtern(thread_name)
Typedefs
typedef int16_t i16
typedef int32_t i32
typedef int64_t i64
typedef int8_t i8
typedef struct sdb__log_module__ sdb__log_module__
typedef struct sdb_arena sdb_arena
typedef int_least32_t sdb_errno
typedef struct sdb_slice sdb_slice
typedef char * sdb_string
typedef uint16_t u16
typedef uint32_t u32
typedef uint64_t u64
typedef uint8_t u8
Enumerations
enum {
SDBE_SUCCESS = 0 ,
SDBE_ERR = 1 ,
SDBE_DBS_UNAVAIL = 2 ,
SDBE_CP_UNAVAIL = 3 ,
SDBE_CONN_CLOSED_SUCS = 4 ,
SDBE_CONN_CLOSED_ERR = 5 ,
SDBE_PG_ERR = 6 ,
SDBE_JSON_ERR = 7 ,
SDBE_PTR_WAS_NULL = 8
}
Functions
void * Sdb__CallocTrace__ (u64 ElementCount, u64 ElementSize, int Line, const char *Func, sdb__log_module__ *Module)
void Sdb__FreeTrace__ (void *Pointer, int Line, const char *Func, sdb__log_module__ *Module)
u32 * Sdb__GetPCGState__ (void)
void * Sdb__MallocTrace__ (size_t Size, int Line, const char *Func, sdb__log_module__ *Module)
sdb_errno Sdb__MemMap__ (sdb_mmap *Map, void *MAddr, size_t MSize, int MProt, int MFlags, int MFd, off_t MOffset, sdb_string FileName, int OFlags, mode_t OMode, sdb__log_module__ *Module)
Creates a memory mapping with optional file backing.
void * Sdb__ReallocTrace__ (void *Pointer, size_t Size, int Line, const char *Func, sdb__log_module__ *Module)
sdb_scratch_arena Sdb__ScratchGet__ (sdb_arena **Conflicts, u64 ConflictCount, sdb__thread_arenas__ *TAs)
void Sdb__ScratchRelease__ (sdb_scratch_arena Scratch)
sdb_errno Sdb__ThreadArenasAdd__ (sdb_arena *Arena, sdb__thread_arenas__ *TAInstance)
void Sdb__ThreadArenasInit__ (sdb_arena *TABuf[], sdb__thread_arenas__ *TAs, sdb__thread_arenas__ **TAInstance)
void Sdb__ThreadArenasInitExtern__ (sdb__thread_arenas__ *TAs, sdb__thread_arenas__ **TAInstance)
i64 Sdb__WriteLog__ (sdb__log_module__ *Module, const char *LogLevel, const char *Fmt,...) __attribute__((format(printf
sdb_arena * SdbArenaBootstrap (sdb_arena *Arena, sdb_arena *NewArena_, u64 Size)
void SdbArenaClear (sdb_arena *Arena)
void SdbArenaClearZero (sdb_arena *Arena)
u64 SdbArenaGetPos (sdb_arena *Arena)
void SdbArenaInit (sdb_arena *Arena, u8 *Mem, u64 Size)
void * SdbArenaPop (sdb_arena *Arena, u64 Size)
void * SdbArenaPush (sdb_arena *Arena, u64 Size)
void * SdbArenaPushZero (sdb_arena *Arena, u64 Size)
u64 SdbArenaRemaining (sdb_arena *Arena)
u64 SdbArenaReserve (sdb_arena *Arena, u64 Size)
void * SdbArenaSeek (sdb_arena *Arena, u64 Pos)
void SdbArrayShift (void *Mem, u64 From, u64 To, u64 Count, u64 ElementSize)
bool SdbDoubleEpsilonCompare (const double A, const double B)
u64 SdbDoubleSignBit (double F)
sdb_token SdbGetNextToken (char **Cursor)
sdb_file_data * SdbLoadFileIntoMemory (const char *Filename, sdb_arena *Arena)
bool SdbMemcmp (const void *Lhs, const void *Rhs, size_t Len)
void * SdbMemcpy (void *__restrict To, const void *__restrict From, size_t Len)
int SdbMemMapAdvise (sdb_mmap *Map, int Advice)
int SdbMemMapSync (sdb_mmap *Map)
void * SdbMemset (void *__restrict Data, int SetTo, size_t Len)
size_t SdbMemSizeFromString (const char *SizeStr)
void SdbMemUnmap (sdb_mmap *Map)
void SdbMemZero (void *Mem, u64 Size)
void SdbMemZeroSecure (void *Mem, u64 Size)
double SdbRadiansFromDegrees (double Degrees)
u32 SdbRandPCG (void)
sdb_scratch_arena SdbScratchBegin (sdb_arena *Arena)
void SdbSeedRandPCG (uint32_t Seed)
char * SdbStrdup (char *String, sdb_arena *Arena)
static const char * SdbStrErr (sdb_errno E)
u64 SdbStringAllocSize (sdb_string String)
sdb_string SdbStringAppend (sdb_string String, sdb_string Other)
sdb_string SdbStringAppendC (sdb_string String, const char *Other)
sdb_string SdbStringAppendFmt (sdb_string String, const char *Fmt,...) __attribute__((format(printf
u64 SdbStringAvailableSpace (sdb_string String)
void SdbStringBackspace (sdb_string String, u64 N)
u64 SdbStringCap (sdb_string String)
void SdbStringClear (sdb_string String)
sdb_string SdbStringDuplicate (sdb_arena *A, const sdb_string String)
void SdbStringFree (sdb_string String)
u64 SdbStringLen (sdb_string String)
sdb_string SdbStringMake (sdb_arena *A, const char *String)
sdb_string SdbStringMakeSpace (sdb_string String, u64 AddLen)
sdb_string bool SdbStringsAreEqual (sdb_string Lhs, sdb_string Rhs)
sdb_string SdbStringSet (sdb_string String, const char *CString)
u64 SdbStrlen (const char *String)
u64 SdbStrnlen (const char *String, u64 Max)
bool SdbWrite_sdb_file_data_ToFile (sdb_file_data *FileData, const char *Filename)
bool SdbWriteBufferToFile (void *Buffer, u64 ElementSize, u64 ElementCount, const char *Filename)
Macro Definition Documentation
SDB__CONCAT2__
#define SDB__CONCAT2__ (x, y) x##y
Definition at line 131 of file Sdb.h.
SDB__CONCAT3__
#define SDB__CONCAT3__ (x, y, z) x##y##z
Definition at line 134 of file Sdb.h.
SDB__LOG__
#define SDB__LOG__ (log_level, fmt, ...)
Value:
    do {                                                                                           \
        if(SDB__LOG_LEVEL_CHECK__(log_level)) {                                                    \
            sdb_errno LogRet = Sdb__WriteLog__(Sdb__LogInstance__, SDB_STRINGIFY(log_level), fmt,  \
                                               ##__VA_ARGS__);                                     \
            assert(LogRet >= 0);                                                                   \
        }                                                                                          \
    } while(0)
Definition at line 219 of file Sdb.h.
SDB__LOG_LEVEL_CHECK__
#define SDB__LOG_LEVEL_CHECK__ (level) (SDB_LOG_LEVEL >= SDB_LOG_LEVEL_##level)
Definition at line 199 of file Sdb.h.
SDB__STRINGIFY__
#define SDB__STRINGIFY__ (x) #x
Definition at line 128 of file Sdb.h.
SDB_BEGIN_EXTERN_C
#define SDB_BEGIN_EXTERN_C
Definition at line 41 of file Sdb.h.
SDB_CONCAT2
#define SDB_CONCAT2 (x, y) SDB__CONCAT2__(x, y)
Definition at line 132 of file Sdb.h.
SDB_CONCAT3
#define SDB_CONCAT3 (x, y, z) SDB__CONCAT3__(x, y, z)
Definition at line 135 of file Sdb.h.
SDB_END_EXTERN_C
#define SDB_END_EXTERN_C
Definition at line 42 of file Sdb.h.
SDB_EXPAND
#define SDB_EXPAND (x) x
Definition at line 127 of file Sdb.h.
sdb_global
#define sdb_global static
Definition at line 52 of file Sdb.h.
sdb_internal
#define sdb_internal static
Definition at line 50 of file Sdb.h.
SDB_LOG_BUF_SIZE
#define SDB_LOG_BUF_SIZE 2048
Definition at line 167 of file Sdb.h.
SDB_LOG_DECLARE
#define SDB_LOG_DECLARE (name)
Value:
    extern sdb__log_module__  SDB_CONCAT3(Sdb__LogModule, name, __);                               \
    static sdb__log_module__ *Sdb__LogInstance__ __attribute__((used))                             \
    = &SDB_CONCAT3(Sdb__LogModule, name, __)
Definition at line 214 of file Sdb.h.
SDB_LOG_LEVEL
#define SDB_LOG_LEVEL 3
Definition at line 179 of file Sdb.h.
SDB_LOG_LEVEL_DBG
#define SDB_LOG_LEVEL_DBG (4U)
Definition at line 176 of file Sdb.h.
SDB_LOG_LEVEL_ERR
#define SDB_LOG_LEVEL_ERR (1U)
Definition at line 173 of file Sdb.h.
SDB_LOG_LEVEL_INF
#define SDB_LOG_LEVEL_INF (3U)
Definition at line 175 of file Sdb.h.
SDB_LOG_LEVEL_NONE
#define SDB_LOG_LEVEL_NONE (0U)
Definition at line 172 of file Sdb.h.
SDB_LOG_LEVEL_WRN
#define SDB_LOG_LEVEL_WRN (2U)
Definition at line 174 of file Sdb.h.
SDB_LOG_REGISTER
#define SDB_LOG_REGISTER (module_name)
Value:
    static char       SDB_CONCAT3(Sdb__LogModule, module_name, Buffer__)[SDB_LOG_BUF_SIZE];        \
    sdb__log_module__ SDB_CONCAT3(Sdb__LogModule, module_name, __) __attribute__((used))           \
    = { .Name       = SDB_STRINGIFY(module_name),                                                  \
        .BufferSize = SDB_LOG_BUF_SIZE,                                                            \
        .Buffer     = SDB_CONCAT3(Sdb__LogModule, module_name, Buffer__),                          \
        .Lock       = PTHREAD_MUTEX_INITIALIZER };                                                       \
    static sdb__log_module__ *Sdb__LogInstance__ __attribute__((used))                             \
    = &SDB_CONCAT3(Sdb__LogModule, module_name, __)
Definition at line 204 of file Sdb.h.
SDB_LOGGING_NOT_USED
#define SDB_LOGGING_NOT_USED static sdb__log_module__ *Sdb__LogInstance__ __attribute__((used)) = NULL
Definition at line 201 of file Sdb.h.
sdb_persist
#define sdb_persist static
Definition at line 51 of file Sdb.h.
SDB_POOL_ALLOCATOR_DEFINE
#define SDB_POOL_ALLOCATOR_DEFINE (type_name, func_name)
Value:
    typedef struct type_name##_pool                                                                \
    {                                                                                              \
        sdb_arena *Arena;                                                                          \
        type_name *FirstFree;                                                                      \
    } type_name##_pool;                                                                            \
                                                                                                   \
    type_name *func_name##Alloc(type_name##_pool *Pool)                                            \
    {                                                                                              \
        type_name *Result = Pool->FirstFree;                                                       \
        if(Result) {                                                                               \
            Pool->FirstFree = Pool->FirstFree->Next;                                               \
            SdbMemZeroStruct(Result);                                                              \
        } else {                                                                                   \
            Result = SdbPushStructZero(Pool->Arena, type_name);                                    \
        }                                                                                          \
                                                                                                   \
        return Result;                                                                             \
    }                                                                                              \
                                                                                                   \
    void func_name##Release(type_name##_pool *Pool, type_name *Instance)                           \
    {                                                                                              \
        Instance->Next  = Pool->FirstFree;                                                         \
        Pool->FirstFree = Instance;                                                                \
    }
Definition at line 355 of file Sdb.h.
SDB_STRING_HEADER
#define SDB_STRING_HEADER (str) ((sdb_string_header *)(str) - 1)
Definition at line 414 of file Sdb.h.
SDB_STRINGIFY
#define SDB_STRINGIFY (x) SDB__STRINGIFY__(x)
Definition at line 129 of file Sdb.h.
SDB_THREAD_ARENAS_EXTERN
#define SDB_THREAD_ARENAS_EXTERN (thread_name)
Value:
    extern __thread sdb__thread_arenas__  SDB_CONCAT3(Sdb__ThreadArenas, thread_name, __);         \
    static __thread sdb__thread_arenas__ *Sdb__ThreadArenasInstance__ __attribute__((used))
Definition at line 288 of file Sdb.h.
SDB_THREAD_ARENAS_REGISTER
#define SDB_THREAD_ARENAS_REGISTER (thread_name, count)
Value:
    static __thread sdb_arena *SDB_CONCAT3(Sdb__ThreadArenas, thread_name, Buffer__)[count]        \
        __attribute__((used));                                                                     \
    __thread sdb__thread_arenas__ SDB_CONCAT3(Sdb__ThreadArenas, thread_name, __)                  \
        __attribute__((used))                                                                      \
        = { .Arenas = NULL, .Count = 0, .MaxCount = count };                                       \
    static __thread sdb__thread_arenas__ *Sdb__ThreadArenasInstance__ __attribute__((used))
Definition at line 280 of file Sdb.h.
SdbArrayDeleteAndShift
#define SdbArrayDeleteAndShift (mem, i, count, esize) SdbArrayShift(mem, (i + 1), i, count, esize)
Definition at line 353 of file Sdb.h.
SdbArrayLen
#define SdbArrayLen (Array) (sizeof(Array) / sizeof(Array[0]))
Definition at line 149 of file Sdb.h.
SdbAssert
#define SdbAssert (...)
Definition at line 243 of file Sdb.h.
SdbGibiByte
#define SdbGibiByte (Number) (SdbMebiByte(Number) * 1024ULL)
Definition at line 145 of file Sdb.h.
SdbGigaByte
#define SdbGigaByte (Number) (SdbMegaByte(Number) * 1000ULL)
Definition at line 140 of file Sdb.h.
SdbKibiByte
#define SdbKibiByte (Number) (Number * 1024ULL)
Definition at line 143 of file Sdb.h.
SdbKiloByte
#define SdbKiloByte (Number) (Number * 1000ULL)
Definition at line 138 of file Sdb.h.
SdbLogDebug
#define SdbLogDebug (...) SDB__LOG__(DBG, ##__VA_ARGS__)
Definition at line 228 of file Sdb.h.
SdbLogError
#define SdbLogError (...) SDB__LOG__(ERR, ##__VA_ARGS__)
Definition at line 231 of file Sdb.h.
SdbLogInfo
#define SdbLogInfo (...) SDB__LOG__(INF, ##__VA_ARGS__)
Definition at line 229 of file Sdb.h.
SdbLogWarning
#define SdbLogWarning (...) SDB__LOG__(WRN, ##__VA_ARGS__)
Definition at line 230 of file Sdb.h.
SdbMax
#define SdbMax (a, b) ((a > b) ? a : b)
Definition at line 152 of file Sdb.h.
SdbMebiByte
#define SdbMebiByte (Number) (SdbKibiByte(Number) * 1024ULL)
Definition at line 144 of file Sdb.h.
SdbMegaByte
#define SdbMegaByte (Number) (SdbKiloByte(Number) * 1000ULL)
Definition at line 139 of file Sdb.h.
SdbMemMap
#define SdbMemMap (map, maddr, msize, mprot, mflags, mfd, moffset, filename, oflags, omode)
Value:
    Sdb__MemMap__(map, maddr, msize, mprot, mflags, mfd, moffset, filename, oflags, omode,         \
                  Sdb__LogInstance__)
Definition at line 579 of file Sdb.h.
SdbMemZeroStruct
#define SdbMemZeroStruct (struct) SdbMemZero(struct, sizeof(*struct))
Definition at line 324 of file Sdb.h.
SdbMemZeroStructSecure
#define SdbMemZeroStructSecure (struct) SdbMemZeroSecure(struct, sizeof(*struct))
Definition at line 325 of file Sdb.h.
SdbMin
#define SdbMin (a, b) ((a < b) ? a : b)
Definition at line 153 of file Sdb.h.
SdbPrintfDebug
#define SdbPrintfDebug (...)
Definition at line 185 of file Sdb.h.
SdbPushArray
#define SdbPushArray (arena, type, count) (type *)SdbArenaPush(arena, sizeof(type) * (count))
Definition at line 346 of file Sdb.h.
SdbPushArrayZero
#define SdbPushArrayZero (arena, type, count) (type *)SdbArenaPushZero(arena, sizeof(type) * (count))
Definition at line 347 of file Sdb.h.
SdbPushStruct
#define SdbPushStruct (arena, type) SdbPushArray(arena, type, 1)
Definition at line 349 of file Sdb.h.
SdbPushStructZero
#define SdbPushStructZero (arena, type) SdbPushArrayZero(arena, type, 1)
Definition at line 350 of file Sdb.h.
SdbScratchGet
#define SdbScratchGet (conflicts, conflict_count) Sdb__ScratchGet__(conflicts, conflict_count, Sdb__ThreadArenasInstance__)
Definition at line 314 of file Sdb.h.
SdbScratchRelease
#define SdbScratchRelease (scratch) Sdb__ScratchRelease__(scratch)
Definition at line 318 of file Sdb.h.
SdbTebiByte
#define SdbTebiByte (Number) (SdbGibiByte(Number) * 1024ULL)
Definition at line 146 of file Sdb.h.
SdbTeraByte
#define SdbTeraByte (Number) (SdbGigaByte(Number) * 1000ULL)
Definition at line 141 of file Sdb.h.
SdbThreadArenasAdd
#define SdbThreadArenasAdd (arena) Sdb__ThreadArenasAdd__(arena, Sdb__ThreadArenasInstance__)
Definition at line 308 of file Sdb.h.
SdbThreadArenasInit
#define SdbThreadArenasInit (thread_name)
Value:
    Sdb__ThreadArenasInit__(SDB_CONCAT3(Sdb__ThreadArenas, thread_name, Buffer__),                 \
                            &SDB_CONCAT3(Sdb__ThreadArenas, thread_name, __),                      \
                            &Sdb__ThreadArenasInstance__)
Definition at line 296 of file Sdb.h.
SdbThreadArenasInitExtern
#define SdbThreadArenasInitExtern (thread_name)
Value:
    Sdb__ThreadArenasInitExtern__(&SDB_CONCAT3(Sdb__ThreadArenas, thread_name, __),                \
                                  &Sdb__ThreadArenasInstance__)
Definition at line 302 of file Sdb.h.
Typedef Documentation
i16
typedef int16_t i16
Definition at line 61 of file Sdb.h.
i32
typedef int32_t i32
Definition at line 62 of file Sdb.h.
i64
typedef int64_t i64
Definition at line 63 of file Sdb.h.
i8
typedef int8_t i8
Definition at line 60 of file Sdb.h.
sdb__log_module__
typedef struct sdb__log_module__ sdb__log_module__
sdb_arena
typedef struct sdb_arena sdb_arena
sdb_errno
typedef int_least32_t sdb_errno
sdb_errno is a custom type to represent error and success codes in systems using Sdb. Values >= 0 indicate success, while values < 0 indicate errors.
Generic success is defined as 0, and generic error is defined as -1. Custom errno codes can be defined in the below enum.
When appropriate, negative POSIX errno values can be returned, e.g. -EINVAL.
Definition at line 77 of file Sdb.h.
sdb_slice
typedef struct sdb_slice sdb_slice
sdb_string
typedef char* sdb_string
Definition at line 405 of file Sdb.h.
u16
typedef uint16_t u16
Definition at line 56 of file Sdb.h.
u32
typedef uint32_t u32
Definition at line 57 of file Sdb.h.
u64
typedef uint64_t u64
Definition at line 58 of file Sdb.h.
u8
typedef uint8_t u8
Definition at line 55 of file Sdb.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SDBE_SUCCESS
SDBE_ERR
SDBE_DBS_UNAVAIL
SDBE_CP_UNAVAIL
SDBE_CONN_CLOSED_SUCS
SDBE_CONN_CLOSED_ERR
SDBE_PG_ERR
SDBE_JSON_ERR
SDBE_PTR_WAS_NULL
Definition at line 78 of file Sdb.h.
Function Documentation
Sdb__CallocTrace__()
void * Sdb__CallocTrace__ (u64 ElementCount, u64 ElementSize, int Line, const char * Func, sdb__log_module__ * Module)
Sdb__FreeTrace__()
void Sdb__FreeTrace__ (void * Pointer, int Line, const char * Func, sdb__log_module__ * Module)
Sdb__GetPCGState__()
u32 * Sdb__GetPCGState__ (void)
Sdb__MallocTrace__()
void * Sdb__MallocTrace__ (size_t Size, int Line, const char * Func, sdb__log_module__ * Module)
Sdb__MemMap__()
sdb_errno Sdb__MemMap__ (sdb_mmap * Map, void * MAddr, size_t MSize, int MProt, int MFlags, int MFd, off_t MOffset, sdb_string FileName, int OFlags, mode_t OMode, sdb__log_module__ * Module)
Creates a memory mapping with optional file backing.
This function provides a convenient wrapper around mmap() with integrated file handling. It can create both file-backed and anonymous mappings, with various protection and sharing options.
Parameters
Map Pointer to the sdb_mmap that will be filled
MAddr Desired mapping address (NULL for system choice)
MSize Size of the mapping in bytes
MProt Memory protection flags (can be combined with |):
PROT_NONE : No access permitted
PROT_READ : Pages can be read
PROT_WRITE : Pages can be written
PROT_EXEC : Pages can be executed
MFlags Mapping flags (can be combined with |):
MAP_SHARED : Updates visible to other processes
MAP_PRIVATE : Creates copy-on-write mapping
MAP_FIXED : Use exact address (not recommended)
MAP_ANONYMOUS : Create anonymous mapping (no file backing)
MAP_LOCKED : Lock pages into memory
MAP_POPULATE : Populate page tables
MAP_NORESERVE : No swap space reservation
MAP_HUGETLB : Use huge pages
MFd File descriptor for mapping:
>= 0 : Use this file descriptor
-1 : Used with MAP_ANONYMOUS
< -1 : Open file using FileName, OFlags, and OMode
MOffset Offset into file (must be page-aligned)
FileName Path to file (used only if MFd < -1)
OFlags File open flags (used only if MFd < -1), can combine with |: Required - one of:
O_RDONLY : Read only
O_WRONLY : Write only
O_RDWR : Read and write
Optional:
O_APPEND : Append to file
O_CREAT : Create if not exists
O_EXCL : With O_CREAT: fail if exists
O_TRUNC : Truncate to MSize (WARN: Will shrink the file if the file's size is > MSize)
O_DIRECT : Direct I/O
O_SYNC : Synchronous I/O
O_NOFOLLOW : Don't follow symlinks
O_CLOEXEC : Close on exec
O_TMPFILE : Create unnamed temporary file
Parameters
OMode File creation mode (used only if OFlags includes O_CREAT): Typical values (in octal):
: User: rw-, Group: r–, Other: r–
: User: rw-, Group: rw-, Other: rw-
: User: rw-, Group: —, Other: —
: User: rwx, Group: r-x, Other: r-x
Individual bits:
S_IRUSR (0400) : User read
S_IWUSR (0200) : User write
S_IXUSR (0100) : User execute
S_IRGRP (0040) : Group read
S_IWGRP (0020) : Group write
S_IXGRP (0010) : Group execute
S_IROTH (0004) : Other read
S_IWOTH (0002) : Other write
S_IXOTH (0001) : Other execute
Special bits:
S_ISUID (04000) : Set UID bit
S_ISGID (02000) : Set GID bit
S_ISVTX (01000) : Sticky bit
Returns
sdb_errno:
0 on success
Negative errno value on failure:
-EACCES : Permission denied
-EEXIST : File exists (with O_CREAT | O_EXCL)
-EINVAL : Invalid arguments
-ENFILE : System file table full
-ENOMEM : Out of memory
-ENOENT : File not found
Note
The Map structure must be allocated by the caller
FileName string must remain valid throughout the mapping's lifetime
File descriptor handling:
MAP_SHARED: fd kept open
MAP_PRIVATE: fd closed after mapping
MAP_ANONYMOUS: fd closed/ignored
The actual mapping size will be rounded up to the system page size
MProt permissions must be compatible with OFlags
The actual protection may be more restrictive than MProt due to file permissions
MAP_FIXED is dangerous and should be avoided
File permissions are masked by the process umask
Some combinations may not be supported on all systems
Sdb__ReallocTrace__()
void * Sdb__ReallocTrace__ (void * Pointer, size_t Size, int Line, const char * Func, sdb__log_module__ * Module)
Sdb__ScratchGet__()
sdb_scratch_arena Sdb__ScratchGet__ (sdb_arena ** Conflicts, u64 ConflictCount, sdb__thread_arenas__ * TAs)
Sdb__ScratchRelease__()
void Sdb__ScratchRelease__ (sdb_scratch_arena Scratch)
Sdb__ThreadArenasAdd__()
sdb_errno Sdb__ThreadArenasAdd__ (sdb_arena * Arena, sdb__thread_arenas__ * TAInstance)
Sdb__ThreadArenasInit__()
void Sdb__ThreadArenasInit__ (sdb_arena * TABuf[], sdb__thread_arenas__ * TAs, sdb__thread_arenas__ ** TAInstance)
Sdb__ThreadArenasInitExtern__()
void Sdb__ThreadArenasInitExtern__ (sdb__thread_arenas__ * TAs, sdb__thread_arenas__ ** TAInstance)
Sdb__WriteLog__()
i64 Sdb__WriteLog__ (sdb__log_module__ * Module, const char * LogLevel, const char * Fmt, ...)
SdbArenaBootstrap()
sdb_arena * SdbArenaBootstrap (sdb_arena * Arena, sdb_arena * NewArena_, u64 Size)
Referenced by MbPipeThroughputTest(), MbRun(), PgRun(), and SdpCreate().
SdbArenaClear()
void SdbArenaClear (sdb_arena * Arena)
Referenced by SdPipeFlush(), and SdPipeGetWriteBuffer().
SdbArenaClearZero()
void SdbArenaClearZero (sdb_arena * Arena)
SdbArenaGetPos()
u64 SdbArenaGetPos (sdb_arena * Arena)
Referenced by MbRun(), SdpCreate(), and SdPipeFlush().
SdbArenaInit()
void SdbArenaInit (sdb_arena * Arena, u8 * Mem, u64 Size)
Referenced by MbPipeThroughputTest(), MbRun(), PgRun(), and SdpCreate().
SdbArenaPop()
void * SdbArenaPop (sdb_arena * Arena, u64 Size)
SdbArenaPush()
void * SdbArenaPush (sdb_arena * Arena, u64 Size)
Referenced by MbPipeThroughputTest(), and MbRun().
SdbArenaPushZero()
void * SdbArenaPushZero (sdb_arena * Arena, u64 Size)
SdbArenaRemaining()
u64 SdbArenaRemaining (sdb_arena * Arena)
SdbArenaReserve()
u64 SdbArenaReserve (sdb_arena * Arena, u64 Size)
SdbArenaSeek()
void * SdbArenaSeek (sdb_arena * Arena, u64 Pos)
Referenced by SdpCreate().
SdbArrayShift()
void SdbArrayShift (void * Mem, u64 From, u64 To, u64 Count, u64 ElementSize)
SdbDoubleEpsilonCompare()
bool SdbDoubleEpsilonCompare (const double A, const double B)
SdbDoubleSignBit()
u64 SdbDoubleSignBit (double F)
SdbGetNextToken()
sdb_token SdbGetNextToken (char ** Cursor)
SdbLoadFileIntoMemory()
sdb_file_data * SdbLoadFileIntoMemory (const char * Filename, sdb_arena * Arena)
Referenced by DbInitGetConfFromFile(), MbPipeThroughputTest(), MbPrepareCtx(), PgPrepareCtx(), and SetUpFromConf().
SdbMemcmp()
bool SdbMemcmp (const void * Lhs, const void * Rhs, size_t Len)
SdbMemcpy()
void * SdbMemcpy (void *__restrict To, const void *__restrict From, size_t Len)
Referenced by GenerateModbusTcpFrame(), main(), MakeModbusTcpFrame(), MbPipeThroughputTest(), MbRun(), PgInsertData(), SdbTimePrintSpecDiffWT(), SendModbusData(), TgCreateGroup(), Write2(), Write4(), Write8(), and WriteTimestamp().
SdbMemMapAdvise()
int SdbMemMapAdvise (sdb_mmap * Map, int Advice)
SdbMemMapSync()
int SdbMemMapSync (sdb_mmap * Map)
SdbMemset()
void * SdbMemset (void *__restrict Data, int SetTo, size_t Len)
Referenced by RunModbusTestServer(), and SocketCreate().
SdbMemSizeFromString()
size_t SdbMemSizeFromString (const char * SizeStr)
Referenced by DhsGetMemAndScratchSize(), GetMemAndScratchSize(), and MbPgCreateTg().
SdbMemUnmap()
void SdbMemUnmap (sdb_mmap * Map)
Referenced by main().
SdbMemZero()
void SdbMemZero (void * Mem, u64 Size)
SdbMemZeroSecure()
void SdbMemZeroSecure (void * Mem, u64 Size)
SdbRadiansFromDegrees()
double SdbRadiansFromDegrees (double Degrees)
SdbRandPCG()
u32 SdbRandPCG (void)
SdbScratchBegin()
sdb_scratch_arena SdbScratchBegin (sdb_arena * Arena)
Referenced by DbInitGetConfFromFile().
SdbSeedRandPCG()
void SdbSeedRandPCG (uint32_t Seed)
SdbStrdup()
char * SdbStrdup (char * String, sdb_arena * Arena)
SdbStrErr()
static const char * SdbStrErr (sdb_errno E) inline static
Definition at line 97 of file Sdb.h.
References SDBE_CONN_CLOSED_ERR, SDBE_CONN_CLOSED_SUCS, SDBE_CP_UNAVAIL, SDBE_DBS_UNAVAIL, SDBE_ERR, SDBE_JSON_ERR, SDBE_PG_ERR, SDBE_PTR_WAS_NULL, and SDBE_SUCCESS.
Referenced by MbPgPipeThroughputTest(), MbThread(), and PgThread().
SdbStringAllocSize()
u64 SdbStringAllocSize (sdb_string String)
SdbStringAppend()
sdb_string SdbStringAppend (sdb_string String, sdb_string Other)
Referenced by PgPrepareCtx().
SdbStringAppendC()
sdb_string SdbStringAppendC (sdb_string String, const char * Other)
Referenced by PgPrepareCtx().
SdbStringAppendFmt()
sdb_string SdbStringAppendFmt (sdb_string String, const char * Fmt, ...)
Referenced by GetTableMetadata().
SdbStringAvailableSpace()
u64 SdbStringAvailableSpace (sdb_string String)
SdbStringBackspace()
void SdbStringBackspace (sdb_string String, u64 N)
Referenced by PgPrepareCtx().
SdbStringCap()
u64 SdbStringCap (sdb_string String)
SdbStringClear()
void SdbStringClear (sdb_string String)
SdbStringDuplicate()
sdb_string SdbStringDuplicate (sdb_arena * A, const sdb_string String)
SdbStringFree()
void SdbStringFree (sdb_string String)
SdbStringLen()
u64 SdbStringLen (sdb_string String)
SdbStringMake()
sdb_string SdbStringMake (sdb_arena * A, const char * String)
Referenced by GetTableMetadata(), MbPrepareCtx(), and PgPrepareCtx().
SdbStringMakeSpace()
sdb_string SdbStringMakeSpace (sdb_string String, u64 AddLen)
SdbStringsAreEqual()
sdb_string bool SdbStringsAreEqual (sdb_string Lhs, sdb_string Rhs)
SdbStringSet()
sdb_string SdbStringSet (sdb_string String, const char * CString)
SdbStrlen()
u64 SdbStrlen (const char * String)
SdbStrnlen()
u64 SdbStrnlen (const char * String, u64 Max)
SdbWrite_sdb_file_data_ToFile()
bool SdbWrite_sdb_file_data_ToFile (sdb_file_data * FileData, const char * Filename)
SdbWriteBufferToFile()
bool SdbWriteBufferToFile (void * Buffer, u64 ElementSize, u64 ElementCount, const char * Filename)