Sensor Data Handler System: src/Common/SensorDataPipe.c File Reference
SensorDataPipe.c File Reference
Implementation of lock free Data Pipeline.
#include <stdio.h>
#include <sys/eventfd.h>
#include <src/Sdb.h>
#include <src/Common/SensorDataPipe.h>
#include <src/Common/Thread.h>
#include <src/Common/Time.h>
Functions
SDB_LOG_REGISTER (SensorDataPipe)
sensor_data_pipe * SdpCreate (u64 BufCount, u64 BufSize, sdb_arena *Arena)
Create Sensor Data Pipeline.
void SdpDestroy (sensor_data_pipe *Pipe, bool AllocatedWithArena)
Destroy Sensor Data Pipeline.
void SdPipeFlush (sensor_data_pipe *Pipe)
Flush the current write buffer.
sdb_arena * SdPipeGetReadBuffer (sensor_data_pipe *Pipe)
Acquire Read Buffer Arena.
sdb_arena * SdPipeGetWriteBuffer (sensor_data_pipe *Pipe)
Acquire Write Buffer Arena.
Detailed Description
Implementation of lock free Data Pipeline.
Provides a high-performance, lock-free data transmission mechanism using memory arenas and atomic operations.
Definition in file SensorDataPipe.c.
Function Documentation
SDB_LOG_REGISTER()
SDB_LOG_REGISTER (SensorDataPipe)
SdpCreate()
sensor_data_pipe* SdpCreate (u64 BufCount, u64 BufSize, sdb_arena * Arena)
Create Sensor Data Pipeline.
Create a Sensor Data Pipeline.
Parameters
BufCount Number of buffer arenas in pipeline
BufSize Size of each buffer arena
Arena Optional memory arena for allocation
Returns
sensor_data_pipe* Initialized pipeline or NULL
Definition at line 35 of file SensorDataPipe.c.
References sensor_data_pipe::BufCount, sensor_data_pipe::Buffers, sensor_data_pipe::FullBuffersCount, sdb_arena::Mem, sensor_data_pipe::ReadBufIdx, sensor_data_pipe::ReadEventFd, SdbArenaBootstrap(), SdbArenaGetPos(), SdbArenaInit(), SdbArenaSeek(), SdbLogError, SdbPushArray, SdbPushStruct, sensor_data_pipe::WriteBufIdx, and sensor_data_pipe::WriteEventFd.
Referenced by MbPgCreateTg().
SdpDestroy()
void SdpDestroy (sensor_data_pipe * Pipe, bool AllocatedWithArena)
Destroy Sensor Data Pipeline.
Performs cleanup of:
Event file descriptors
Optionally frees allocated memory
Parameters
Pipe Pipeline to destroy
AllocatedWithArena Whether pipeline was arena-allocated
Definition at line 93 of file SensorDataPipe.c.
References sensor_data_pipe::ReadEventFd, and sensor_data_pipe::WriteEventFd.
Referenced by MbPgCleanup().
SdPipeFlush()
void SdPipeFlush (sensor_data_pipe * Pipe)
Flush the current write buffer.
Flush Partial Buffer Arena.
If the current write buffer is not empty, it is marked as full and the next buffer is prepared. If the next buffer is already full, the function will block until a slot is available.
Parameters
Pipe Pipeline instance
Definition at line 192 of file SensorDataPipe.c.
References sensor_data_pipe::BufCount, sensor_data_pipe::Buffers, sensor_data_pipe::FullBuffersCount, sensor_data_pipe::ReadEventFd, SdbArenaClear(), SdbArenaGetPos(), SdbLogError, SdbLogWarning, sensor_data_pipe::WriteBufIdx, and sensor_data_pipe::WriteEventFd.
Referenced by MbPipeThroughputTest(), and MbRun().
SdPipeGetReadBuffer()
sdb_arena* SdPipeGetReadBuffer (sensor_data_pipe * Pipe)
Acquire Read Buffer Arena.
Obtains the next available memory arena for reading, blocking until data is available.
Parameters
Pipe Pipeline instance
Returns
sdb_arena* Available read buffer arena or NULL
Definition at line 155 of file SensorDataPipe.c.
References sensor_data_pipe::BufCount, sensor_data_pipe::Buffers, sensor_data_pipe::FullBuffersCount, sensor_data_pipe::ReadBufIdx, sensor_data_pipe::ReadEventFd, SdbLogError, and sensor_data_pipe::WriteEventFd.
Referenced by PgRun().
SdPipeGetWriteBuffer()
sdb_arena* SdPipeGetWriteBuffer (sensor_data_pipe * Pipe)
Acquire Write Buffer Arena.
Obtains the next available memory arena for writing, blocking if no buffer is available.
Parameters
Pipe Pipeline instance
Returns
sdb_arena* Available write buffer arena or NULL
Definition at line 113 of file SensorDataPipe.c.
References sensor_data_pipe::BufCount, sensor_data_pipe::Buffers, sensor_data_pipe::FullBuffersCount, sensor_data_pipe::ReadEventFd, SdbArenaClear(), SdbLogError, sensor_data_pipe::WriteBufIdx, and sensor_data_pipe::WriteEventFd.
Referenced by MbPipeThroughputTest(), and MbRun().