Sensor Data Handler System: src/Common/SensorDataPipe.h File Reference
SensorDataPipe.h File Reference
Lock-Free Data Pipeline.
#include <stdatomic.h>
#include <src/Sdb.h>
#include <src/Common/Thread.h>
Classes
struct sensor_data_pipe
Sensor Data Pipeline Structure.
Functions
sensor_data_pipe * SdpCreate (u64 BufCount, u64 BufSize, sdb_arena *Arena)
Create a Sensor Data Pipeline.
void SdpDestroy (sensor_data_pipe *Pipe, bool AllocatedWithArena)
Destroy Sensor Data Pipeline.
void SdPipeFlush (sensor_data_pipe *Pipe)
Flush Partial Buffer Arena.
sdb_arena * SdPipeGetReadBuffer (sensor_data_pipe *Pipe)
Acquire Read Buffer Arena.
sdb_arena * SdPipeGetWriteBuffer (sensor_data_pipe *Pipe)
Acquire Write Buffer Arena.
Detailed Description
Lock-Free Data Pipeline.
Key Features:
Lock-free buffer management
Dynamic arena allocation
Event-driven synchronization
Definition in file SensorDataPipe.h.
Function Documentation
SdpCreate()
sensor_data_pipe * SdpCreate (u64 BufCount, u64 BufSize, sdb_arena * Arena)
Create a Sensor Data Pipeline.
Initializes a set of memory arenas with event-based synchronization for inter-thread data transfer.
Parameters
BufCount Number of buffers in the pipeline
BufSize Size of each buffer arena
Arena Optional memory arena for allocation
Returns
sensor_data_pipe* Initialized pipeline or NULL on failure
Create a Sensor Data Pipeline.
Parameters
BufCount Number of buffer arenas in pipeline
BufSize Size of each buffer arena
Arena Optional memory arena for allocation
Returns
sensor_data_pipe* Initialized pipeline or NULL
Definition at line 35 of file SensorDataPipe.c.
References sensor_data_pipe::BufCount, sensor_data_pipe::Buffers, sensor_data_pipe::FullBuffersCount, sdb_arena::Mem, sensor_data_pipe::ReadBufIdx, sensor_data_pipe::ReadEventFd, SdbArenaBootstrap(), SdbArenaGetPos(), SdbArenaInit(), SdbArenaSeek(), SdbLogError, SdbPushArray, SdbPushStruct, sensor_data_pipe::WriteBufIdx, and sensor_data_pipe::WriteEventFd.
Referenced by MbPgCreateTg().
SdpDestroy()
void SdpDestroy (sensor_data_pipe * Pipe, bool AllocatedWithArena)
Destroy Sensor Data Pipeline.
Closes event file descriptors and optionally frees memory.
Parameters
Pipe Pipeline to destroy
AllocatedWithArena Whether pipeline was arena-allocated
Performs cleanup of:
Event file descriptors
Optionally frees allocated memory
Parameters
Pipe Pipeline to destroy
AllocatedWithArena Whether pipeline was arena-allocated
Definition at line 93 of file SensorDataPipe.c.
References sensor_data_pipe::ReadEventFd, and sensor_data_pipe::WriteEventFd.
Referenced by MbPgCleanup().
SdPipeFlush()
void SdPipeFlush (sensor_data_pipe * Pipe)
Flush Partial Buffer Arena.
Signals and transitions a partially filled buffer arena to the read side of the pipeline.
Parameters
Pipe Pipeline instance
Flush Partial Buffer Arena.
If the current write buffer is not empty, it is marked as full and the next buffer is prepared. If the next buffer is already full, the function will block until a slot is available.
Parameters
Pipe Pipeline instance
Definition at line 192 of file SensorDataPipe.c.
References sensor_data_pipe::BufCount, sensor_data_pipe::Buffers, sensor_data_pipe::FullBuffersCount, sensor_data_pipe::ReadEventFd, SdbArenaClear(), SdbArenaGetPos(), SdbLogError, SdbLogWarning, sensor_data_pipe::WriteBufIdx, and sensor_data_pipe::WriteEventFd.
Referenced by MbPipeThroughputTest(), and MbRun().
SdPipeGetReadBuffer()
sdb_arena * SdPipeGetReadBuffer (sensor_data_pipe * Pipe)
Acquire Read Buffer Arena.
Obtains the next available memory arena for reading, blocking until data is available.
Parameters
Pipe Pipeline instance
Returns
sdb_arena* Available read buffer arena or NULL
Definition at line 155 of file SensorDataPipe.c.
References sensor_data_pipe::BufCount, sensor_data_pipe::Buffers, sensor_data_pipe::FullBuffersCount, sensor_data_pipe::ReadBufIdx, sensor_data_pipe::ReadEventFd, SdbLogError, and sensor_data_pipe::WriteEventFd.
Referenced by PgRun().
SdPipeGetWriteBuffer()
sdb_arena * SdPipeGetWriteBuffer (sensor_data_pipe * Pipe)
Acquire Write Buffer Arena.
Obtains the next available memory arena for writing, blocking if no buffer is available.
Parameters
Pipe Pipeline instance
Returns
sdb_arena* Available write buffer arena or NULL
Definition at line 113 of file SensorDataPipe.c.
References sensor_data_pipe::BufCount, sensor_data_pipe::Buffers, sensor_data_pipe::FullBuffersCount, sensor_data_pipe::ReadEventFd, SdbArenaClear(), SdbLogError, sensor_data_pipe::WriteBufIdx, and sensor_data_pipe::WriteEventFd.
Referenced by MbPipeThroughputTest(), and MbRun().