Sensor Data Handler System: src/Signals.c File Reference
Signals.c File Reference
Signal handling implementation for the Sensor Data Handler System.
#include <errno.h>
#include <execinfo.h>
#include <fcntl.h>
#include <pthread.h>
#include <signal.h>
#include <src/Signals.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>
#include <src/Sdb.h>
#include <src/Common/SensorDataPipe.h>
#include <src/DevUtils/TestConstants.h>
Macros
#define _GNU_SOURCE
#define BACKTRACE_SIZE 50
Functions
void ConvertDumpToCSV (const char *DumpFileName, const char *CsvFileName)
Converts a binary dump file to CSV format.
static void DumpProcessMemory (int SignalNum, siginfo_t *Info)
Creates a memory dump of the process state.
static pid_t GetThreadId (void)
static void GetThreadName (char *Name, size_t Size)
static bool HandlePipeDump (void)
Handles internal pipe dump operations.
static void InitiateGracefulShutdown (void)
Initiates system shutdown with proper synchronization.
SDB_LOG_REGISTER (Signals)
bool SdbDumpSensorDataPipe (sensor_data_pipe *Pipe, const char *Filename)
Dumps sensor data pipe contents to a file.
bool SdbIsShutdownInProgress (void)
void SdbSetMemoryDumpPath (const char *Path)
int SdbSetupSignalHandlers (struct tg_manager *Manager)
Sets up signal handlers for the application.
bool SdbShouldShutdown (void)
Checks if the system should initiate shutdown.
static void SignalHandler (int SignalNum, siginfo_t *Info, void *Context)
Internal signal handler to process system signals.
Variables
static volatile sig_atomic_t GShutdownRequested = 0
Context structure for signal handling This should be documented in the header file (Signals.h)
signal_handler_context GSignalContext = { 0 }
Global signal handler context.
Detailed Description
Signal handling implementation for the Sensor Data Handler System.
Implements signal handling, memory dumping, and graceful shutdown mechanisms for the sensor data handling system. Includes facilities for process memory dumps and pipe data preservation during crashes or shutdowns.
Definition in file Signals.c.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 10 of file Signals.c.
BACKTRACE_SIZE
#define BACKTRACE_SIZE 50
Definition at line 32 of file Signals.c.
Function Documentation
ConvertDumpToCSV()
void ConvertDumpToCSV (const char * DumpFileName, const char * CsvFileName)
Converts a binary dump file to CSV format.
Transforms raw sensor data dumps into human-readable CSV files containing packet information with timestamps and sensor readings.
Parameters
dumpFileName Source binary dump file
csvFileName Destination CSV file
Definition at line 357 of file Signals.c.
References shaft_power_data.
DumpProcessMemory()
static void DumpProcessMemory (int SignalNum, siginfo_t * Info) static
Creates a memory dump of the process state.
Generates a comprehensive dump including:
Stack trace
Thread information
Memory regions
Signal context
Parameters
SignalNum The signal that triggered the dump
Info Signal information structure
Definition at line 70 of file Signals.c.
References BACKTRACE_SIZE, GetThreadId(), GetThreadName(), SdbLogError, and SdbLogInfo.
Referenced by SignalHandler().
GetThreadId()
static pid_t GetThreadId (void) static
Definition at line 42 of file Signals.c.
Referenced by DumpProcessMemory().
GetThreadName()
static void GetThreadName (char * Name, size_t Size) static
Definition at line 48 of file Signals.c.
Referenced by DumpProcessMemory().
HandlePipeDump()
static bool HandlePipeDump (void) static
Handles internal pipe dump operations.
Creates timestamped dump files of pipe contents during signal handling. Used by the signal handler to preserve data during crashes.
Returns
true if dump successful, false on error
Definition at line 173 of file Signals.c.
References GSignalContext, signal_handler_context::Pipe, SdbDumpSensorDataPipe(), and SdbLogError.
Referenced by SignalHandler().
InitiateGracefulShutdown()
static void InitiateGracefulShutdown (void) static
Initiates system shutdown with proper synchronization.
Uses atomic operations to ensure thread-safe shutdown initiation
Definition at line 158 of file Signals.c.
References GShutdownRequested, and SdbLogInfo.
Referenced by SignalHandler().
SDB_LOG_REGISTER()
SDB_LOG_REGISTER (Signals)
SdbDumpSensorDataPipe()
bool SdbDumpSensorDataPipe (sensor_data_pipe * Pipe, const char * Filename)
Dumps sensor data pipe contents to a file.
Creates a binary dump of the pipe's current state including all buffer contents and metadata.
Parameters
pipe Pointer to the sensor data pipe to dump
filename Path where the dump will be saved
Returns
true if successful, false if any error occurred
Definition at line 324 of file Signals.c.
References sensor_data_pipe::BufCount, sensor_data_pipe::BufferMaxFill, sensor_data_pipe::Buffers, sdb_arena::Cur, sensor_data_pipe::ItemMaxCount, sdb_arena::Mem, sensor_data_pipe::PacketSize, SdbLogError, and SdbLogInfo.
Referenced by HandlePipeDump().
SdbIsShutdownInProgress()
bool SdbIsShutdownInProgress (void)
Definition at line 302 of file Signals.c.
References GSignalContext, and signal_handler_context::ShutdownFlag.
SdbSetMemoryDumpPath()
void SdbSetMemoryDumpPath (const char * Path)
Definition at line 293 of file Signals.c.
References GSignalContext, and signal_handler_context::MemoryDumpPath.
SdbSetupSignalHandlers()
int SdbSetupSignalHandlers (struct tg_manager * Manager)
Sets up signal handlers for the application.
Initializes signal handlers for the application.
Sets up handlers for system signals including SIGINT, SIGTERM, SIGSEGV, SIGABRT, SIGFPE, and SIGILL.
Parameters
Manager Thread group manager to be controlled by signals
Returns
0 on success, -1 on failure
Definition at line 268 of file Signals.c.
References GSignalContext, signal_handler_context::Manager, SdbLogError, and SignalHandler().
Referenced by main().
SdbShouldShutdown()
bool SdbShouldShutdown (void)
Checks if the system should initiate shutdown.
Returns
true if shutdown should be initiated
false if operation should continue
Definition at line 308 of file Signals.c.
References GShutdownRequested.
Referenced by MbPgPipeThroughputTest(), MbRun(), PgRun(), RunModbusTestServer(), and TgManagerWaitForAll().
SignalHandler()
static void SignalHandler (int SignalNum, siginfo_t * Info, void * Context) static
Internal signal handler to process system signals.
Handles different types of signals:
SIGINT/SIGTERM: Initiates graceful shutdown
SIGSEGV: Handles segmentation faults
SIGABRT: Handles abnormal terminations
SIGFPE: Handles floating point exceptions
SIGILL: Handles illegal instructions
Parameters
SignalNum Signal number received
Info Signal information structure
Context Signal context
Definition at line 212 of file Signals.c.
References DumpProcessMemory(), HandlePipeDump(), InitiateGracefulShutdown(), SdbLogError, and SdbLogWarning.
Referenced by SdbSetupSignalHandlers().
Variable Documentation
GShutdownRequested
volatile sig_atomic_t GShutdownRequested = 0 static
Context structure for signal handling This should be documented in the header file (Signals.h)
Definition at line 38 of file Signals.c.
Referenced by InitiateGracefulShutdown(), and SdbShouldShutdown().
GSignalContext
signal_handler_context GSignalContext = { 0 }
Global signal handler context.
Definition at line 39 of file Signals.c.
Referenced by HandlePipeDump(), MbPgCreateTg(), SdbIsShutdownInProgress(), SdbSetMemoryDumpPath(), and SdbSetupSignalHandlers().