Sensor Data Handler System: src/Signals.h File Reference
Signals.h File Reference
Signal handling interface for the Sensor Data Handler System.
#include <signal.h>
#include <src/Sdb.h>
#include <src/Common/SensorDataPipe.h>
#include <src/Common/ThreadGroup.h>
#include <src/Libs/cJSON/cJSON.h>
Classes
struct signal_handler_context
Context structure maintaining signal handler state.
Typedefs
typedef struct signal_handler_context signal_handler_context
Functions
void ConvertDumpToCSV (const char *DumpFileName, const char *CsvFileName)
Converts a binary dump file to CSV format.
bool SdbDumpSensorDataPipe (sensor_data_pipe *Pipe, const char *Filename)
Dumps sensor data pipe contents to a file.
int SdbSetupSignalHandlers (tg_manager *Manager)
Initializes signal handlers for the application.
bool SdbShouldShutdown (void)
Checks if the system should initiate shutdown.
Variables
signal_handler_context GSignalContext
Global signal handler context.
Detailed Description
Signal handling interface for the Sensor Data Handler System.
Provides signal handling, crash dump functionality, and graceful shutdown mechanisms for the sensor data handling system. This module manages system signals and ensures proper data preservation during shutdowns or crashes.
Definition in file Signals.h.
Typedef Documentation
signal_handler_context
typedef struct signal_handler_context signal_handler_context
Function Documentation
ConvertDumpToCSV()
void ConvertDumpToCSV (const char * DumpFileName, const char * CsvFileName)
Converts a binary dump file to CSV format.
Transforms raw sensor data dumps into human-readable CSV files containing packet information with timestamps and sensor readings.
Parameters
dumpFileName Source binary dump file
csvFileName Destination CSV file
Definition at line 357 of file Signals.c.
References shaft_power_data.
SdbDumpSensorDataPipe()
bool SdbDumpSensorDataPipe (sensor_data_pipe * Pipe, const char * Filename)
Dumps sensor data pipe contents to a file.
Creates a binary dump of the pipe's current state including all buffer contents and metadata.
Parameters
pipe Pointer to the sensor data pipe to dump
filename Path where the dump will be saved
Returns
true if successful, false if any error occurred
Definition at line 324 of file Signals.c.
References sensor_data_pipe::BufCount, sensor_data_pipe::BufferMaxFill, sensor_data_pipe::Buffers, sdb_arena::Cur, sensor_data_pipe::ItemMaxCount, sdb_arena::Mem, sensor_data_pipe::PacketSize, SdbLogError, and SdbLogInfo.
Referenced by HandlePipeDump().
SdbSetupSignalHandlers()
int SdbSetupSignalHandlers (struct tg_manager * Manager)
Initializes signal handlers for the application.
Sets up handlers for system signals including SIGINT, SIGTERM, SIGSEGV, SIGABRT, SIGFPE, and SIGILL.
Parameters
manager Thread group manager to be controlled by signals
Returns
0 on success, -1 on failure
Initializes signal handlers for the application.
Sets up handlers for system signals including SIGINT, SIGTERM, SIGSEGV, SIGABRT, SIGFPE, and SIGILL.
Parameters
Manager Thread group manager to be controlled by signals
Returns
0 on success, -1 on failure
Definition at line 268 of file Signals.c.
References GSignalContext, signal_handler_context::Manager, SdbLogError, and SignalHandler().
Referenced by main().
SdbShouldShutdown()
bool SdbShouldShutdown (void)
Checks if the system should initiate shutdown.
Returns
true if shutdown should be initiated
false if operation should continue
Definition at line 308 of file Signals.c.
References GShutdownRequested.
Referenced by MbPgPipeThroughputTest(), MbRun(), PgRun(), RunModbusTestServer(), and TgManagerWaitForAll().
Variable Documentation
GSignalContext
signal_handler_context GSignalContext extern
Global signal handler context.
Definition at line 39 of file Signals.c.
Referenced by HandlePipeDump(), MbPgCreateTg(), SdbIsShutdownInProgress(), SdbSetMemoryDumpPath(), and SdbSetupSignalHandlers().