Sensor Data Handler System: src/Common/Socket.h File Reference
Socket.h File Reference
Simplified Socket Communication Utilities.
#include <src/Sdb.h>
#include <src/Common/Time.h>
#include <sys/socket.h>
#include <sys/types.h>
Functions
SDB_BEGIN_EXTERN_C int SocketCreate (const char *IpAddress, int Port)
Create and Connect a TCP Socket.
int SocketRecvWithTimeout (int SockFd, void *Buffer, size_t Length, sdb_timediff Timeout)
Receive Data with Timeout.
Detailed Description
Simplified Socket Communication Utilities.
Provides high-level, error-handled socket creation and receive operations with timeout support.
Key Features:
IPv4 TCP socket creation
Connection establishment with error handling
Receive operation with configurable timeout
Design Principles:
Robust error reporting
Simplified socket management
Timeout-based receive mechanism
Note
Uses standard POSIX socket interfaces
Definition in file Socket.h.
Function Documentation
SocketCreate()
SDB_BEGIN_EXTERN_C int SocketCreate (const char * IpAddress, int Port)
Create and Connect a TCP Socket.
Establishes a TCP connection to specified IP and port.
Parameters
IpAddress Destination IP address (IPv4 dot-decimal notation)
Port Destination port number
Returns
int
Socket file descriptor on success
-1 on connection failure
Note
Includes a 1-second connection delay for stability
Create and Connect a TCP Socket.
Performs socket creation and connection with comprehensive error handling and logging.
Steps:
Create TCP socket
Configure server address
Convert IP address
Establish connection with brief delay
Parameters
IpAddress Destination IP address
Port Destination port number
Returns
int Socket file descriptor or error code
Definition at line 55 of file Socket.c.
References SdbLogError, and SdbMemset().
Referenced by MbPrepareCtx().
SocketRecvWithTimeout()
int SocketRecvWithTimeout (int SockFd, void * Buffer, size_t Length, sdb_timediff TimeoutDiff)
Receive Data with Timeout.
Attempts to receive data from a socket with a specified timeout.
Parameters
SockFd Socket file descriptor
Buffer Destination buffer for received data
Length Maximum number of bytes to receive
Timeout Maximum time to wait for data
Returns
int
>0: Number of bytes received
0: Connection closed by server
-1: Socket error
-2: Receive timeout
Receive Data with Timeout.
Implements a receive operation with:
Timeout mechanism using select()
Comprehensive error handling
Detailed logging of connection states
Parameters
SockFd Socket file descriptor
Buffer Destination for received data
Length Maximum receive buffer size
TimeoutDiff Maximum wait time
Returns
int
Bytes received
Connection status indicators
Definition at line 106 of file Socket.c.
References SDB_TIME_TO_MS, SdbLogError, SdbLogWarning, and SdbTimeval().
Referenced by MbRun().