Sensor Data Handler System: src/Common/Socket.c File Reference
Socket.c File Reference
Implementation of Socket Communication Utilities.
#include <arpa/inet.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>
#include <src/Sdb.h>
#include <src/Common/Socket.h>
Functions
SDB_LOG_REGISTER (Socket)
int SocketCreate (const char *IpAddress, int Port)
Create and Connect TCP Socket.
int SocketRecvWithTimeout (int SockFd, void *Buffer, size_t Length, sdb_timediff TimeoutDiff)
Receive Data with Configurable Timeout.
Detailed Description
Implementation of Socket Communication Utilities.
Provides concrete implementations for socket creation and receive operations with comprehensive error handling.
Core Functionalities:
TCP socket establishment
Connection management
Timeout-based data reception
Design Highlights:
Detailed error logging
Robust connection handling
Flexible timeout mechanisms
Note
Uses standard POSIX socket programming techniques
Definition in file Socket.c.
Function Documentation
SDB_LOG_REGISTER()
SDB_LOG_REGISTER (Socket)
SocketCreate()
int SocketCreate (const char * IpAddress, int Port)
Create and Connect TCP Socket.
Create and Connect a TCP Socket.
Performs socket creation and connection with comprehensive error handling and logging.
Steps:
Create TCP socket
Configure server address
Convert IP address
Establish connection with brief delay
Parameters
IpAddress Destination IP address
Port Destination port number
Returns
int Socket file descriptor or error code
Definition at line 55 of file Socket.c.
References SdbLogError, and SdbMemset().
Referenced by MbPrepareCtx().
SocketRecvWithTimeout()
int SocketRecvWithTimeout (int SockFd, void * Buffer, size_t Length, sdb_timediff TimeoutDiff)
Receive Data with Configurable Timeout.
Receive Data with Timeout.
Implements a receive operation with:
Timeout mechanism using select()
Comprehensive error handling
Detailed logging of connection states
Parameters
SockFd Socket file descriptor
Buffer Destination for received data
Length Maximum receive buffer size
TimeoutDiff Maximum wait time
Returns
int
Bytes received
Connection status indicators
Definition at line 106 of file Socket.c.
References SDB_TIME_TO_MS, SdbLogError, SdbLogWarning, and SdbTimeval().
Referenced by MbRun().