Sensor Data Handler System: src/DevUtils/TestDataGenerator.c File Reference
TestDataGenerator.c File Reference
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
#include <src/Sdb.h>
#include <src/CommProtocols/Modbus.h>
#include <src/Common/Socket.h>
#include <src/Common/Thread.h>
#include <src/Common/Time.h>
#include <src/DatabaseSystems/Postgres.h>
#include <src/DevUtils/TestConstants.h>
Macros
#define SDB_H_IMPLEMENTATION
Functions
static void FillShaftPowerData (shaft_power_data *Data)
int main (void)
static void MakeModbusTcpFrame (u8 *Buffer, u16 TransactionId, u16 ProtocolId, u16 Length, u8 UnitId, u16 FunctionCode, u8 *Data, u16 DataLength)
int PrintTestDataSample (sdb_string Filename)
SDB_LOG_REGISTER (TestDataGenerator)
Macro Definition Documentation
SDB_H_IMPLEMENTATION
#define SDB_H_IMPLEMENTATION
Definition at line 10 of file TestDataGenerator.c.
Function Documentation
FillShaftPowerData()
static void FillShaftPowerData (shaft_power_data * Data) static
Definition at line 26 of file TestDataGenerator.c.
Referenced by main().
main()
int main (void)
Definition at line 105 of file TestDataGenerator.c.
References sdb_mmap::Data, FillShaftPowerData(), PrintTestDataSample(), SdbMemcpy(), SdbMemMap, SdbMemUnmap(), and shaft_power_data.
MakeModbusTcpFrame()
static void MakeModbusTcpFrame (u8 * Buffer, u16 TransactionId, u16 ProtocolId, u16 Length, u8 UnitId, u16 FunctionCode, u8 * Data, u16 DataLength) static
Definition at line 40 of file TestDataGenerator.c.
References SdbMemcpy().
PrintTestDataSample()
int PrintTestDataSample (sdb_string Filename)
Definition at line 56 of file TestDataGenerator.c.
References shaft_power_data.
Referenced by main().
SDB_LOG_REGISTER()
SDB_LOG_REGISTER (TestDataGenerator)