Sensor Data Handler System: src/Common/ThreadGroup.h File Reference
ThreadGroup.h File Reference
Thread Group Management System.
#include <pthread.h>
#include <stdbool.h>
#include <src/Sdb.h>
#include <src/Common/Thread.h>
Classes
struct tg_group
Thread Group Structure.
struct tg_manager
Thread Group Manager Structure.
Typedefs
typedef sdb_errno(* tg_cleanup) (void *)
Cleanup function signature.
typedef void *(* tg_init) (void)
Initialization function signature.
typedef struct tg_manager tg_manager
typedef void *(* tg_task) (void *)
Thread task function signature.
Functions
tg_group * TgCreateGroup (u64 GroupId, u64 ThreadCount, void *SharedData, tg_init Init, tg_task *Tasks, tg_cleanup Cleanup, sdb_arena *A)
Create a Thread Group.
tg_manager * TgCreateManager (tg_group **Groups, u64 GroupCount, sdb_arena *A)
Create a Thread Group Manager.
void TgDestroyManager (tg_manager *M)
Destroy Thread Group Manager.
sdb_errno TgManagerStartAll (tg_manager *Manager)
Start All Thread Groups in Manager.
void TgManagerWaitForAll (tg_manager *Manager)
Wait for Completion of All Thread Groups.
sdb_errno TgStartGroup (tg_group *Group)
Start All Threads in a Thread Group.
Detailed Description
Thread Group Management System.
Provides a high-level abstraction for managing groups of concurrent threads with shared resources and synchronized lifecycle.
Key Features:
Dynamic thread group creation
Shared data management
Centralized thread lifecycle control
Flexible initialization and cleanup mechanisms
Design Principles:
Minimal synchronization overhead
Centralized thread group management
Extensible thread creation patterns
Definition in file ThreadGroup.h.
Typedef Documentation
tg_cleanup
typedef sdb_errno(* tg_cleanup) (void *)
Cleanup function signature.
Function called after all threads in a group complete
Parameters
arg Shared data to be cleaned up
Returns
sdb_errno Success or error code
Definition at line 63 of file ThreadGroup.h.
tg_init
typedef void *(* tg_init) (void)
Initialization function signature.
Optional function to create or prepare shared data before thread group creation
Returns
void* Initialized shared data
Definition at line 53 of file ThreadGroup.h.
tg_manager
typedef struct tg_manager tg_manager
Definition at line 65 of file ThreadGroup.h.
tg_task
typedef void *(* tg_task) (void *)
Thread task function signature.
Defines the function type for individual thread tasks
Parameters
arg Shared data passed to the thread
Returns
void* Thread return value
Definition at line 42 of file ThreadGroup.h.
Function Documentation
TgCreateGroup()
tg_group * TgCreateGroup (u64 GroupId, u64 ThreadCount, void * SharedData, tg_init Init, tg_task * Tasks, tg_cleanup Cleanup, sdb_arena * A)
Create a Thread Group.
Configures a group of threads with shared resources and optional initialization/cleanup functions
Parameters
GroupId Unique group identifier
ThreadCount Number of threads in the group
SharedData Optional pre-initialized shared data
Init Optional initialization function
Tasks Array of thread task functions
Cleanup Optional cleanup function
A Optional memory arena for allocation
Returns
tg_group* Initialized thread group or NULL
Definition at line 87 of file ThreadGroup.c.
References tg_group::Cleanup, tg_group::Completed, tg_group::GroupId, SdbMemcpy(), SdbPushArray, SdbPushStruct, tg_group::SharedData, tg_group::Tasks, tg_group::ThreadCount, and tg_group::Threads.
Referenced by MbPgCreateTg().
TgCreateManager()
tg_manager * TgCreateManager (tg_group ** Groups, u64 GroupCount, sdb_arena * A)
Create a Thread Group Manager.
Initializes a manager for coordinating multiple thread groups
Parameters
Groups Array of thread groups to manage
GroupCount Number of thread groups
A Optional memory arena for allocation
Returns
tg_manager* Initialized manager or NULL
Definition at line 14 of file ThreadGroup.c.
References tg_manager::CompletedCount, tg_manager::Cond, tg_manager::GroupCount, tg_manager::Groups, tg_group::Manager, tg_manager::Mutex, SdbCondInit(), SdbMutexInit(), SdbPushArray, and SdbPushStruct.
Referenced by SetUpFromConf().
TgDestroyManager()
void TgDestroyManager (tg_manager * M)
Destroy Thread Group Manager.
Releases resources associated with the manager
Parameters
M Manager to destroy
Definition at line 49 of file ThreadGroup.c.
References SdbLogWarning.
Referenced by main(), and SetUpFromConf().
TgManagerStartAll()
sdb_errno TgManagerStartAll (tg_manager * Manager)
Start All Thread Groups in Manager.
Initiates execution of all thread groups managed
Parameters
Manager Thread group manager
Returns
sdb_errno Success or error code
Definition at line 169 of file ThreadGroup.c.
References tg_manager::GroupCount, tg_group::GroupId, tg_manager::Groups, tg_manager::Mutex, SDB_TIMEOUT_MAX, SdbLogError, SdbMutexLock(), SdbMutexUnlock(), and TgStartGroup().
Referenced by main().
TgManagerWaitForAll()
void TgManagerWaitForAll (tg_manager * Manager)
Wait for Completion of All Thread Groups.
Blocks until all thread groups complete or shutdown is requested
Parameters
Manager Thread group manager
Definition at line 187 of file ThreadGroup.c.
References tg_group::Completed, tg_manager::CompletedCount, tg_manager::Cond, tg_manager::GroupCount, tg_group::GroupId, tg_manager::Groups, tg_manager::Mutex, SDB_TIME_S, SDB_TIMEOUT_MAX, SdbCondWait(), SdbLogInfo, SdbMutexLock(), SdbMutexUnlock(), and SdbShouldShutdown().
Referenced by main().
TgStartGroup()
sdb_errno TgStartGroup (tg_group * Group)
Start All Threads in a Thread Group.
Initiates execution of all threads in the group Launches a monitor thread to track group completion
Parameters
Group Thread group to start
Returns
sdb_errno Success or error code
Definition at line 139 of file ThreadGroup.c.
References tg_group::Cleanup, tg_group::GroupId, SdbLogError, tg_group::SharedData, tg_group::Tasks, TgMonitor(), tg_group::ThreadCount, and tg_group::Threads.
Referenced by TgManagerStartAll().