Sensor Data Handler System: src/Common/Thread.h File Reference
Thread.h File Reference
Lightweight Synchronization Primitives Wrapper.
#include <pthread.h>
#include <semaphore.h>
#include <src/Sdb.h>
#include <src/Common/Time.h>
Classes
struct sdb_thread_control
Typedefs
typedef pthread_barrier_t sdb_barrier
typedef pthread_cond_t sdb_cond
typedef pthread_mutex_t sdb_mutex
Functions
sdb_errno SdbBarrierDeinit (sdb_barrier *Barrier)
Deinitialize a thread barrier.
sdb_errno SdbBarrierInit (sdb_barrier *Barrier, u32 ThreadCount)
Initialize a thread barrier.
sdb_errno SdbBarrierWait (sdb_barrier *Barrier)
Wait on a thread barrier.
sdb_errno SdbCondBroadcast (sdb_cond *Cond)
Broadcast on a condition variable.
sdb_errno SdbCondDeinit (sdb_cond *Cond)
Deinitialize a condition variable.
sdb_errno SdbCondInit (sdb_cond *Cond)
Initialize a condition variable.
sdb_errno SdbCondSignal (sdb_cond *Cond)
Signal a condition variable.
sdb_errno SdbCondWait (sdb_cond *Cond, sdb_mutex *Mutex, sdb_timediff Timeout)
Wait on a condition variable with timeout.
sdb_errno SdbMutexDeinit (sdb_mutex *Mutex)
Deinitialize a mutex.
sdb_errno SdbMutexInit (sdb_mutex *Mutex)
Initialize a mutex.
sdb_errno SdbMutexLock (sdb_mutex *Mutex, sdb_timediff Timeout)
Lock a mutex with timeout.
sdb_errno SdbMutexUnlock (sdb_mutex *Mutex)
Unlock a mutex.
sdb_errno SdbSemDeinit (sdb_sem *Sem)
Deinitialize a semaphore.
sdb_errno SdbSemInit (sdb_sem *Sem, u32 InitialValue)
Initialize a semaphore.
sdb_errno SdbSemPost (sdb_sem *Sem)
Post (increment) a semaphore.
sdb_errno SdbSemWait (sdb_sem *Sem, sdb_timediff Timeout)
Wait on a semaphore with timeout.
sdb_errno SdbTCtlDeinit (sdb_thread_control *Control)
bool SdbTCtlHasStoppedLocked (sdb_thread_control *Control)
sdb_errno SdbTCtlInit (sdb_thread_control *Control)
sdb_errno SdbTCtlMarkStopped (sdb_thread_control *Control)
bool SdbTCtlShouldStop (sdb_thread_control *Control)
bool SdbTCtlShouldStopLocked (sdb_thread_control *Control)
sdb_errno SdbTCtlSignalStop (sdb_thread_control *Control)
sdb_errno SdbTCtlWaitForSignal (sdb_thread_control *Control)
sdb_errno SdbTCtlWaitForStop (sdb_thread_control *Control)
Variables
SDB_BEGIN_EXTERN_C typedef sem_t sdb_sem
Detailed Description
Lightweight Synchronization Primitives Wrapper.
Provides a unified, error-handled interface for POSIX threading synchronization mechanisms.
Key Features:
Semaphore management
Mutex operations
Condition variable handling
Thread control utilities
Design Principles:
Consistent error handling
Timeout-based blocking primitives
Minimal abstraction overhead
Definition in file Thread.h.
Typedef Documentation
sdb_barrier
typedef pthread_barrier_t sdb_barrier
Definition at line 37 of file Thread.h.
sdb_cond
typedef pthread_cond_t sdb_cond
Definition at line 36 of file Thread.h.
sdb_mutex
typedef pthread_mutex_t sdb_mutex
Definition at line 35 of file Thread.h.
Function Documentation
SdbBarrierDeinit()
sdb_errno SdbBarrierDeinit (sdb_barrier * Barrier)
Deinitialize a thread barrier.
Parameters
Barrier Barrier to deinitialize
Returns
sdb_errno Success or error code
Definition at line 203 of file Thread.c.
Referenced by MbPgCleanup().
SdbBarrierInit()
sdb_errno SdbBarrierInit (sdb_barrier * Barrier, u32 ThreadCount)
Initialize a thread barrier.
Parameters
Barrier Barrier to initialize
ThreadCount Number of threads to synchronize
Returns
sdb_errno Success or error code
Definition at line 192 of file Thread.c.
Referenced by MbPgCreateTg().
SdbBarrierWait()
sdb_errno SdbBarrierWait (sdb_barrier * Barrier)
Wait on a thread barrier.
Parameters
Barrier Barrier to wait on
Returns
sdb_errno Success or error code
Definition at line 210 of file Thread.c.
Referenced by MbPipeThroughputTest(), MbRun(), PgRun(), and RunModbusTestServer().
SdbCondBroadcast()
sdb_errno SdbCondBroadcast (sdb_cond * Cond)
Broadcast on a condition variable.
Parameters
Cond Condition variable to broadcast
Returns
sdb_errno Success or error code
Definition at line 180 of file Thread.c.
References SdbLogDebug, and SdbLogError.
Referenced by SdbTCtlMarkStopped(), and SdbTCtlSignalStop().
SdbCondDeinit()
sdb_errno SdbCondDeinit (sdb_cond * Cond)
Deinitialize a condition variable.
Parameters
Cond Condition variable to deinitialize
Returns
sdb_errno Success or error code
Definition at line 145 of file Thread.c.
Referenced by SdbTCtlDeinit().
SdbCondInit()
sdb_errno SdbCondInit (sdb_cond * Cond)
Initialize a condition variable.
Parameters
Cond Condition variable to initialize
Returns
sdb_errno Success or error code
Definition at line 138 of file Thread.c.
Referenced by SdbTCtlInit(), and TgCreateManager().
SdbCondSignal()
sdb_errno SdbCondSignal (sdb_cond * Cond)
Signal a condition variable.
Parameters
Cond Condition variable to signal
Returns
sdb_errno Success or error code
Definition at line 173 of file Thread.c.
Referenced by TgMonitor().
SdbCondWait()
sdb_errno SdbCondWait (sdb_cond * Cond, sdb_mutex * Mutex, sdb_timediff Timeout)
Wait on a condition variable with timeout.
Parameters
Cond Condition variable to wait on
Mutex Associated mutex
Timeout Maximum wait time
Returns
sdb_errno Success or error code
Definition at line 152 of file Thread.c.
References CreateTimeout(), SDB_TIME_EQ, SDB_TIMEOUT_MAX, and SDB_TIMEOUT_NONE.
Referenced by SdbTCtlWaitForSignal(), SdbTCtlWaitForStop(), and TgManagerWaitForAll().
SdbMutexDeinit()
sdb_errno SdbMutexDeinit (sdb_mutex * Mutex)
Deinitialize a mutex.
Parameters
Mutex Mutex to deinitialize
Returns
sdb_errno Success or error code
Definition at line 102 of file Thread.c.
Referenced by SdbTCtlDeinit(), and SdbTCtlInit().
SdbMutexInit()
sdb_errno SdbMutexInit (sdb_mutex * Mutex)
Initialize a mutex.
Parameters
Mutex Mutex to initialize
Returns
sdb_errno Success or error code
Definition at line 95 of file Thread.c.
Referenced by SdbTCtlInit(), and TgCreateManager().
SdbMutexLock()
sdb_errno SdbMutexLock (sdb_mutex * Mutex, sdb_timediff Timeout)
Lock a mutex with timeout.
Parameters
Mutex Mutex to lock
Timeout Maximum wait time
Returns
sdb_errno Success or error code
Definition at line 109 of file Thread.c.
References CreateTimeout(), SDB_TIME_EQ, SDB_TIMEOUT_MAX, and SDB_TIMEOUT_NONE.
Referenced by SdbTCtlMarkStopped(), SdbTCtlShouldStop(), SdbTCtlSignalStop(), SdbTCtlWaitForSignal(), SdbTCtlWaitForStop(), TgManagerStartAll(), TgManagerWaitForAll(), and TgMonitor().
SdbMutexUnlock()
sdb_errno SdbMutexUnlock (sdb_mutex * Mutex)
Unlock a mutex.
Parameters
Mutex Mutex to unlock
Returns
sdb_errno Success or error code
Definition at line 130 of file Thread.c.
Referenced by SdbTCtlMarkStopped(), SdbTCtlShouldStop(), SdbTCtlSignalStop(), SdbTCtlWaitForSignal(), SdbTCtlWaitForStop(), TgManagerStartAll(), TgManagerWaitForAll(), and TgMonitor().
SdbSemDeinit()
sdb_errno SdbSemDeinit (sdb_sem * Sem)
Deinitialize a semaphore.
Parameters
Sem Semaphore to deinitialize
Returns
sdb_errno Success or error code
Definition at line 52 of file Thread.c.
SdbSemInit()
sdb_errno SdbSemInit (sdb_sem * Sem, u32 InitialValue)
Initialize a semaphore.
Parameters
Sem Semaphore to initialize
InitialValue Initial semaphore value
Returns
sdb_errno Success or error code
Definition at line 42 of file Thread.c.
SdbSemPost()
sdb_errno SdbSemPost (sdb_sem * Sem)
Post (increment) a semaphore.
Parameters
Sem Semaphore to post
Returns
sdb_errno Success or error code
Definition at line 84 of file Thread.c.
SdbSemWait()
sdb_errno SdbSemWait (sdb_sem * Sem, sdb_timediff Timeout)
Wait on a semaphore with timeout.
Parameters
Sem Semaphore to wait on
Timeout Maximum wait time
Returns
sdb_errno Success or error code
Definition at line 59 of file Thread.c.
References CreateTimeout(), SDB_TIME_EQ, SDB_TIMEOUT_MAX, and SDB_TIMEOUT_NONE.
SdbTCtlDeinit()
sdb_errno SdbTCtlDeinit (sdb_thread_control * Control)
Definition at line 240 of file Thread.c.
References sdb_thread_control::Cond, sdb_thread_control::Mutex, SdbCondDeinit(), and SdbMutexDeinit().
SdbTCtlHasStoppedLocked()
bool SdbTCtlHasStoppedLocked (sdb_thread_control * Control)
Definition at line 264 of file Thread.c.
References sdb_thread_control::HasStopped.
Referenced by SdbTCtlWaitForStop().
SdbTCtlInit()
sdb_errno SdbTCtlInit (sdb_thread_control * Control)
Definition at line 218 of file Thread.c.
References sdb_thread_control::Cond, sdb_thread_control::HasStopped, sdb_thread_control::Mutex, SdbCondInit(), SdbMutexDeinit(), SdbMutexInit(), sdb_thread_control::ShouldStop, and sdb_thread_control::WaitingForSignalStop.
SdbTCtlMarkStopped()
sdb_errno SdbTCtlMarkStopped (sdb_thread_control * Control)
Definition at line 295 of file Thread.c.
References sdb_thread_control::Cond, sdb_thread_control::HasStopped, sdb_thread_control::Mutex, SDB_TIMEOUT_MAX, SdbCondBroadcast(), SdbLogError, SdbMutexLock(), SdbMutexUnlock(), and sdb_thread_control::WaitingForMarkStopped.
SdbTCtlShouldStop()
bool SdbTCtlShouldStop (sdb_thread_control * Control)
Definition at line 248 of file Thread.c.
References sdb_thread_control::Mutex, SDB_TIMEOUT_MAX, SdbMutexLock(), SdbMutexUnlock(), and sdb_thread_control::ShouldStop.
SdbTCtlShouldStopLocked()
bool SdbTCtlShouldStopLocked (sdb_thread_control * Control)
Definition at line 258 of file Thread.c.
References sdb_thread_control::ShouldStop.
Referenced by SdbTCtlWaitForSignal().
SdbTCtlSignalStop()
sdb_errno SdbTCtlSignalStop (sdb_thread_control * Control)
Definition at line 270 of file Thread.c.
References sdb_thread_control::Cond, sdb_thread_control::Mutex, SDB_TIMEOUT_MAX, SdbCondBroadcast(), SdbMutexLock(), SdbMutexUnlock(), sdb_thread_control::ShouldStop, and sdb_thread_control::WaitingForSignalStop.
SdbTCtlWaitForSignal()
sdb_errno SdbTCtlWaitForSignal (sdb_thread_control * Control)
Definition at line 282 of file Thread.c.
References sdb_thread_control::Cond, sdb_thread_control::Mutex, SDB_TIMEOUT_MAX, SdbCondWait(), SdbMutexLock(), SdbMutexUnlock(), SdbTCtlShouldStopLocked(), and sdb_thread_control::WaitingForSignalStop.
SdbTCtlWaitForStop()
sdb_errno SdbTCtlWaitForStop (sdb_thread_control * Control)
Definition at line 311 of file Thread.c.
References sdb_thread_control::Cond, sdb_thread_control::Mutex, SDB_TIMEOUT_MAX, SdbCondWait(), SdbMutexLock(), SdbMutexUnlock(), SdbTCtlHasStoppedLocked(), and sdb_thread_control::WaitingForMarkStopped.
Variable Documentation
sdb_sem
SDB_BEGIN_EXTERN_C typedef sem_t sdb_sem
Definition at line 34 of file Thread.h.