Sensor Data Handler System: src/Common/Time.c File Reference
Time.c File Reference
Implementation of Time Manipulation Utilities.
#include <time.h>
#include <src/Sdb.h>
#include <src/Common/Time.h>
Functions
sdb_errno SdbSleep (sdb_timediff Delta)
Sleep for Specified Time.
void SdbTimeAdd (struct timespec *Timespec, sdb_timediff Delta)
Add Time Difference to Timestamp.
sdb_errno SdbTimeMonotonic (struct timespec *TimeStamp)
Get Current Monotonic Timestamp.
sdb_errno SdbTimeNow (struct timespec *Timespec)
Get Current Real-Time Timestamp.
bool SdbTimeoutExpired (struct timespec *Timeout, struct timespec *Now)
Check if Timeout Has Expired.
sdb_errno SdbTimePrintSpecDiffWT (const struct timespec *StartTime, const struct timespec *EndTime, struct timespec *Diff)
Calculate Time Difference Between Timestamps.
void SdbTimespec (struct timespec *Timespec, sdb_timediff Delta)
Convert Time Difference to Timespec.
sdb_errno SdbTimespecAbsolute (struct timespec *Timespec, sdb_timediff Delta)
Create Absolute Timeout Timestamp.
void SdbTimeval (struct timeval *Timeval, sdb_timediff Delta)
Convert Time Difference to Timeval.
Detailed Description
Implementation of Time Manipulation Utilities.
Definition in file Time.c.
Function Documentation
SdbSleep()
sdb_errno SdbSleep (sdb_timediff Delta)
Sleep for Specified Time.
Pauses execution for a given time difference
Parameters
Delta Time to sleep
Returns
sdb_errno Success or error code
Definition at line 107 of file Time.c.
References SdbTimespec().
SdbTimeAdd()
void SdbTimeAdd (struct timespec * Timespec, sdb_timediff Delta)
Add Time Difference to Timestamp.
Modifies a timestamp by adding a time difference
Parameters
Timespec Timestamp to modify
Delta Time difference to add
Definition at line 35 of file Time.c.
References SDB_TIME_TO_NS, and SDB_TIME_TO_S.
Referenced by SdbTimespecAbsolute().
SdbTimeMonotonic()
sdb_errno SdbTimeMonotonic (struct timespec * TimeStamp)
Get Current Monotonic Timestamp.
Retrieves a monotonically increasing timestamp
Parameters
TimeStamp Pointer to timespec structure to store timestamp
Returns
sdb_errno Success or error code
Definition at line 25 of file Time.c.
Referenced by PgRun().
SdbTimeNow()
sdb_errno SdbTimeNow (struct timespec * Timespec)
Get Current Real-Time Timestamp.
Retrieves the current system time using CLOCK_REALTIME
Parameters
Timespec Pointer to timespec structure to store timestamp
Returns
sdb_errno Success or error code
Definition at line 15 of file Time.c.
Referenced by SdbTimespecAbsolute().
SdbTimeoutExpired()
bool SdbTimeoutExpired (struct timespec * Timeout, struct timespec * Now)
Check if Timeout Has Expired.
Compares current time against a timeout timestamp
Parameters
Timeout Timeout timestamp
Now Current timestamp
Returns
bool True if timeout has expired
Definition at line 98 of file Time.c.
SdbTimePrintSpecDiffWT()
sdb_errno SdbTimePrintSpecDiffWT (const struct timespec * StartTime, const struct timespec * EndTime, struct timespec * Diff)
Calculate Time Difference Between Timestamps.
Computes the difference between two timestamps
Parameters
StartTime Beginning timestamp
EndTime Ending timestamp
Diff Optional pointer to store time difference
Returns
sdb_errno Success or error code
Definition at line 60 of file Time.c.
References SdbMemcpy(), and SdbPrintfDebug.
Referenced by PgRun().
SdbTimespec()
void SdbTimespec (struct timespec * Timespec, sdb_timediff Delta)
Convert Time Difference to Timespec.
Converts a time difference to a timespec structure
Parameters
Timespec Pointer to store timespec
Delta Time difference to convert
Definition at line 84 of file Time.c.
References SDB_TIME_TO_NS, and SDB_TIME_TO_S.
Referenced by SdbSleep().
SdbTimespecAbsolute()
sdb_errno SdbTimespecAbsolute (struct timespec * Timespec, sdb_timediff Delta)
Create Absolute Timeout Timestamp.
Generates a future timestamp based on current time and delta
Parameters
Timespec Pointer to store absolute timestamp
Delta Time difference from now
Returns
sdb_errno Success or error code
Definition at line 47 of file Time.c.
References SdbTimeAdd(), and SdbTimeNow().
Referenced by CreateTimeout().
SdbTimeval()
void SdbTimeval (struct timeval * Timeval, sdb_timediff Delta)
Convert Time Difference to Timeval.
Converts a time difference to a timeval structure
Parameters
Timeval Pointer to store timeval
Delta Time difference to convert
Definition at line 91 of file Time.c.
References SDB_TIME_TO_S, and SDB_TIME_TO_US.
Referenced by SocketRecvWithTimeout().