Sensor Data Handler System: src/Common/Time.h File Reference
Time.h File Reference
Lightweight Time Manipulation Utilities.
#include <limits.h>
#include <time.h>
#include <src/Sdb.h>
Macros
#define SDB_TIME_BASE_NS_ (1)
#define SDB_TIME_EQ(t1, t2) (t1 == t2)
#define SDB_TIME_MAX ((sdb_timediff){ UINT64_MAX })
#define SDB_TIME_MS(ms) ((sdb_timediff){ ms * 1e6 * SDB_TIME_BASE_NS_ })
#define SDB_TIME_NS(ns) ((sdb_timediff){ ns * 1 * SDB_TIME_BASE_NS_ })
#define SDB_TIME_S(s) ((sdb_timediff){ s * 1e9 * SDB_TIME_BASE_NS_ })
#define SDB_TIME_TO_MS(ns) ((u64)(ns / (1e6 * SDB_TIME_BASE_NS_)))
#define SDB_TIME_TO_NS(ns) ((uint64_t)(ns / (1 * SDB_TIME_BASE_NS_)))
#define SDB_TIME_TO_S(ns) ((u64)(ns / (1e9 * SDB_TIME_BASE_NS_)))
#define SDB_TIME_TO_US(ns) ((uint64_t)(ns / (1e3 * SDB_TIME_BASE_NS_)))
#define SDB_TIME_US(us) ((sdb_timediff){ us * 1e3 * SDB_TIME_BASE_NS_ })
#define SDB_TIMEOUT_MAX (SDB_TIME_MAX)
#define SDB_TIMEOUT_NONE (SDB_TIME_NS(0))
Typedefs
typedef u64 sdb_timediff
Functions
sdb_errno SdbSleep (sdb_timediff Delta)
Sleep for Specified Time.
void SdbTimeAdd (struct timespec *Timespec, sdb_timediff Delta)
Add Time Difference to Timestamp.
sdb_errno SdbTimeMonotonic (struct timespec *TimeStamp)
Get Current Monotonic Timestamp.
sdb_errno SdbTimeNow (struct timespec *Timespec)
Get Current Real-Time Timestamp.
bool SdbTimeoutExpired (struct timespec *Timeout, struct timespec *Now)
Check if Timeout Has Expired.
sdb_errno SdbTimePrintSpecDiffWT (const struct timespec *StartTime, const struct timespec *EndTime, struct timespec *Diff)
Calculate Time Difference Between Timestamps.
void SdbTimespec (struct timespec *Timespec, sdb_timediff Delta)
Convert Time Difference to Timespec.
sdb_errno SdbTimespecAbsolute (struct timespec *Timespec, sdb_timediff Delta)
Create Absolute Timeout Timestamp.
void SdbTimeval (struct timeval *Timeval, sdb_timediff Delta)
Convert Time Difference to Timeval.
Detailed Description
Lightweight Time Manipulation Utilities.
Provides a set of time-related macros, conversions, and utility functions for high-precision time management.
Definition in file Time.h.
Macro Definition Documentation
SDB_TIME_BASE_NS_
#define SDB_TIME_BASE_NS_ (1)
Definition at line 23 of file Time.h.
SDB_TIME_EQ
#define SDB_TIME_EQ (t1, t2) (t1 == t2)
Definition at line 27 of file Time.h.
SDB_TIME_MAX
#define SDB_TIME_MAX ((sdb_timediff){ UINT64_MAX })
Definition at line 29 of file Time.h.
SDB_TIME_MS
#define SDB_TIME_MS (ms) ((sdb_timediff){ ms * 1e6 * SDB_TIME_BASE_NS_ })
Definition at line 34 of file Time.h.
SDB_TIME_NS
#define SDB_TIME_NS (ns) ((sdb_timediff){ ns * 1 * SDB_TIME_BASE_NS_ })
Definition at line 40 of file Time.h.
SDB_TIME_S
#define SDB_TIME_S (s) ((sdb_timediff){ s * 1e9 * SDB_TIME_BASE_NS_ })
Definition at line 31 of file Time.h.
SDB_TIME_TO_MS
#define SDB_TIME_TO_MS (ns) ((u64)(ns / (1e6 * SDB_TIME_BASE_NS_)))
Definition at line 35 of file Time.h.
SDB_TIME_TO_NS
#define SDB_TIME_TO_NS (ns) ((uint64_t)(ns / (1 * SDB_TIME_BASE_NS_)))
Definition at line 41 of file Time.h.
SDB_TIME_TO_S
#define SDB_TIME_TO_S (ns) ((u64)(ns / (1e9 * SDB_TIME_BASE_NS_)))
Definition at line 32 of file Time.h.
SDB_TIME_TO_US
#define SDB_TIME_TO_US (ns) ((uint64_t)(ns / (1e3 * SDB_TIME_BASE_NS_)))
Definition at line 38 of file Time.h.
SDB_TIME_US
#define SDB_TIME_US (us) ((sdb_timediff){ us * 1e3 * SDB_TIME_BASE_NS_ })
Definition at line 37 of file Time.h.
SDB_TIMEOUT_MAX
#define SDB_TIMEOUT_MAX (SDB_TIME_MAX)
Definition at line 44 of file Time.h.
SDB_TIMEOUT_NONE
#define SDB_TIMEOUT_NONE (SDB_TIME_NS(0))
Definition at line 43 of file Time.h.
Typedef Documentation
sdb_timediff
typedef u64 sdb_timediff
Definition at line 25 of file Time.h.
Function Documentation
SdbSleep()
sdb_errno SdbSleep (sdb_timediff Delta)
Sleep for Specified Time.
Pauses execution for a given time difference
Parameters
Delta Time to sleep
Returns
sdb_errno Success or error code
Definition at line 107 of file Time.c.
References SdbTimespec().
SdbTimeAdd()
void SdbTimeAdd (struct timespec * Timespec, sdb_timediff Delta)
Add Time Difference to Timestamp.
Modifies a timestamp by adding a time difference
Parameters
Timespec Timestamp to modify
Delta Time difference to add
Definition at line 35 of file Time.c.
References SDB_TIME_TO_NS, and SDB_TIME_TO_S.
Referenced by SdbTimespecAbsolute().
SdbTimeMonotonic()
sdb_errno SdbTimeMonotonic (struct timespec * TimeStamp)
Get Current Monotonic Timestamp.
Retrieves a monotonically increasing timestamp
Parameters
TimeStamp Pointer to timespec structure to store timestamp
Returns
sdb_errno Success or error code
Definition at line 25 of file Time.c.
Referenced by PgRun().
SdbTimeNow()
sdb_errno SdbTimeNow (struct timespec * Timespec)
Get Current Real-Time Timestamp.
Retrieves the current system time using CLOCK_REALTIME
Parameters
Timespec Pointer to timespec structure to store timestamp
Returns
sdb_errno Success or error code
Definition at line 15 of file Time.c.
Referenced by SdbTimespecAbsolute().
SdbTimeoutExpired()
bool SdbTimeoutExpired (struct timespec * Timeout, struct timespec * Now)
Check if Timeout Has Expired.
Compares current time against a timeout timestamp
Parameters
Timeout Timeout timestamp
Now Current timestamp
Returns
bool True if timeout has expired
Definition at line 98 of file Time.c.
SdbTimePrintSpecDiffWT()
sdb_errno SdbTimePrintSpecDiffWT (const struct timespec * StartTime, const struct timespec * EndTime, struct timespec * Diff)
Calculate Time Difference Between Timestamps.
Computes the difference between two timestamps
Parameters
StartTime Beginning timestamp
EndTime Ending timestamp
Diff Optional pointer to store time difference
Returns
sdb_errno Success or error code
Definition at line 60 of file Time.c.
References SdbMemcpy(), and SdbPrintfDebug.
Referenced by PgRun().
SdbTimespec()
void SdbTimespec (struct timespec * Timespec, sdb_timediff Delta)
Convert Time Difference to Timespec.
Converts a time difference to a timespec structure
Parameters
Timespec Pointer to store timespec
Delta Time difference to convert
Definition at line 84 of file Time.c.
References SDB_TIME_TO_NS, and SDB_TIME_TO_S.
Referenced by SdbSleep().
SdbTimespecAbsolute()
sdb_errno SdbTimespecAbsolute (struct timespec * Timespec, sdb_timediff Delta)
Create Absolute Timeout Timestamp.
Generates a future timestamp based on current time and delta
Parameters
Timespec Pointer to store absolute timestamp
Delta Time difference from now
Returns
sdb_errno Success or error code
Definition at line 47 of file Time.c.
References SdbTimeAdd(), and SdbTimeNow().
Referenced by CreateTimeout().
SdbTimeval()
void SdbTimeval (struct timeval * Timeval, sdb_timediff Delta)
Convert Time Difference to Timeval.
Converts a time difference to a timeval structure
Parameters
Timeval Pointer to store timeval
Delta Time difference to convert
Definition at line 91 of file Time.c.
References SDB_TIME_TO_S, and SDB_TIME_TO_US.
Referenced by SocketRecvWithTimeout().